---
title: "Welcome to BMSC 620"
author: "Emile Latour"
date: "`r library(here); source(here('class_dates.R')); w1d1`"
date-format: long
format:
  revealjs:
    theme: "../../assets/css/reveal-bmsc620_v4.scss"
    slide-number: true
    show-slide-number: all
    width: 1955
    height: 1100
    footer: "BMSC 620"
    header-includes: |
      <style>
      #wrap {
        width: 1650px;
        height: 900px;
        margin: 0 auto;
        overflow: hidden;
        border: 1px solid #999;
        border-radius: 8px;
      }
      #frame {
        width: 1650px;
        height: 900px;
        border: 0;
        zoom: 1.25;
        -moz-transform: scale(1.25);
        -moz-transform-origin: 0 0;
      }
      </style>
execute:
  echo: true
  freeze: auto
---

```{r setup, include=FALSE}
library(here)
source(here("class_dates.R"))

library(tidyverse)
```

## Welcome to BMSC 620

<br><br>

**Emile Latour, MS**  
Biostatistician, OHSU Knight Cancer Institute

&nbsp;

This course builds on prior versions developed by  
**Meike Niederhausen** and **Nicky Wakim**, with updates and revisions for Winter 2026.

## Some important tasks

<br>

- **Bookmark the course website**  
  <https://emilelatour.github.io/BMSC_620_W26/>
  
&nbsp;

- **Complete Homework 0 by Sunday at 11:00 pm**
  - Get comfortable with RStudio and Quarto
  - Make sure you can render a document successfully
  - This assignment is graded for completion only
  
&nbsp;

- **Make sure you have access to the textbook**
  - Details are posted on the course website


## Let's visit the website: Homepage

```{=html}
<div id="wrap">
  <iframe id="frame" src="https://emilelatour.github.io/BMSC_620_W26/"></iframe>
</div>
```

## Course information on the website

- **Syllabus**
  - What this course is about
  - How grading and homework work
  - Exams, attendance, and course policies

- **Instructors**
  - Contact information
  - Office hours
  - How to get help

- **Resources**
  - R and RStudio installation instructions
  - Course materials and datasets
  - Additional support resources

## Let's visit the website: Syllabus

```{=html}
<div id="wrap">
  <iframe id="frame" src="https://emilelatour.github.io/BMSC_620_W26/syllabus.html"></iframe>
</div>
```

## Let's visit the website: Instructors

```{=html}
<div id="wrap">
  <iframe id="frame" src="https://emilelatour.github.io/BMSC_620_W26/instructors.html"></iframe>
</div>
```

## Let's visit the website: Resources

```{=html}
<div id="wrap">
  <iframe id="frame" src="https://emilelatour.github.io/BMSC_620_W26/resources.html"></iframe>
</div>
```

## How this course runs on the website

- **Schedule**
  - Big-picture view of topics and due dates
  - Updated if anything changes

- **Weekly materials**
  - What to read or review
  - Slides, code, and links for each class

- **Homework**
  - Assignment templates
  - Due dates and grading expectations

- **Exams**
  - Midterm and final format
  - Timing, coverage, and policies

## Let's visit the website: Schedule

```{=html}
<div id="wrap">
  <iframe id="frame" src="https://emilelatour.github.io/BMSC_620_W26/schedule.html"></iframe>
</div>
```

## Let's visit the website: Weekly materials

```{=html}
<div id="wrap">
  <iframe id="frame" src="https://emilelatour.github.io/BMSC_620_W26/weeks/week_01.html"></iframe>
</div>
```

## Let's visit the website: Homework

```{=html}
<div id="wrap">
  <iframe id="frame" src="https://emilelatour.github.io/BMSC_620_W26/homework.html"></iframe>
</div>
```

## Let's visit the website: Exams

```{=html}
<div id="wrap">
  <iframe id="frame" src="https://emilelatour.github.io/BMSC_620_W26/exams.html"></iframe>
</div>
```

## Structure for this course

- Learning the core tools to **understand and interpret statistics**
  
&nbsp;

- Some pieces may feel abstract or disconnected at first — that’s normal
  
&nbsp;

- The goal is to build a **toolbox** that lets you analyze data *and* explain what the results mean

## Let me know if you have questions

Or if you notice:

- something unclear
- something confusing
- or something that contradicts the course site

## That’s it for logistics

- The course website is your home base
- Homework 0 is due **Sunday at 11:00 pm**
- Reach out early if something is confusing

Let’s shift gears and start the course.