---
title: "Schedule"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    page-layout: full
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(here)
source(here("class_dates.R"))
```

<!-- ### Week 1 (`{r} format(w1d1, '%b %d')`–`{r} format(w1d1 + 6, '%b %d')`) -->

<!-- Schedule table: Date | Lesson | Topic | Textbook -->

<!-- |  Date    |   Lesson  |   Topic   |   Textbook sections   | -->

<!-- |  :---:   |   :---:   |   --- |   :---:   | -->

<!-- |  `{r} format(w1d1, '%a, %m/%d')` |   0   |   Welcome |   X.X | -->

<!-- |      |   1   |   Data collection |   1.3 | -->

<!-- |  `{r} format(w1d2, '%a, %m/%d')` |   2   |   Intro to data & numerical summaries |   1.2, 1.4    | -->

<!-- |  [**`{r} format(hw0, '%a, %m/%d')`**]{.hw-row}   |       |   [**HW 0 due @ 11 pm**]{.hw-row} |       | -->

<!-- : {.hover tbl-colwidths="[7, 6, 40, 8]"}        -->

<!-- ### Week 2 (`{r} format(w2d1, '%b %d')`–`{r} format(w2d1 + 6, '%b %d')`) -->

<!-- Schedule table: Date | Lesson | Topic | Textbook -->

<!-- |  Date    |   Lesson  |   Topic   |   Textbook sections   | -->

<!-- |  :---:   |   :---:   |   --- |   :---:   | -->

<!-- |  `{r} format(w2d1, '%a, %m/%d')` |   3   |   Defining probability    |   2.1 | -->

<!-- |      |   R01 |   Download R and RStudio  |       | -->

<!-- |  `{r} format(w2d2, '%a, %m/%d')` |   4   |   Conditional probability |   2.2 | -->

<!-- |      |   R02 |   R Basics, part 1    |       | -->

<!-- : {.hover tbl-colwidths="[7, 6, 40, 8]"}    -->

<!-- FULL SCHEDULE -->

| Week | Dates | Lesson | Topics | Chapter sections |
|:-------------:|:-------------:|:-------------:|---------------|:-------------:|
| 1 | `{r} format(w1d1, '%a, %m/%d')` | 0 | Welcome |  |
|  |  | 1 | Intro to Data, Summarizing numerical data | 1.1-1.4 |
|  | `{r} format(w1d2, '%a, %m/%d')` | 2 | Introduction to R & RStudio |  |
|  | [**`{r} format(hw0, '%a, %m/%d')`**]{.hw-row} |  | [**HW 0 due \@ 11 pm**]{.hw-row} |  |
|  |  |  |  |  |
| 2 | `{r} format(w2d1, '%a, %m/%d')` | 3 | Probability | 2.1-2.4 |
|  | `{r} format(w2d2, '%a, %m/%d')` | 4 | Data visualization, exploratory data analysis (EDA), and summarizing categorical data | 1.5-1.7 |
|  | [**`{r} format(hw1, '%a, %m/%d')`**]{.hw-row} |  | [**HW 1 due \@ 11 pm**]{.hw-row} |  |
|  |  |  |  |  |
| 3 | **`{r} format(w3d1, '%a, %m/%d')`** |  | **No class, Martin Luther King Jr. Day** |  |
|  | `{r} format(w3d2, '%a, %m/%d')` | 5 | Data visualization (continued) | 1.5-1.7 |
|  | [**`{r} format(hw2, '%a, %m/%d')`**]{.hw-row} |  | [**HW 2 due \@ 11 pm**]{.hw-row} |  |
|  |  |  |  |  |
| 4 | `{r} format(w4d1, '%a, %m/%d')` | 6 | Random variables and the binomial distribution | 3.1-3.2 |
|  | `{r} format(w4d2, '%a, %m/%d')` | 7 | Normal distribution and sampling distributions | 3.3-3.4 |
|  | [**`{r} format(hw3, '%a, %m/%d')`**]{.hw-row} |  | [**HW 3 due \@ 11 pm**]{.hw-row} |  |
|  |  |  |  |  |
| 5 | `{r} format(w5d1, '%a, %m/%d')` | 8 | Estimation and confidence intervals | 4.1-4.2 |
|  | `{r} format(w5d2, '%a, %m/%d')` | 9 | Hypothesis testing concepts; One-sample t-tests | 4.3, 5.1 |
|  | [**`{r} format(hw4, '%a, %m/%d')`**]{.hw-row} |  | [**HW 4 due \@ 11 pm**]{.hw-row} |  |
|  |  |  |  |  |
| 6 | `{r} format(w6d1, '%a, %m/%d')` | 10 | Paired data and paired t-tests; Two-sample independent t-tests | 5.2-5.3 |
|  | `{r} format(w6d2, '%a, %m/%d')` | 11 | Power; Midterm review | 5.4 |
|  | [**`{r} format(mid_opens, '%a, %m/%d')`**]{.hw-row} |  | [**MIDTERM opens at 3pm**]{.hw-row} |  |
|  |  |  | Midterm will cover Lessons 1–9 |  |
|  | [**`{r} format(mid_closes, '%a, %m/%d')`**]{.hw-row} |  | [**MIDTERM closes at 11pm**]{.hw-row} |  |
|  |  |  |  |  |
| 7 | **`{r} format(w7d1, '%a, %m/%d')`** |  | **No class, Presidents Day** |  |
|  | `{r} format(w7d2, '%a, %m/%d')` | 12 | Power (continued) | 5.4, extra |
|  | [**`{r} format(hw5, '%a, %m/%d')`**]{.hw-row} |  | [**HW 5 due \@ 11 pm**]{.hw-row} |  |
|  |  |  |  |  |
| 8 | `{r} format(w8d1, '%a, %m/%d')` | 13 | Inference for proportions and 2x2 tables | 8.1-8.2 |
|  | `{r} format(w8d2, '%a, %m/%d')` | 14 | Chi-squared tests, Fishers exact test | 8.3-8.4 |
|  | [**`{r} format(hw6, '%a, %m/%d')`**]{.hw-row} |  | [**HW 6 due \@ 11 pm**]{.hw-row} |  |
|  |  |  |  |  |
| 9 | `{r} format(w9d1, '%a, %m/%d')` | 15 | Comparing Means with ANOVA. | 5.5, extra |
|  | `{r} format(w9d2, '%a, %m/%d')` | 16 | Nonparametric tests | Extra |
|  | [**`{r} format(hw7, '%a, %m/%d')`**]{.hw-row} |  | [**HW 7 due \@ 11 pm**]{.hw-row} |  |
|  |  |  |  |  |
| 10 | `{r} format(w10d1, '%a, %m/%d')` | 17 | Correlation and association | 1.6, extra |
|  | `{r} format(w10d2, '%a, %m/%d')` | 18 | Simple Linear Regression | 6.1-6.2 |
|  | [**`{r} format(hw8, '%a, %m/%d')`**]{.hw-row} |  | [**HW 8 due \@ 11 pm**]{.hw-row} |  |
|  |  |  |  |  |
| 11 | `{r} format(w11d1, '%a, %m/%d')` | 19 | Simple Linear Regression; Finals review | 6.3-6.4 |
|  | [**`{r} format(final_opens, '%a, %m/%d')`**]{.hw-row} |  | [**FINAL opens at 3pm**]{.hw-row} |  |
|  |  |  | Final exam is cumulative, with emphasis on Lessons 10–19 |  |
|  | `{r} format(w11d2, '%a, %m/%d')` | 20 | Optional: Review and questions (no new material) | 7.1 |
|  | [**`{r} format(final_closes, '%a, %m/%d')`**]{.hw-row} |  | [**FINAL closes at 5pm**]{.hw-row} |  |

: {.hover tbl-colwidths="\[7, 8, 6, 40, 8\]"}
