{
  "hash": "04a634a044e2348f76f37c22cfed3efd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Correlation and Simple Linear Regression\"\nsubtitle: \"Textbook Sections 1.6, 6.1-6.4\"\nauthor: \"Emile Latour, Nicky Wakim, Meike Niederhausen\"\ndate: \"2026-03-11\"\ndate-format: long\nformat:\n  revealjs:\n    theme: \"../../assets/css/reveal-bmsc620_v5.scss\"\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"BMSC 620 | Correlation and Simple Linear Regression\"\n    html-math-method: mathjax\n    chalkboard: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n  freeze: auto\n---\n\n\n\n\n\n\n# Learning Objectives\n\nBy the end of today's lecture, you will be able to:\n\n1. Calculate and interpret Pearson and Spearman correlation coefficients\n2. Identify the components of the simple linear regression model\n3. Explain what ordinary least squares (OLS) minimizes\n4. Run a simple linear regression in R and interpret the output\n5. Check the LINE assumptions using diagnostic plots\n6. Interpret $R^2$ as a measure of model fit\n7. Conduct and interpret inference for the population slope $\\beta_1$\n8. Construct confidence and prediction intervals for new observations\n\n## Roadmap for Today\n\n\\\n\n::::: columns\n::: {.column width=\"50%\"}\n**Part 1: Correlation**\n\n- Visualizing two continuous variables\n- Pearson correlation: $r$\n- Spearman correlation: a nonparametric bridge\n- Correlation ≠ causation\n\n**Part 2: The SLR Model**\n\n- From correlation to regression\n- Population model vs. estimated line\n- Residuals and OLS\n- Running `lm()` in R\n- Interpreting slope and intercept\n:::\n\n::: {.column width=\"50%\"}\n**Part 3: Model Evaluation**\n\n- LINE assumptions\n- Diagnostic plots in R\n- $R^2$: how much variation does the model explain?\n\n**Part 4: Inference and Prediction**\n\n- Hypothesis test for slope $\\beta_1$\n- Confidence interval for $\\beta_1$\n- Predicting new observations\n- CI for mean response vs. prediction interval\n:::\n:::::\n\n# Part 1: Correlation\n\n## The question: do two continuous variables move together?\n\n\n::: columns\n::: {.column width=\"50%\"}\n\\\n\nWe've spent the semester asking questions like:\n\n- Does **mean** BP differ between groups?\n- Is **proportion** with hypertension the same across age groups?\n\n\\\n\nNow a new type of question: **As BMI increases, does systolic blood pressure tend to increase too?**\n\n\\\n\nBoth variables are continuous. We need new tools.\n:::\n::: {.column width=\"50%\"}\n\n\\\n\n\\\n\n\\\n\n\\\n\n\\\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](21_slr_files/figure-revealjs/unnamed-chunk-1-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n:::\n:::\n\n\n## Response and explanatory variables\n\n\n::::: columns\n::: {.column width=\"48%\"}\n\n::: {.callout-note icon=\"false\"}\n### Response variable\n\nThe variable that **measures the outcome of interest** — what we are trying to understand or predict.\n\n**Example:** Systolic blood pressure\n:::\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n::: {.callout-note icon=\"false\"}\n### Explanatory variable\n\nThe variable we think may **explain or be associated with** changes in the response.\n\n**Example:** BMI\n:::\n\n:::\n:::::\n\n\n- A study will typically examine whether the values of a **response variable** differ as values of an **explanatory variable** change\n- These roles guide how we set up plots and models\n   - The explanatory variable goes on the $x$-axis, the response on the $y$-axis.\n- Sometimes we’re just interested in viewing the relationship between **explanatory variables**\n- Approaches vary depending on whether the two variables are:\n   - Both numerical\n   - Both categorical\n   - One numerical and one categorical\n   \n\\\n\nWhen both variables are numerical, the **scatterplot** is our primary tool for visualizing the relationship.\n  \n\n## Reading a scatterplot\n\n\\\n\nWhen you look at a scatterplot, ask four questions:\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n**1. Direction**\n\n- Positive: as $X$ increases, $Y$ tends to increase\n- Negative: as $X$ increases, $Y$ tends to decrease\n- None: no clear pattern\n\n**2. Form**\n\n- Linear: points follow a straight line\n- Curved: some other shape\n- No pattern\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n**3. Strength**\n\n- How tightly do the points follow the pattern?\n- Strong, moderate, weak\n\n**4. Unusual observations**\n\n- Outliers that don't fit the trend\n- Clusters or subgroups\n\n:::\n:::::\n\n\\\n\n\n\n<!-- ::: {.callout-tip icon=\"false\"} -->\n<!-- For systolic BP vs. BMI: **positive, roughly linear, moderate strength**. Some variability — not a tight cloud. -->\n<!-- ::: -->\n\n## Scatterplot for systolic BP vs. BMI\n\n::: columns\n::: {.column width=\"40%\"}\n\n1. Direction \n   - Positive\n2. Form\n   - Roughly linear\n3. Strength\n   - Moderate\n   - Not a tight cloud\n4. Unusual observations\n   - Some present\n\n:::\n::: {.column width=\"60%\"}\n\n\\\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](21_slr_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n\n:::\n:::\n\n## The Pearson correlation coefficient\n\n\\\n\nThe **Pearson correlation coefficient** $r$ quantifies the strength and direction of the **linear** association between two continuous variables.\n\n$$r = \\frac{1}{n-1}\\sum_{i=1}^{n}\\left(\\frac{x_i - \\bar{x}}{s_x}\\right)\\left(\\frac{y_i - \\bar{y}}{s_y}\\right)$$\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n\n<!-- **Properties of $r$:** -->\n\n<!-- - Always between −1 and +1 -->\n<!-- - $r = +1$: perfect positive linear relationship -->\n<!-- - $r = -1$: perfect negative linear relationship -->\n<!-- - $r = 0$: no linear relationship -->\n<!-- - Sign = direction; magnitude = strength -->\n\n**With base R:**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(nhanes_bp$BMI, nhanes_bp$BPSys1,\n    use = \"complete.obs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2955122\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n**Using tidyverse:**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnhanes_bp %>%\n  summarise(\n    r = cor(BMI, BPSys1,\n            use = \"complete.obs\")\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n      r\n  <dbl>\n1 0.296\n```\n\n\n:::\n:::\n\n\n\n\n:::\n:::::\n\n## Describing associations between 2 numerical variables\n\n\n\\\n\n- Two variables $X$ and $Y$ are \n\n  - **Positively associated** if $Y$ increases as $X$ increases\n\n  - **Negatively associated** if $Y$ decreases as $X$ increases\n  \n\\\n- If there is no association between the variables, then we say they are **uncorrelated** or **independent**\n\n\\\n\n- The term \"association\" is a very general term\n\n  - Can be used for numerical or categorical variables\n  - Not specifically referring to linear associations\n\n## (Pearson) Correlation coefficient ($r$)\n\n::: columns\n::: {.column width=\"40%\"}\n* $r = -1$ indicates a __perfect negative linear relationship__: As one variable increases, the value of the other variable tends to go down, following a *straight line*\n* $r = 0$ indicates __no linear relationship__: The values of both variables go up/down independently of each other\n* $r = 1$ indicates a __perfect positive linear relationship__: As the value of one variable goes up, the value of the other variable tends to go up as well in a linear fashion\n\n \n\n* The closer $r$ is to ±1, the stronger the linear association\n:::\n\n::: {.column width=\"60%\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](21_slr_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n:::\n:::\n\n## Interpreting the correlation coefficient\n\nMultiple published schemes exist for labeling the strength of $r$ — and they don't agree:\n\n::::: columns\n::: {.column width=\"30%\"}\n\n**Common scheme**\n\n| $|r|$ | Label |\n|---|---|\n| $\\geq 0.6$ | Strong |\n| $0.3 – 0.6$ | Moderate |\n| $< 0.3$ | Weak |\n\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"30%\"}\n\n**Another common scheme**\n\n| $|r|$ | Label |\n|---|---|\n| $> 0.8$ | Strong |\n| $0.5 – 0.8$ | Moderate |\n| $< 0.5$ | Weak |\n\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"30%\"}\n\n**Mukaka (2012)**\n\n| $|r|$ | Label |\n|---|---|\n| $0.9 – 1.0$ | Very high |\n| $0.7 – 0.9$ | High |\n| $0.5 – 0.7$ | Moderate |\n| $0.3 – 0.5$ | Low |\n| $0.0 – 0.3$ | Negligible |\n\n:::\n:::::\n\n::: {.callout-important icon=\"false\"}\n### The disagreement is the lesson\n\nThree published schemes, three different answers for the same $r$. Rather than memorizing cutoffs, ask: does this correlation **accurately and meaningfully represent the relationship** for your research question and field?\n\nIn biomedical research with a single predictor, $r = 0.40$ may be quite meaningful. In a tightly controlled physical measurement, $r = 0.85$ might be disappointing. **Always report the actual value and interpret it in context.**\n:::\n\n[Eight things you need to know about interpreting correlations (from University of Sussex)](https://users.sussex.ac.uk/~grahamh/RM1web/Eight%20things%20you%20need%20to%20know%20about%20interpreting%20correlations.pdf)\n\n<!-- ::: {.callout-warning icon=\"false\"} -->\n<!-- ### Common rough benchmarks (context-dependent!) -->\n<!-- $|r| < 0.3$: weak  &nbsp;&nbsp;&nbsp; $0.3 \\leq |r| < 0.6$: moderate  &nbsp;&nbsp;&nbsp; $|r| \\geq 0.6$: strong -->\n\n<!-- These are rough rules of thumb — what counts as a \"strong\" correlation varies by field. In complex biological systems, $r = 0.4$ may be quite meaningful. -->\n<!-- ::: -->\n\n<!-- ## Interpreting the correlation coefficient -->\n\n<!-- \\ -->\n\n<!-- ::: {.callout-warning icon=\"false\"} -->\n<!-- ### There is no universal benchmark -->\n\n<!-- A correlation coefficient should accurately reflect the strength of the relationship in *your* data. What counts as \"strong\" depends entirely on the subject area. -->\n<!-- ::: -->\n\n<!-- \\ -->\n\n<!-- ::::: columns -->\n<!-- ::: {.column width=\"48%\"} -->\n\n<!-- **One common scheme:** -->\n\n<!-- | Strength | $|r|$ | -->\n<!-- |---|---| -->\n<!-- | Weak | $< 0.5$ | -->\n<!-- | Moderate | $0.5$ to $0.8$ | -->\n<!-- | Strong | $> 0.8$ | -->\n\n<!-- ::: -->\n\n<!-- ::: {.column width=\"4%\"} -->\n<!-- ::: -->\n\n<!-- ::: {.column width=\"48%\"} -->\n\n<!-- **Why context matters:** -->\n\n<!-- - Studies involving **human behavior or biology** often yield $r < 0.6$ — humans are complex and hard to predict -->\n<!-- - Studies of **physical or chemical processes** with precise measurement may yield $r$ near $\\pm 1$ -->\n<!-- - In biomedical research, $r = 0.4$ with a single predictor can be quite meaningful -->\n\n<!-- ::: -->\n<!-- ::::: -->\n\n<!-- \\ -->\n\n<!-- ::: {.callout-tip icon=\"false\"} -->\n<!-- **Bottom line:** Don't chase a benchmark. Ask whether the correlation accurately and meaningfully represents the relationship for your research question. -->\n<!-- ::: -->\n\n## Correlation ≠ causation\n\n\\\n\nA high $r$ tells you two variables are associated. It says **nothing** about whether one causes the other.\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n\n**Classic confounders:**\n\n- Ice cream sales and drowning deaths both increase in summer (confounder: temperature)\n- Shoe size and reading ability in children (confounder: age)\n- Higher hospital admission rates associated with worse outcomes (confounder: severity of illness)\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n**For our example:**\n\nBMI and systolic BP are associated — but the causal pathway is complex:\n\n- BMI → metabolic syndrome → hypertension\n- Shared causes: diet, physical activity, genetics\n- Reverse causation is unlikely here but not impossible\n\n:::\n:::::\n\n\\\n\n::: {.callout-important icon=\"false\"}\nCorrelation is a description of the data. Causation requires study design (randomized experiments) or careful causal reasoning — not a higher $r$.\n:::\n\n## Spearman correlation: the nonparametric alternative\n\n\\\n\n**Recall from Lesson 17:** when data are skewed, contain outliers, or are ordinal, rank-based methods are more robust.\n\n\\\n\nThe **Spearman correlation** $r_s$ is simply the Pearson correlation applied to the **ranks** of $X$ and $Y$:\n\n1. Rank all $X$ values (1 = smallest)\n2. Rank all $Y$ values (1 = smallest)\n3. Compute Pearson $r$ on those ranks\n\n\\\n\n\n**When to use Spearman:**\n\n- Ordinal outcomes (pain scales, severity scores)\n- Skewed continuous variables (viral loads, antibody titers)\n- When outliers would distort Pearson $r$\n\n\n\n## Spearman correlation in R\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n\n**In base R**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(nhanes_bp$BMI, nhanes_bp$BPSys1,\n    method = \"spearman\",\n    use = \"complete.obs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3610264\n```\n\n\n:::\n:::\n\n\n\n\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n**More tidyverse way:**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnhanes_bp %>%\n  summarise(\n    r_pearson = cor(BMI, BPSys1,\n        use = \"complete.obs\"),\n    r_spearman = cor(BMI, BPSys1,\n        method = \"spearman\",\n        use = \"complete.obs\")\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  r_pearson r_spearman\n      <dbl>      <dbl>\n1     0.296      0.361\n```\n\n\n:::\n:::\n\n\n\n\n:::\n:::::\n\n\\\n\n::: {.callout-tip icon=\"false\"}\nPearson and Spearman are similar here — the relationship is reasonably linear without extreme outliers dominating.\n:::\n\n## The limitation of correlation\n\n\\\n\nCorrelation answers: **how strongly are these two variables associated?**\n\n\\\n\nBut researchers often want to know more:\n\n- How much does systolic BP **increase** for each 1-unit increase in BMI?\n- What systolic BP would we **predict** for a patient with BMI = 32?\n- Is the association **statistically significant** — or could it be due to chance?\n\n\\\n\n::: {.callout-note icon=\"false\"}\n### Correlation → Regression\n\nCorrelation gives us a single number summarizing the association. **Regression** gives us a line — a model that lets us quantify, predict, and test.\n\nWe keep the same scatterplot. We add a line.\n:::\n\n# Part 2: The Simple Linear Regression Model\n\n## The regression line\n\n\\\n\nA **regression line** describes how the mean of $Y$ changes as $X$ changes:\n\n$$\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 X$$\n\\\n\nThe **hat** (^) on $\\hat{Y}$ signals this is an **estimated** value from the line — not the actual observed $Y$.\n\n\\\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(nhanes_bp, aes(x = BMI, y = BPSys1)) +\n  geom_point(alpha = 0.3, color = \"#0072B2\", size = 1.5) +\n  geom_smooth(method = \"lm\", se = FALSE,\n              color = \"#D55E00\", linewidth = 1.5) +\n  labs(title = \"Systolic BP vs. BMI with regression line\",\n       x = \"BMI (kg/m²)\", y = \"Systolic BP (mmHg)\")\n```\n\n::: {.cell-output-display}\n![](21_slr_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n\n\n\n\n## Population model vs. estimated line\n\n::::: columns\n::: {.column width=\"48%\"}\n\n::: {.callout-note icon=\"false\"}\n### Population model (unobservable)\n\n$$Y = \\beta_0 + \\beta_1 X + \\epsilon$$\n\n- $\\beta_0$, $\\beta_1$: unknown population parameters we want to estimate\n- $\\epsilon$ (epsilon): random error — how far each individual deviates from the true line\n- Assumption: $\\epsilon \\sim N(0, \\sigma^2)$ — errors are normally distributed with mean 0 and constant variance\n:::\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n::: {.callout-tip icon=\"false\"}\n### Estimated line (from our data)\n\n$$\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 X$$\n\n- $\\hat{\\beta}_0$, $\\hat{\\beta}_1$: our sample estimates of $\\beta_0$, $\\beta_1$\n- No error term — the line gives the **predicted mean** at each $X$\n- Individual observations will scatter above and below this line\n:::\n\n:::\n:::::\n\n| Symbol | Name | Type |\n|---|---|---|\n| $Y$ | Response / outcome | Observed |\n| $X$ | Predictor / covariate | Observed |\n| $\\beta_0$ | Intercept | Population parameter |\n| $\\beta_1$ | Slope | Population parameter |\n| $\\epsilon$ | Error term | Unobservable |\n| $\\hat{\\beta}_0$, $\\hat{\\beta}_1$ | Estimated intercept / slope | Calculated from data |\n\n## Residuals: the building block of regression\n\n\\\n\nFor each observation $i$, the **residual** is the difference between what we observed and what the line predicted:\n\n$$\\hat{\\epsilon}_i = Y_i - \\hat{Y}_i$$\n\n\\\n\n::::: columns\n::: {.column width=\"30%\"}\n\n\\\n\n- Points **above** the line: \n   - positive residual ($Y_i > \\hat{Y}_i$)\n- Points **below** the line: \n   - negative residual ($Y_i < \\hat{Y}_i$)\n- Points **on** the line: \n   - residual = 0 (rare in practice)\n\n:::\n\n\n::: {.column width=\"70%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](21_slr_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=864}\n:::\n:::\n\n\n\n\n:::\n:::::\n\n## Ordinary Least Squares (OLS)\n\n\\\n\n**Key question:** With infinitely many possible lines we could draw through the data, which one is *best*?\n\n\\\n\n**OLS answer:** Choose the line that minimizes the **Sum of Squared Errors (SSE)**:\n\n$$SSE = \\sum_{i=1}^{n} \\hat{\\epsilon}_i^2 = \\sum_{i=1}^{n}(Y_i - \\hat{Y}_i)^2$$\n\n\\\n\n::::: columns\n::: {.column width=\"55%\"}\n\n**Why square the residuals?**\n\n- Positive and negative residuals would cancel\n- Squaring penalizes large errors more than small ones\n- Makes the math tractable (calculus gives closed-form solutions)\n\nThe OLS estimates $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$ are the values that make SSE as small as possible. R's `lm()` finds these automatically.\n\n- [Math details if interested](https://www.stat.cmu.edu/~hseltman/309/Book/chapter9.pdf)\n\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.callout-tip icon=\"false\"}\n### The OLS formulas\n\n$$\\hat{\\beta}_1 = r \\cdot \\frac{s_Y}{s_X}$$\n\n$$\\hat{\\beta}_0 = \\bar{Y} - \\hat{\\beta}_1 \\bar{X}$$\n\nNotice: $\\hat{\\beta}_1$ depends directly on the Pearson correlation $r$ — regression and correlation are deeply connected.\n:::\n\n:::\n:::::\n\n## Running SLR in R: `lm()` + `tidy()`\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the model\nmodel_bp <- lm(BPSys1 ~ BMI, data = nhanes_bp)\n\nlibrary(broom)\n# Tidy output: coefficients, SE, t, p, CI\ntidy(model_bp, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term        estimate std.error statistic  p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)   98.8       5.05      19.6  2.88e-44   88.8      109.  \n2 BMI            0.698     0.178      3.91 1.35e- 4    0.345      1.05\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\nOur estimated regression equation:\n\n$$\\widehat{\\text{Systolic BP}} = 98.83 + 0.70 \\times \\text{BMI}$$\n\n## Interpreting the slope and intercept\n\n\\\n\n$$\\widehat{\\text{Systolic BP}} = 98.83 + 0.70 \\times \\text{BMI}$$\n\n\n::::: columns\n::: {.column width=\"48%\"}\n\n::: {.callout-note icon=\"false\"}\n### Slope ($\\hat{\\beta}_1$ = 0.70)\n\nFor every **1 kg/m² increase in BMI**, systolic blood pressure is expected to increase by **0.70 mmHg**, on average, holding all else constant.\n\n- Sign tells you the **direction** of the association\n- Magnitude tells you the **rate of change** in the units of $Y$ per unit of $X$\n:::\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n::: {.callout-note icon=\"false\"}\n### Intercept ($\\hat{\\beta}_0$ = 98.83)\n\nThe expected systolic BP for someone with a BMI of 0 is 98.83 mmHg.\n\n**⚠️ The intercept is often not directly interpretable.** A BMI of 0 is physiologically impossible. The intercept is a mathematical anchor for the line — interpret it only when $X = 0$ is meaningful in context.\n:::\n\n:::\n:::::\n\n::: {.callout-important icon=\"false\"}\nRegression describes **association**, not causation. \"Expected to increase by 0.70 mmHg\" does not mean BMI *causes* higher blood pressure — it means these two variables are associated in a positive linear way.\n:::\n\n# Part 3: Model Evaluation\n\n## The LINE conditions\n\n\\\n\nFor the regression model to give valid estimates and reliable inference, four conditions must hold. We remember them as **LINE**:\n\n\\\n\n| Letter | Condition | How to check |\n|:---:|---|---|\n| **L** | **L**inearity — the relationship between $X$ and $Y$ is linear | Scatterplot; residual plot |\n| **I** | **I**ndependence — observations are independent of each other | Study design |\n| **N** | **N**ormality — residuals are approximately normally distributed | QQ plot of residuals |\n| **E** | **E**qual variance — residuals have constant variance across all $X$ values | Residual plot |\n\n: {tbl-colwidths=\"\\[7, 50, 25\\]\"}\n\n\\\n\n::: {.callout-tip icon=\"false\"}\nThe two key diagnostic plots are the **residual plot** (residuals vs. fitted values) and the **QQ plot of residuals**. We generate both from the fitted model object using `augment()` from `broom`.\n:::\n\n## Diagnostic plots in R\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\naug <- augment(model_bp)\n\np1 <- ggplot(aug, aes(x = .fitted, y = .resid)) +\n  geom_point(alpha = 0.4, color = \"#0072B2\", size = 1.5) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  geom_smooth(se = FALSE, color = \"#D55E00\", linewidth = 1) +\n  labs(title = \"Residual plot\",\n       subtitle = \"Checks L and E\",\n       x = \"Fitted values (ŷ)\",\n       y = \"Residuals\")\n\np2 <- ggplot(aug, aes(sample = .resid)) +\n  stat_qq(alpha = 0.4, color = \"#0072B2\", size = 1.5) +\n  stat_qq_line(color = \"#D55E00\", linewidth = 1) +\n  labs(title = \"Normal QQ plot of residuals\",\n       subtitle = \"Checks N\",\n       x = \"Theoretical quantiles\",\n       y = \"Sample quantiles\")\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](21_slr_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n\n## Reading the diagnostic plots\n\n::::: columns\n::: {.column width=\"48%\"}\n\n::: {.callout-note icon=\"false\"}\n### Residual plot (checks L and E)\n\n**What you want to see:**\n\n- Points scattered randomly around the horizontal line at 0\n- No systematic curve or funnel shape\n- Roughly equal spread across all fitted values\n\n**Red flags:**\n\n- **Curve:** linearity (L) is violated — consider a transformation\n- **Funnel (spread increases):** equal variance (E) is violated — heteroscedasticity\n:::\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n::: {.callout-note icon=\"false\"}\n### QQ plot (checks N)\n\n**What you want to see:**\n\n- Points fall approximately along the diagonal reference line\n\n**Red flags:**\n\n- S-shaped pattern: skewed residuals\n- Heavy tails: points deviate at both ends\n\n**Note:** With large samples, moderate departures from normality matter less (CLT). Linearity and equal variance are more critical for inference.\n:::\n\n:::\n:::::\n\n## What good diagnostic plots look like\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](21_slr_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n\n::: {.callout-tip icon=\"false\"}\n**Residual plot:** The smoother is flat and close to zero — no curve, no funnel. **QQ plot:** Points track the diagonal closely; minor deviation at the very ends is normal and acceptable.\n:::\n\n## Reading our NHANES diagnostic plots (1/2)\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](21_slr_files/figure-revealjs/unnamed-chunk-13-1.png){width=768}\n:::\n:::\n\n\n\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n::: {.callout-warning icon=\"false\"}\n### Residual plot\n\n- The smoother curves downward at high fitted values — a mild non-linearity signal (**L** is questionable)\n- Spread is roughly constant across most of the range — **E** approximately satisfied\n- One point has a residual near +80: a person whose systolic BP is ~80 mmHg higher than their BMI predicts — worth noting but not removing\n\n:::\n\n:::\n:::::\n\n## Reading our NHANES diagnostic plots (2/2)\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](21_slr_files/figure-revealjs/unnamed-chunk-14-1.png){width=768}\n:::\n:::\n\n\n\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n::: {.callout-warning icon=\"false\"}\n### QQ plot\n\n- Points track the diagonal closely through the bulk of the data — **N** approximately satisfied\n- The upper tail deviates: a few large positive residuals pull away from the line\n- The same outlier visible in the residual plot is driving this deviation\n- With $n$ = 162, moderate tail departures matter less (CLT)\n\n:::\n\n:::\n:::::\n\n\n## Overall assessment\n\n\\\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](21_slr_files/figure-revealjs/unnamed-chunk-15-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n::: {.callout-important icon=\"false\"}\n### Overall assessment\n\nLINE conditions are approximately met. The linear model is a reasonable approximation for this data, and inference on the slope is valid. The curved smoother is a reminder that BMI alone explains only a modest portion of BP variability — other factors are clearly at work.\n:::\n\n## Going further\n\n\\\n\n::: {.callout-note icon=\"false\"}\n### More diagnostic plots\n\nThere are two additional diagnostic plots — the **scale-location plot** (a cleaner check of equal variance) and the **residuals vs. leverage plot** (identifies influential observations). You can produce all four at once with `autoplot(model)` from the `ggfortify` package. \n:::\n\n\\\n\nFurther reading: \n\n- [Understanding Diagnostic Plots for Linear Regression Analysis](https://library.virginia.edu/data/articles/diagnostic-plots)\n- [Diagnostic Plots for Model Evaluation](https://www.geeksforgeeks.org/r-machine-learning/diagnostic-plots-for-model-evaluation/)\n- [Demystifying Simple Linear Regression Diagnostics in R](https://medium.com/@dorothyavo/demystifying-simple-linear-regression-diagnostics-in-r-720dd140f012) \n\n\n## The $R^2$ statistic\n\n**$R^2$** (the coefficient of determination) tells us: \n\n- **what proportion of the variability in $Y$ is explained by the linear relationship with $X$?**\n\n$$R^2 = 1 - \\frac{SSE}{SST} = 1 - \\frac{\\sum(Y_i - \\hat{Y}_i)^2}{\\sum(Y_i - \\bar{Y})^2}$$\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n\n- $R^2 = 0$: the model explains none of the variability in $Y$ — no better than predicting $\\bar{Y}$ for everyone\n- $R^2 = 1$: the model explains all of the variability — all points fall exactly on the line\n- For simple linear regression: $R^2 = r^2$ (square of the Pearson correlation)\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# glance() gives model-level summaries\nglance(model_bp) %>%\n  select(r.squared, sigma, nobs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  r.squared sigma  nobs\n      <dbl> <dbl> <int>\n1    0.0873  17.5   162\n```\n\n\n:::\n:::\n\n\n\n\n::: {.callout-tip icon=\"false\"}\n`sigma` = residual standard error = the typical size of a residual. Think of it as the average prediction error in units of $Y$.\n:::\n\n:::\n:::::\n\n## Interpreting $R^2$ in context\n\n\\\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nFor our model: $R^2$ = 8.7%\n\n\\\n\n::: {.callout-important icon=\"false\"}\n### Interpretation\n\nBMI explains approximately 8.7% of the variability in systolic blood pressure in this NHANES sample. The remaining 91.3% of variability is due to other factors not included in the model — age, sex, medications, genetics, sodium intake, stress, and so on.\n\nAn $R^2$ of 8.7% sounds modest, but in a complex biological system with a single predictor, this is a meaningful association. **Context matters.**\n:::\n\n\\\n\n::: {.callout-warning icon=\"false\"}\nA high $R^2$ does not validate the model. It is possible to have a high $R^2$ with a curved relationship that a linear model fits poorly. **Always check the LINE conditions first.**\n:::\n\n# Part 4: Inference and Prediction\n\n## What are we testing?\n\n\\\n\nWe have an estimated slope $\\hat{\\beta}_1$. But is the true population slope $\\beta_1$ actually different from zero?\n\n\\\n\n$$H_0: \\beta_1 = 0 \\qquad \\text{vs.} \\qquad H_A: \\beta_1 \\neq 0$$\n\n\\\n\n::: {.callout-note icon=\"false\"}\n### Why $\\beta_1 = 0$ matters\n\nIf $\\beta_1 = 0$, the regression line is flat — $X$ tells us nothing about $Y$. Testing $H_0: \\beta_1 = 0$ is equivalent to testing whether there is **any linear association** between the two variables.\n:::\n\n\\\n\nThe test statistic is a $t$-statistic:\n\n$$t = \\frac{\\hat{\\beta}_1 - 0}{SE_{\\hat{\\beta}_1}} = \\frac{\\hat{\\beta}_1}{SE_{\\hat{\\beta}_1}}$$\n\nwhich follows a $t$-distribution with $df = n - 2$ under $H_0$.\n\n## Inference for slope $\\beta_1$: all 6 steps\n\n**Step 1: Hypotheses**\n\n$$H_0: \\beta_1 = 0 \\quad \\text{(no linear association between BMI and systolic BP)}$$\n$$H_A: \\beta_1 \\neq 0 \\quad \\text{(a linear association exists)}$$\n\n\\\n\n**Step 2: Significance level** &nbsp; $\\alpha = 0.05$\n\n**Step 3: Check assumptions** &nbsp; LINE conditions — checked via diagnostic plots on previous slides ✓\n\n\\\n\n**Step 4: Test statistic**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb1_row <- model_bp %>% \n  broom::tidy() %>% \n  dplyr::filter(term == \"BMI\")\n\nt_stat <- b1_row %>% dplyr::pull(statistic)\nt_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.912713\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n\n$$t = \\frac{\\hat{\\beta}_1}{SE_{\\hat{\\beta}_1}} = \\frac{0.698}{0.178} = 3.91$$\n\n## Inference for slope $\\beta_1$ (continued)\n\n\\\n\n**Step 5: p-value**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_val <- b1_row %>% dplyr::pull(p.value)\np_val\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0001346729\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\nOr directly from the regression table:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_bp %>% \n  broom::tidy(conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term        estimate std.error statistic  p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)   98.8       5.05      19.6  2.88e-44   88.8      109.  \n2 BMI            0.698     0.178      3.91 1.35e- 4    0.345      1.05\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n**Step 6: Conclusion**\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\nWe reject $H_0$ at the $\\alpha = 0.05$ level (t = 3.91, df = 160, *p* < 0.001). There is strong evidence of a positive linear association between BMI and systolic blood pressure.\n\n## Confidence interval for $\\beta_1$\n\n\\\n\nThe 95% confidence interval for the population slope uses the same logic as all our previous CIs:\n\n$$\\text{point estimate} \\pm z^*(or~t^*)\\cdot SE$$\n\\\n\nSo for the confidence interval for the coefficient $\\hat{\\beta}_1$ this translates to \n\n$$\\hat{\\beta}_1 \\pm t^*_{n-2} \\cdot SE_{\\hat{\\beta}_1}$$\n\nwhere $t^*_{n-2}$ is the critical value from the $t$-distribution with $n - 2$ degrees of freedom.\n\n\\\n\n## Confidence interval for $\\beta_1$ (continued)\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_bp %>% \n  tidy(conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term        estimate std.error statistic  p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)   98.8       5.05      19.6  2.88e-44   88.8      109.  \n2 BMI            0.698     0.178      3.91 1.35e- 4    0.345      1.05\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n::: {.callout-important icon=\"false\"}\n### Interpretation\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nFor every 1 kg/m² increase in BMI, systolic blood pressure is expected to increase by 0.70 mmHg, on average (95% CI: 0.35 to 1.05 mmHg). Because the CI does not include 0, this is consistent with our hypothesis test conclusion: there is evidence of a positive linear association.\n:::\n\n::: {.callout-note icon=\"false\"}\n### General statement for population slope inference\n\nFor every 1 unit increase in the $X$-variable, the is an expected/average increase of $\\hat{\\beta}_1$ units in the $Y$-variable (95% CI: LB, UB).\n\n:::\n\n## Prediction: using the model for new observations\n\n\\\n\nOnce we have a regression line, we can plug in any $X$ value to get a predicted $\\hat{Y}$:\n\n$$\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 \\cdot X^*$$\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_data <- data.frame(BMI = c(25, 30, 35))\n\npredict(model_bp, newdata = new_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1        2        3 \n116.2686 119.7562 123.2438 \n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n::: {.callout-note icon=\"false\"}\n### Interpretation\n\nFor a person with BMI = 30, the model predicts a systolic BP of approximately 119.8 mmHg — the **average** expected BP for all people at that BMI.\n:::\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n::: {.callout-warning icon=\"false\"}\n### Extrapolation\n\nOnly predict within the range of your data. The model was fit on BMI values from roughly 14 to 69 kg/m² — predictions far outside this range are unreliable.\n:::\n:::\n:::::\n\n<!-- ## Three intervals in regression -->\n\n<!-- \\ -->\n\n<!-- | | What it estimates | Width | -->\n<!-- |---|---|---| -->\n<!-- | **CI for $\\hat{\\beta}_1$** | How precisely did we estimate the *slope*? | Constant — one number | -->\n<!-- | **CI for mean response** | What is the average $Y$ for *all people* at a given $X^*$? | Varies — narrowest at $\\bar{X}$ | -->\n<!-- | **Prediction interval** | What $Y$ would *this specific new person* at $X^*$ have? | Varies — always wider than CI for mean | -->\n\n<!-- : {tbl-colwidths=\"\\[20, 30, 30\\]\"} -->\n\n<!-- \\ -->\n\n<!-- ::: {.callout-tip icon=\"false\"} -->\n<!-- ### Why does width vary for the bottom two? -->\n\n<!-- The predicted mean at any $X^*$ depends on both $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$.  -->\n<!-- Think of the line as a rod balanced at $(\\bar{X}, \\bar{Y})$ — uncertainty in the  -->\n<!-- slope means the rod can rotate slightly around that pivot. Near the center, a small  -->\n<!-- rotation barely moves the prediction. Near the extremes, the same rotation moves  -->\n<!-- it a lot. -->\n\n<!-- The prediction interval is wider still because even if we knew the line perfectly,  -->\n<!-- individual patients vary around it. -->\n\n<!-- **Short version:** The CI for mean response asks about the *line*. The prediction  -->\n<!-- interval asks about a *person*. The CI for $\\hat{\\beta}_1$ asks about a *parameter*. -->\n<!-- ::: -->\n\n## Two kinds of prediction uncertainty\n\n\\\n\nA point prediction is a single number — but how uncertain is it? There are two distinct questions:\n\n\\\n\n| | Question | Accounts for |\n|---|---|---|\n| **CI for mean response** | What is the *average* BP for **all people** with BMI = 30? | Uncertainty about where the line is |\n| **Prediction interval** | What BP would *this specific new patient* with BMI = 30 have? | Uncertainty about the line **+** individual variation around it |\n\n: {tbl-colwidths=\"\\[20, 30, 30\\]\"}\n\n\\\n\nPrediction intervals are always **wider** than confidence intervals for the mean — even if we knew the line perfectly, individuals still vary around it.\n\n\\\n\n::: {.callout-tip icon=\"false\"}\n- The CI for mean response asks about the **line**. \n- The prediction interval asks about a **person**.\n- The CI for $\\hat{\\beta}_1$ asks about a *parameter*.\n:::\n\n## For BMI = 30\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(model_bp, \n        newdata = tibble(BMI = 30), \n        interval = \"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 119.7562 116.8847 122.6277\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n::: {.callout-important icon=\"false\"}\n### CI for mean response\n\nWe are 95% confident that the **average** BP for all people with BMI = 30 is between **117 and 123 mmHg**.\n:::\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(model_bp, \n        newdata = tibble(BMI = 30), \n        interval = \"prediction\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 119.7562 85.16867 154.3437\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n::: {.callout-important icon=\"false\"}\n### Prediction interval\n\nWe are 95% confident that a **specific future individual** with BMI = 30 will have BP between **85 and 154 mmHg**.\n:::\n\n\\\n\nNotice how much wider the prediction interval is — it must account for individual variation, not just uncertainty about the line.\n\n## Visualizing both intervals\n\n::: {style=\"font-size: 0.55em;\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Generate CI and prediction interval bands across BMI range\nbmi_grid <- data.frame(BMI = seq(min(nhanes_bp$BMI), \n                                 max(nhanes_bp$BMI), \n                                 length.out = 200))\n\nci_band   <- predict(model_bp, newdata = bmi_grid, \n                     interval = \"confidence\") %>% \n  as_tibble() %>% \n  bind_cols(bmi_grid)\n\npred_band <- predict(model_bp, newdata = bmi_grid, \n                     interval = \"prediction\") %>% \n  as_tibble() %>% \n  bind_cols(bmi_grid)\n\nggplot(nhanes_bp, aes(x = BMI, y = BPSys1)) +\n  geom_point(alpha = 0.3, color = \"#0072B2\", size = 1.5) +\n  geom_ribbon(data = pred_band, \n              aes(y = fit, ymin = lwr, ymax = upr),\n              fill = \"#E69F00\", alpha = 0.2) +\n  geom_ribbon(data = ci_band,  \n              aes(y = fit, ymin = lwr, ymax = upr),\n              fill = \"#009E73\", alpha = 0.4) +\n  geom_line(data = ci_band, aes(y = fit), \n            color = \"#D55E00\", linewidth = 1) +\n  labs(title = \"CI for mean response (green) vs. prediction interval (yellow)\",\n       x = \"BMI (kg/m²)\", y = \"Systolic BP (mmHg)\")\n```\n\n::: {.cell-output-display}\n![](21_slr_files/figure-revealjs/unnamed-chunk-30-1.png){fig-align='center' width=864}\n:::\n:::\n\n\n\n:::\n\n::: {.callout-note icon=\"false\"}\nThe **green band** is the 95% CI for the mean response — narrow near the center of the data, wider at the extremes. The **yellow band** is the 95% prediction interval — much wider, because it must capture individual patients, not just the average.\n:::\n\n\n\n\n# Wrap-Up\n\n## The full SLR workflow\n\n\\\n\n::::: columns\n::: {.column width=\"45%\"}\n\n**1. Visualize**\n\n```r\nggplot(data, aes(x = X, y = Y)) +\n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n**2. Fit**\n\n```r\nmodel <- lm(Y ~ X, data = data)\n```\n\n**3. Coefficients + inference**\n\n```r\ntidy(model, conf.int = TRUE)\n```\n\n**4. Model fit**\n\n```r\nglance(model)   # R², sigma\n```\n\n:::\n\n::: {.column width=\"3%\"}\n:::\n\n::: {.column width=\"52%\"}\n\n**5. Diagnostics**\n\n```r\naug <- augment(model)\n\n# Residual plot\nggplot(aug, aes(x = .fitted, y = .resid)) +\n  geom_point() +\n  geom_hline(yintercept = 0)\n\n# QQ plot\nggplot(aug, aes(sample = .resid)) +\n  stat_qq() + stat_qq_line()\n```\n\n**6. Predict**\n\n```r\npredict(model,\n  newdata = new_data)\n```\n\n:::\n:::::\n\n## Where this fits in the bigger picture\n\n\\\n\n::::: columns\n::: {.column width=\"55%\"}\n\n**What we've learned this semester:**\n\n- Describing data (distributions, summaries, visualization)\n- Inference for one group (means, proportions)\n- Inference for two groups (t-tests, difference in proportions)\n- Inference for 3+ groups (ANOVA, Kruskal-Wallis)\n- Inference for categorical associations (chi-square, Fisher's)\n- Inference for linear associations **(today)**\n\n**Where this leads:**\n\n- Multiple regression (add more predictors)\n- Logistic regression (binary outcome)\n- Survival analysis, mixed models, causal inference\n\n\n\n:::\n\n::: {.column width=\"2%\"}\n:::\n\n::: {.column width=\"43%\"}\n\n::: {.callout-tip icon=\"false\"}\n### The unifying thread\n\nEvery method we've learned is asking the same fundamental question:\n\n**What does the data tell us about the population, and how confident are we?**\n\nThe tools change. The logic — estimate, quantify uncertainty, test — stays the same.\n:::\n\n:::\n:::::\n\n\\\n\n**Next: Lesson 19 — Course Review and Final Exam Preparation**\n",
    "supporting": [
      "21_slr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}