{
  "hash": "f05173e84e6ce1c9701aec895751c038",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Introduction to Data & Numerical Summaries (continued)\"\nauthor: \"Emile Latour, Nicky Wakim, Meike Niederhausen\"\ndate: \"2026-01-05\"\ndate-format: long\nformat:\n  revealjs:\n    theme: \"../../assets/css/reveal-bmsc620_v4.scss\"\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"BMSC 620 | Intro to Data & Numerical Summaries (continued)\"\n    html-math-method: mathjax\n    header-includes: |\n      <style>\n      #wrap {\n        width: 1650px;\n        height: 900px;\n        margin: 0 auto;\n        overflow: hidden;\n        border: 1px solid #999;\n        border-radius: 8px;\n      }\n      #frame {\n        width: 1650px;\n        height: 900px;\n        border: 0;\n        zoom: 1.25;\n        -moz-transform: scale(1.25);\n        -moz-transform-origin: 0 0;\n      }\n      </style>\nexecute:\n  echo: true\n  freeze: auto\n---\n\n\n\n\n\n## Learning objectives (today)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# TODO -- update learning objectives\n```\n:::\n\n\n\nBy the end of class, you should be able to:\n\n1.\tIdentify observations and variables in a dataset\n2.\tDistinguish numerical and categorical variables (discrete/continuous; nominal/ordinal)\n3.\tDescribe the center of numerical data using the mean and median\n4.\tDescribe the spread of numerical data using the SD and IQR\n5.\tExplain why skewness and outliers affect some summaries more than others\n\n## Intro to Data (1.2)\n\n![[Artwork by @allison_horst](https://allisonhorst.com/r-packages-functions)](/img_slides/horst_data_cowboy.png){fig-align=\"center\"}\n\n## A motivating example: frog reproduction data[^1]\n\n[^1]: Dataset adapted from an example in *Introductory Statistics for the Life and Biomedical Sciences*.\n\nTo make ideas about data more concrete, we will work with a dataset\nfrom an evolutionary biology study on frog reproduction.\n\nFemale frogs invest energy into reproduction by producing eggs.\nBecause energy is limited, there are natural trade-offs:\n- producing **many small eggs** versus\n- producing **fewer larger eggs**\n\nResearchers collected data from frog egg clutches found at breeding ponds\nacross multiple locations that differed in altitude.\n\nThe goal was to understand how reproductive investment varies across\nenvironments.\n\n## The frog study data (1/2)\n\n\n\n\n| row|altitude | egg.size| clutch.size| clutch.volume| body.size|\n|---:|:--------|--------:|-----------:|-------------:|---------:|\n|   1|3,462.00 |     1.95|      181.97|        177.83|      3.63|\n|   2|3,462.00 |     1.95|      269.15|        257.04|      3.63|\n|   3|3,462.00 |     1.95|      158.49|        151.36|      3.72|\n| 150|2,597.00 |     2.24|      537.03|        776.25|        NA|\n\n\n\n## The frog study data (2/2)\n\n\n\n\n| row|altitude | egg.size| clutch.size| clutch.volume| body.size|\n|---:|:--------|--------:|-----------:|-------------:|---------:|\n|   1|3,462.00 |     1.95|      181.97|        177.83|      3.63|\n|   2|3,462.00 |     1.95|      269.15|        257.04|      3.63|\n|   3|3,462.00 |     1.95|      158.49|        151.36|      3.72|\n| 150|2,597.00 |     2.24|      537.03|        776.25|        NA|\n\n\n\n\\\n\n- Each **observation** is a **row**.\n- Each **variable** is a **column**.\n- Each **cell** contains a **single value**.\n- All the **observations** and **variables** together make a **data frame**. The textbook will sometimes call it a data matrix.\n\n\\ \n\n- **Missing values**: `NA` here means \"missing\". The clutch #150 is missing `body.size`.\n\n## The frog study variables and descriptions\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|variable      |description                                         |\n|:-------------|:---------------------------------------------------|\n|altitude      |Altitude of the study site (meters above sea level) |\n|latitude      |Latitude of the study site (degrees)                |\n|egg.size      |Average diameter of an individual egg (mm)          |\n|clutch.size   |Estimated number of eggs in a clutch                |\n|clutch.volume |Total volume of the egg clutch (mm^3)               |\n|body.size     |Body length of the egg-laying female frog (cm)      |\n\n\n:::\n:::\n\n\n\n\n## Types of variables\n\n![[ISLBS](https://www.openintro.org/book/biostat/)](/img_slides/Fig1.8_variable_types.png){fig-align=\"center\"}\n\n## Numerical variables\n\n**Numerical variables** take on values for which mathematical operations\n(addition, subtraction, averaging) are meaningful.\n\n\\\n\nThere are two common types:\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n### Discrete\n- Take on **separate, countable values**\n- Usually whole numbers\n- Arise from counting\n\n**Examples:**\n\n- Number of eggs in a clutch\n- Number of clinic visits\n- Number of children in a family\n:::\n\n::: {.column width=\"60%\"}\n### Continuous\n- Can take on **any value within a range**\n- Often measured rather than counted\n- Decimals are possible\n\n**Examples:**\n\n- Egg size (mm)\n- Height or weight\n- Blood pressure\n:::\n\n::::\n\n## Categorical variables\n\n**Categorical variables** describe qualities or group membership rather than\nnumerical magnitude. The values are called **levels**.\n\n\\\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n### Nominal\n- Categories have **no natural ordering**\n- Differences are labels, not amounts\n\n**Examples:**\n\n- Species\n- Blood type\n- Gender identity\n:::\n\n::: {.column width=\"60%\"}\n### Ordinal\n- Categories have a **meaningful order**\n- The spacing between categories is not necessarily equal\n\n**Examples:**\n\n- Disease severity (mild, moderate, severe)\n- Likert-scale responses (strongly disagree -> strongly agree)\n- Education level\n:::\n\n::::\n\n\n## How are data stored, how do we use them? \n\n- Often, data are in an Excel sheet, or a plain text file (.csv, .txt)\n- .csv files open in Excel automatically, but actually are plain text\n- Usually, columns are variables/measures and rows are observations (i.e. a person's measurements)\n\n### Data in R \n\n* We can import data from many file types, including .csv, .txt., and .xlsx\n    * We will cover this on a later date\n* Once imported, R typically stores data as __data frames__, or __tibbles__ if using the `tidyverse` package (more on this later).\n    * For our purposes, these are essentially the same, and I will tend to use the terms interchangeably.\n    * These are examples of what we call __object types__ in R.\n\n## Which type is each frog variable?\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|variable      |description                                         |type                   |\n|:-------------|:---------------------------------------------------|:----------------------|\n|altitude      |Altitude of the study site (meters above sea level) |Numerical (continuous) |\n|latitude      |Latitude of the study site (degrees)                |Numerical (continuous) |\n|egg.size      |Average diameter of an individual egg (mm)          |Numerical (continuous) |\n|clutch.size   |Estimated number of eggs in a clutch                |Numerical (discrete)   |\n|clutch.volume |Total volume of the egg clutch (mm^3)               |Numerical (continuous) |\n|body.size     |Body length of the egg-laying female frog (cm)      |Numerical (continuous) |\n\n\n:::\n:::\n\n\n\n\n## How variable types appear in R (preview)\n\nWe are **not using R in depth yet**.\n\nThis slide is here to help you later connect:\n- the variable types we talk about conceptually, and\n- how R stores those variables internally.\n\nYou do **not** need to memorize this now.\n\nR type | Variable type | What it represents\n---|---|---\ninteger | Numerical (discrete) | Whole-number counts\ndouble / numeric | Numerical (continuous) | Measured values with decimals\nfactor | Categorical | Categories stored with defined levels\ncharacter | Categorical | Text labels\nlogical | Categorical | TRUE / FALSE values\n\n## Summarizing numerical data (1.4)\n\nOnce data have been collected, a first step is to **describe what we see**.\n\n\\\n\nFor **numerical variables**, we often want to understand:\n\n- what values are *typical*, and\n- how much the values *vary* across observations.\n\n\\\n\nNumerical summaries help us:\n\n- quickly describe large datasets,\n- compare groups,\n- and communicate patterns clearly.\n\nIn this section, we focus on summaries for **numerical variables**.\nWe will return to categorical variables later.\n\n## Two questions we often ask\n\nFor a numerical variable, two questions come up repeatedly:\n\n1. **Where are the values centered?**\n   - What is a “typical” value?\n\n2. **How spread out are the values?**\n   - Are observations tightly clustered or widely dispersed?\n\nThe summaries we introduce next are designed to answer these two questions.\n\n::: {.callout-note icon=false}\nSome examples will show R output as a reference.\nYou do not need to understand the R code yet — focus on the ideas.\n:::\n\n## Measures of center: the mean\n\nThe **mean** (or average) describes the *center* of a numerical variable.\n\nIt is calculated by:\n\n- adding all observed values, and\n- dividing by the number of observations.\n\n$$\n\\bar{x} = \\frac{x_1 + x_2 + \\cdots + x_n}{n} = \\sum_{i=1}^{n} \\frac{x_i}{n}\n$$\n\nwhere:\n\n- $x_1, x_2, \\ldots, x_n$ are the observed values, and\n- $n$ is the number of observations.\n\nThe mean uses **all** observed values and is sensitive to unusually large or small values. All data values contribute equally, even \"outliers.\"\n\n## Example: mean clutch volume\n\nUsing the frog data, we can ask:\n\n**What is a typical clutch volume?**\n\n\\\n\nFor this dataset:\n\n- each observation is one egg clutch\n- clutch volume is measured in mm$^3$\n\n$$\n\\bar{x} = \\frac{177.8 + 257.0 + \\cdots + 933.3}{431} = \\frac{380346.3}{431} \\approx 882.5\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(frog$clutch.volume, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 882.474\n```\n\n\n:::\n:::\n\n\n\nThe mean clutch volume is 882.5 mm$^3$.\n\n\\\n\n> The mean tells us where the data balance, but it doesn’t tell us how spread out they are.\n\n## Things to note\n\n\\\n\n- The mean of a binary variable with 0/1 coding gives the proportion (relative frequency) of ones in the sample.\n- The mean can be heavily influenced by \"outliers.\"\n  - ${2, 7, 9} \\rightarrow \\bar{x} = \\frac{2 + 7 + 9}{3} = 6$\n\n  - ${2, 7, 29} \\rightarrow \\bar{x} = \\frac{2 + 7 + 29}{3} \\approx 12.7$\n  \n## Distributions of frog variables\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_intro_to_data_cont_files/figure-revealjs/unnamed-chunk-7-1.png){width=1344}\n:::\n:::\n\n\n\n## Measures of center: the median\n\nThe **median** describes the *center* of a numerical variable\nbased on **order**, not magnitude.\n\n- The median is the **middle value** once observations are ordered\n  from smallest to largest.\n- Half of the observations lie **below** the median\n- Half of the observations lie **above** the median\n\nIf there are:\n\n- an **odd** number of observations, the median is the middle value\n- an **even** number of observations, the median is the average of the two middle values\n\nUnlike the mean, the median is **not affected** by extreme values.\n\n## Example: mean vs. median\n\nConsider these two datasets:\n\n- $2, 7, 9$ \n  - Mean = 6  \n  - Median = 7\n\n- $2, 7, 29$\n  - Mean = 12.7  \n  - Median = 7\n\nOnly one value changed, but the **mean** changed a lot.\nThe **median** did not.\n\n## Distributions of frog variables\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_intro_to_data_cont_files/figure-revealjs/unnamed-chunk-8-1.png){width=1344}\n:::\n:::\n\n\n\n- When distributions are skewed, the **mean** is pulled toward the tail.\n- The **median** stays closer to where most observations lie.\n\n\n## A note on the mode\n\nThe **mode** is the most frequent value in a dataset.\n\n- For **numerical** data, the mode is often unstable or uninformative\n- It depends on how values are measured or grouped\n- As a result, it is rarely reported for continuous variables\n\nThe mode is more useful for **categorical** data, which we will revisit later.\n\n\n## Measures of spread: standard deviation (SD) (1/3)\n\n__standard deviation__ is (approximately) the average distance between an observation and the mean \n\n- An observation's **deviation** is the distance between its value $x$ and the sample mean $\\bar{x}$: deviation = $x - \\bar{x}$.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_intro_to_data_cont_files/figure-revealjs/unnamed-chunk-9-1.png){width=1344}\n:::\n:::\n\n\n\n\n\n## Measures of spread: SD  (2/3)\n\n-   The **sample variance** $s^2$ is the sum of squared deviations divided by the number of observations minus 1. \n\n$$\ns^2 =\n\\frac{(x_1 - \\bar{x})^2 + (x_2 - \\bar{x})^2 + \\cdots + (x_n - \\bar{x})^2}{n - 1}\n=\n\\sum_{i=1}^{n} \\frac{(x_i - \\bar{x})^2}{n - 1}\n$$\nwhere $x_1, x_2, \\dots, x_n$ represent the $n$ observed values.\n\n \n\n-   The **standard deviation** $s$ (or $sd$) is the square root of the variance. \n\n$$\ns \n= \\sqrt{s^2}\n= \\sqrt{\\frac{1}{n - 1}\\sum_{i=1}^{n}(x_i - \\bar{x})^2}\n$$\n\n## Measures of spread: SD  (3/3) \n\n\nLet's calculate the sample standard deviation for the `clutch.volume` from the frog dataset. \n\n- Doing this by hand can be really time consuming!\n- `R` does this easily for us.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(frog$clutch.volume, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 379.0527\n```\n\n\n:::\n:::\n\n\n\nSo the standard deviation is 379.1 mm$^3$.\n\n\\\n\nFor the sample of 431 frog clutches, the mean clutch volume was 882.5  mm$^3$ (SD = 379.1 mm$^3$).\n\n\n\n\n## Empirical Rule: one way to think about the SD\n\n::: {style=\"font-size: 80%;\"}\n\n::: columns\n::: {.column width=\"40%\"}\nFor symmetric bell-shaped data, about\n\n* 68% of the data are within 1 SD of the mean\n* 95% of the data are within 2 SD's of the mean\n* 99.7% of the data are within 3 SD's of the mean\n\nThese percentages are based off of percentages of a true normal distribution.\n:::\n::: {.column width=\"60%\"}\n\n![[https://statistics-made-easy.com/empirical-rule/](https://statistics-made-easy.com/empirical-rule/)](/img_slides/empirical-rule.png){fig-align=\"center\" width=\"660\"}\n\n:::\n:::\n:::\n\n\n## Measures of spread: interquartile range (IQR) (1/2)\n\nThe $p^{th}$ percentile is the observation such that $p\\%$ of the remaining observations fall below this observation.\n\n  - The *first quartile* $Q_1$ is the $25^{th}$ percentile.\n  - The *second quartile* $Q_2$, i.e., the median, is the $50^{th}$ percentile.\n  - The *third quartile* $Q_3$ is the $75^{th}$ percentile.\n    \nThe __interquartile range (IQR)__ is the distance between the third and first quartiles.\n$$IQR = Q_3 - Q_1$$\n\n* IQR focuses on the **middle 50% of the data**.\n* Robust against outliers.\n\n\n## Measures of spread: interquartile range (IQR) (2/2)\n\n:::: {.columns}\n\n::: {.column width=\"60%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_intro_to_data_cont_files/figure-revealjs/unnamed-chunk-11-1.png){width=576}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"40%\"}\n\n\\\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(frog$clutch.volume)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  151.4   609.6   831.8   882.5  1096.5  2630.3 \n```\n\n\n:::\n:::\n\n\n\n$$IQR = Q_3 - Q_1 = 1096.5 - 609.6 = 486.9$$\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nIQR(frog$clutch.volume)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 486.9009\n```\n\n\n:::\n:::\n\n\n:::\n\n::::\n\n\n\n\n\n## Measures of spread: range\n\nThe **range** describes spread using only the **smallest** and **largest** values.\n\n$$\n\\text{Range} = \\max(x) - \\min(x)\n$$\n\n- Easy to compute and easy to interpret\n- **Not robust**: it depends only on two observations\n- A single unusually large or small value can dramatically change the range\n\n::: {.callout-note icon=false}\nBecause it is so sensitive to extreme values, the range is usually less informative than the SD or IQR.\n:::\n\n## Range and outliers (example)\n\n- $2, 7, 9$\n  - $min = 2, max = 9$\n  - $Range = 9 - 2 = 7$\n\n- $2, 7, 29$\n  - $min = 2, max = 29$\n  - $Range = 29 - 2 = 27$\n\n\nOnly one value changed, but the **range** changed a lot.\n\n\n## Robust estimates\n\nSummary statistics are called __robust estimates__ if extreme observations (outliers) have little effect on their values\n\n\n| Estimate           | Robust? |\n|--------------------|---------|\n| Sample mean        | ❌      |\n| Median             | ✅      |\n| Standard deviation | ❌      |\n| IQR                | ✅      |\n| Range              | ❌      |\n\n\n-   For samples with extreme values or skewed distributions, the **median and IQR** often provide a more stable summary of center and spread than the mean, standard deviation, or range.\n\n\n",
    "supporting": [
      "02_intro_to_data_cont_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}