{
  "hash": "7219f88ce89749155412c438eac79d9a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Power and Sample Size\"\nsubtitle: \"Textbook Section 5.4\"\nauthor: \"Emile Latour, Nicky Wakim, Meike Niederhausen\"\ndate: \"2026-02-18\"\ndate-format: long\nformat:\n  revealjs:\n    theme: \"../../assets/css/reveal-bmsc620_v5.scss\"\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"BMSC 620 | Power and Sample Size\"\n    html-math-method: mathjax\n    chalkboard: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n  freeze: auto\n---\n\n\n\n\n\n# Learning Objectives\n\nBy the end of today's lecture, you will be able to:\n\n1.  Understand the four components in equilibrium in a hypothesis test\n2.  Define and interpret Type I and Type II errors\n3.  Define power and understand its role in study design\n4.  Calculate power and sample size using R for one-sample t-tests\n5.  Calculate power and sample size using R for two-sample t-tests\n\n## Roadmap for Today\n\n::::: columns\n::: {.column width=\"50%\"}\n**Part 1: The Four Components**\n\n-   What affects our ability to detect effects?\n-   Significance level ($\\alpha$)\n-   Sample size ($n$)\n-   Effect size\n-   Power ($1-\\beta$)\n\n**Part 2: Errors in Hypothesis Testing**\n\n-   Type I errors ($\\alpha$)\n-   Type II errors ($\\beta$)\n-   Power as \"correct detection\"\n-   Visualizing errors with distributions\n:::\n\n::: {.column width=\"50%\"}\n**Part 3: Calculating Power and Sample Size**\n\n-   Introduction to Cohen's *d*\n-   Using the `pwr` package in R\n-   One-sample t-test examples\n-   Two-sample t-test examples\n\n**Part 4: Study Design Applications**\n\n-   Planning studies with power in mind\n-   Interpreting existing study results\n-   Trade-offs and practical considerations\n:::\n:::::\n\n# Connecting to What We Know\n\n## Where we've been: Hypothesis testing\n\n**Over the past few lectures, we've learned to:**\n\n-   Use **confidence intervals** to estimate population parameters\n-   Conduct **hypothesis tests** to evaluate claims about parameters\n-   Work with three types of t-tests:\n    -   One-sample (compare to known value)\n    -   Paired (compare before/after)\n    -   Two independent samples (compare groups)\n\n\\\n\n**In each case, we:**\n\n1.  Collected data\n2.  Calculated a test statistic\n3.  Got a p-value\n4.  Made a conclusion (reject $H_0$ or fail to reject)\n\n## Quick reference: Everything we've covered {.smaller}\n\n\\\n\n|   | One-sample | Independent two-sample | Paired sample |\n|------------------|------------------|------------------|------------------|\n| Example | Body temp: Population mean is 98.6°F, is sample different? | Caffeine: taps/min between caffeine and non-caffeine group | Vegetarian diet: cholesterol before and after |\n| Sample statistic | $\\bar{x}$ | $\\bar{x}_1 - \\bar{x}_2$ | $\\bar{x}_d$ |\n| Population parameter | $\\mu$ | $\\mu_1 - \\mu_2$ | $\\mu_d$ or $\\delta$ |\n| Possible hypothesis tests | $H_0: \\mu = \\mu_0$ | $H_0: \\mu_1 = \\mu_2$ or $\\mu_1 - \\mu_2 = 0$ | $H_0: \\mu_d = 0$ or $\\delta = 0$ |\n| Standard error | $SE = \\frac{s}{\\sqrt{n}}$ | $SE = \\sqrt{\\frac{s_1^2}{n_1} + \\frac{s_2^2}{n_2}}$ | $SE = \\frac{s_d}{\\sqrt{n}}$ |\n| Test statistic | $t = \\frac{\\bar{x} - \\mu_0}{SE}$ | $t = \\frac{(\\bar{x}_1 - \\bar{x}_2) - 0}{SE}$ | $t = \\frac{\\bar{x}_d - 0}{SE}$ |\n| Confidence intervals | $\\bar{x} \\pm t^* \\times SE$ | $(\\bar{x}_1 - \\bar{x}_2) \\pm t^* \\times SE$ | $\\bar{x}_d \\pm t^* \\times SE$ |\n\n\\\n\n*This summarizes all three test types - we'll use these concepts as we think about power*\n\n## The question we haven't answered yet\n\n\\\n\n**Scenario:** You're planning a new study\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n**Questions you need to answer:**\n\n-   How many participants do I need?\n-   Can I detect the effect I'm looking for?\n-   What if I can only recruit 20 people?\n-   Is my study worth running?\n:::\n\n::: {.column width=\"48%\"}\n**This is about study design:**\n\n-   *Before* collecting data\n-   *Before* spending time/money\n-   *Before* asking participants to volunteer\n-   Making sure your study can answer your question\n:::\n:::::\n\n\\\n\n**Today:** We learn how to design studies with adequate **power** to detect real effects\n\n## Motivating example: The caffeine study\n\n\\\n\n**Research Question:** Does caffeine increase finger tapping speed?\n\n\\\n\n**Study Design:**\n\n-   70 college students trained to tap fingers rapidly\n-   Randomly assigned to two groups:\n    -   **Control group:** Decaffeinated coffee (n=35)\n    -   **Caffeine group:** Coffee with 200mg caffeine (n=35)\n-   After 2 hours, measure taps per minute\n\n\\\n\n**Results:** The caffeine group had significantly higher taps/min (p \\< 0.001)\n\n## The questions we SHOULD have asked first\n\n**But what if we had asked BEFORE running the study:**\n\n-   \"We can only recruit 20 per group - is that enough?\"\n-   \"What difference can we actually detect with this sample size?\"\n-   \"How likely are we to find an effect if it's really there?\"\n\n\\\n\n**These questions are about POWER** - and that's what we'll learn today\n\n\\\n\n::: callout-note\nPower analysis happens *before* data collection, not after!\n:::\n\n# Part 1: The Four Components\n\n## What affects our ability to detect an effect?\n\n\\\n\n**Scenario:** Imagine two populations that differ in their mean tapping speed\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](15_power_sample_size_4_files/figure-revealjs/unnamed-chunk-1-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n\n**Question:** When we take samples from these groups, will it be easy to tell them apart?\n\n**Answer:** It depends on several factors...\n\n## Scenario 1: Small standard deviation\n\n\\\n\n**Same difference (5 taps/min), but less variability (SD = 1 instead of 2)**\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](15_power_sample_size_4_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n\n**Observation:** Less overlap between distributions makes the difference easier to detect!\n\n## Scenario 2: Larger difference\n\n**Larger difference (10 taps/min instead of 5), same variability (SD = 2)**\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](15_power_sample_size_4_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n\n\\\n\n**Observation:** A larger true difference is easier to detect!\n\n## What did we just observe?\n\n**From our visual examples, we noticed:**\n\n::: incremental\n1.  **Less variability** (smaller SD) → distributions pull apart → easier to detect difference\n\n2.  **Bigger true difference** → distributions pull apart → easier to detect difference\n\n3.  These affect how much **overlap** there is between groups\n:::\n\n\\\n\n::: fragment\n**But we're missing something important:**\n\n-   What about sample size? More data should help us detect differences\n-   What about our significance level? Being more strict (lower $\\alpha$) changes our threshold\n:::\n\n\\\n\n::: fragment\n**Let's formalize these ideas...**\n\nStatisticians recognize **four components** that work together in any hypothesis test. Change one, and you affect the others!\n:::\n\n## The four components in equilibrium\n\n\\\n\n**In any hypothesis test, four quantities are mathematically related:**\n\n::::::::: columns\n::::: {.column width=\"48%\"}\n::: {.callout-note icon=\"false\"}\n## 1. Significance level ($\\alpha$)\n\n-   Probability of Type I error\n-   Usually set at 0.05\n-   Set *before* collecting data\n-   Determines rejection region\n:::\n\n::: {.callout-note icon=\"false\"}\n## 2. Power ($1-\\beta$)\n\n-   Probability of detecting a real effect\n-   Typically want 80% or 90%\n-   What we calculate given the others\n-   The probability of \"correctly rejecting\"\n:::\n:::::\n\n::::: {.column width=\"48%\"}\n::: {.callout-note icon=\"false\"}\n## 3. Sample size ($n$)\n\n-   Number of observations\n-   Larger $n$ → smaller SE\n-   Often what we're trying to determine\n-   Constrained by time, cost, ethics\n:::\n\n::: {.callout-note icon=\"false\"}\n## 4. Effect size\n\n-   Difference we want to detect\n-   Relative to variability\n-   Often measured by Cohen's *d*\n-   Based on pilot data or literature\n:::\n:::::\n:::::::::\n\n**Key insight:** Given any 3 pieces, we can solve for the 4th.\n\n# Part 2: Errors in Hypothesis Testing\n\n\n\n## Significance levels and critical values\n\n:::::: columns\n::: {.column width=\"55%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](15_power_sample_size_4_files/figure-revealjs/unnamed-chunk-4-1.png){width=1056}\n:::\n:::\n\n\n:::\n\n:::: {.column width=\"45%\"}\n::: {.callout-note icon=\"false\"}\n## What are critical values?\n\nCutoff points that determine when to reject $H_0$\n\n**Determined by:**\n\n-   Significance level ($\\alpha$)\n-   One- vs two-sided test\\\n-   Distribution type\n\n**For our tests:**\n\n-   We've been using $t^*$ from t-distribution (figure shows z-distribution)\n-   Typically $\\alpha = 0.05$\n-   Two-sided tests (most common)\n\n**If |test statistic| > critical value → reject** $\\boldsymbol{H_0}$\n:::\n::::\n::::::\n\n## Rejection regions\n\n-   If the absolute value of the test statistic is greater than the critical value, we reject $H_0$\n    -   In this case the test statistic is in the **rejection region**.\n    -   Otherwise it's in the non-rejection region.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](15_power_sample_size_4_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n[Stats & Geospatial Analysis](https://www.geo.fu-berlin.de/en/v/soga/Basics-of-statistics/Hypothesis-Tests/Introduction-to-Hypothesis-Testing/Critical-Value-and-the-p-Value-Approach/index.html)\n\n## Visual: One-sided vs. two-sided\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](15_power_sample_size_4_files/figure-revealjs/unnamed-chunk-6-1.png){width=1152}\n:::\n:::\n\n\n\n\n## Hypothesis testing errors\n\n![[StatisticsSolutions](https://www.statisticssolutions.com/to-err-is-human-what-are-type-i-and-ii-errors/)](/img_slides/type_i_type_ii_pregnant.jpg){fig-align=\"center\" width=\"70%\"}\n\n## Justice system analogy \n\n<br><br>\n\n![[Type I and Type II Errors - Making Mistakes in the Justice System](http://www.intuitor.com/statistics/T1T2Errors.html)](/img_slides/intuitor_charts.png){fig-align=\"center\"}\n\n## Type I and Type II errors\n\n\\\n\n**Remember:** Hypothesis tests can make mistakes in two ways\n\n::::::: columns\n:::: {.column width=\"48%\"}\n::: {.callout-important icon=\"false\"}\n## Type I Error (False Positive)\n\n**Definition:** Reject $H_0$ when it's actually true\n\n**Notation:** Probability of making a Type I error = $\\alpha$\n\n**Example:** Conclude caffeine increases tapping when it really doesn't\n\n**Control:** Set $\\alpha$ before study (usually 0.05)\n\n**Also called:** False positive, $\\alpha$ error\n:::\n::::\n\n:::: {.column width=\"48%\"}\n::: {.callout-warning icon=\"false\"}\n## Type II Error (False Negative)\n\n**Definition:** Fail to reject $H_0$ when it's false\n\n**Notation:** Probability of making a Type II error = $\\beta$\n\n**Example:** Fail to detect caffeine effect when it really exists\n\n**Control:** Increase sample size, decrease variability\n\n**Also called:** False negative, $\\beta$ error\n:::\n::::\n:::::::\n\n\\\n\n**Trade-off:** Decreasing one type of error often increases the other!\n\n## Power: The probability of correctly detecting an effect\n\n::: {.callout-tip icon=\"false\"}\n\n## Power Definition\n\n**Power** = $1 - \\beta$ = Probability of correctly rejecting $H_0$ when it's false\n\n-   The probability of detecting an effect that actually exists\n-   Typically want power ≥ 0.80 (80%)\n-   Some fields require 0.90 (90%)\n:::\n\n\\\n\n::: columns\n::: {.column width=\"50%\"}\n**Why 80%?** This is a convention balancing:\n\n-   Reasonable chance of detecting real effects\n-   Practical constraints on sample size\n-   Cost and feasibility\n:::\n\n::: {.column width=\"50%\"}\n**Think of it this way:**\n\n-   High power = good \"detector\" - likely to find effect if it exists\n-   Low power = bad \"detector\" - might miss real effects\n:::\n:::\n\n## The complete picture\n\n<table style=\"border-bottom: 1px solid black;\">\n<thead>\n  <tr>\n    <th></th>\n    <th colspan=\"2\" style=\"text-align: center;\">Reality</th>\n  </tr>\n  <tr>\n    <th>Test decision</th>\n    <th>$H_0$ True</th>\n    <th>$H_1$ True</th>\n  </tr>\n</thead>\n<tbody>\n  <tr>\n    <td><strong>Reject</strong> $H_0$</td>\n    <td>Type I Error ($\\alpha$)</td>\n    <td><strong>Power</strong> ($1-\\beta$) ✓</td>\n  </tr>\n  <tr>\n    <td><strong>Fail to reject</strong> $H_0$</td>\n    <td>Correct ($1-\\alpha$) ✓</td>\n    <td>Type II Error ($\\beta$)</td>\n  </tr>\n</tbody>\n</table>\n\n\n\n<!-- | **Reality**              | $H_0$ True              | $H_0$ False             | -->\n<!-- |---------------------|-------------------------|---------------------------| -->\n<!-- | **Reject** $H_0$         | Type I Error ($\\alpha$) | **Power** ($1-\\beta$) ✓ | -->\n<!-- | **Fail to reject** $H_0$ | Correct ($1-\\alpha$) ✓  | Type II Error ($\\beta$) | -->\n\n\\\n\n**Correct decisions:**\n\n-   $1 - \\alpha$: Confidence (correctly fail to reject when $H_0$ is true)\n-   $1 - \\beta$: Power (correctly reject $H_0$ when $H_1$ is true)\n\n\\\n\n**Errors:**\n\n-   $\\alpha$: Type I error rate (false positive)\n-   $\\beta$: Type II error rate (false negative)\n\n\\\n\n**What we control in study design:** We typically fix $\\alpha$ at 0.05 and choose $n$ to achieve desired power\n\n<!-- ## Visualizing these concepts -->\n\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- #| fig-width: 12 -->\n<!-- #| fig-height: 6 -->\n<!-- #| fig-align: center -->\n\n<!-- # Set up parameters -->\n<!-- mu_null <- 0 -->\n<!-- mu_alt <- 3 -->\n<!-- sd <- 1 -->\n<!-- alpha <- 0.05 -->\n<!-- cv <- qnorm(1 - alpha/2)  # Critical value for two-sided test -->\n\n<!-- # Create the plot -->\n<!-- ggplot(data.frame(x = c(-3, 7)), aes(x)) + -->\n<!--   # Null distribution -->\n<!--   stat_function(fun = dnorm,  -->\n<!--                 args = list(mean = mu_null, sd = sd), -->\n<!--                 linewidth = 1.5, -->\n<!--                 color = \"#E69F00\") + -->\n<!--   # Alternative distribution   -->\n<!--   stat_function(fun = dnorm,  -->\n<!--                 args = list(mean = mu_alt, sd = sd), -->\n<!--                 linewidth = 1.5, -->\n<!--                 color = \"#0072B2\") + -->\n<!--   # Rejection regions under null (Type I error) -->\n<!--   stat_function(fun = dnorm,  -->\n<!--                 args = list(mean = mu_null, sd = sd), -->\n<!--                 xlim = c(-3, -cv), -->\n<!--                 geom = \"area\",  -->\n<!--                 fill = \"#CC79A7\",  -->\n<!--                 alpha = 0.7) + -->\n<!--   stat_function(fun = dnorm,  -->\n<!--                 args = list(mean = mu_null, sd = sd), -->\n<!--                 xlim = c(cv, 4), -->\n<!--                 geom = \"area\",  -->\n<!--                 fill = \"#CC79A7\",  -->\n<!--                 alpha = 0.7) + -->\n<!--   # Type II error region -->\n<!--   stat_function(fun = dnorm,  -->\n<!--                 args = list(mean = mu_alt, sd = sd), -->\n<!--                 xlim = c(-1, cv), -->\n<!--                 geom = \"area\",  -->\n<!--                 fill = \"#F0E442\",  -->\n<!--                 alpha = 0.6) + -->\n<!--   # Power region -->\n<!--   stat_function(fun = dnorm,  -->\n<!--                 args = list(mean = mu_alt, sd = sd), -->\n<!--                 xlim = c(cv, 7), -->\n<!--                 geom = \"area\",  -->\n<!--                 fill = \"#009E73\",  -->\n<!--                 alpha = 0.5) + -->\n<!--   # Labels -->\n<!--   annotate(\"text\", x = -1.5, y = 0.3,  -->\n<!--            label = \"Null\\nDistribution\",  -->\n<!--            size = 5, color = \"#E69F00\") + -->\n<!--   annotate(\"text\", x = 4, y = 0.3,  -->\n<!--            label = \"Alternative\\nDistribution\",  -->\n<!--            size = 5, color = \"#0072B2\") + -->\n<!--   annotate(\"text\", x = -2.5, y = 0.02,  -->\n<!--            label = \"α/2\",  -->\n<!--            size = 5, color = \"#CC79A7\") + -->\n<!--   annotate(\"text\", x = 2.7, y = 0.02,  -->\n<!--            label = \"α/2\",  -->\n<!--            size = 5, color = \"#CC79A7\") + -->\n<!--   annotate(\"text\", x = 1, y = 0.08,  -->\n<!--            label = \"β\\n(Type II error)\",  -->\n<!--            size = 4.5, color = \"#806000\") + -->\n<!--   annotate(\"text\", x = 4, y = 0.15,  -->\n<!--            label = \"Power\\n(1-β)\",  -->\n<!--            size = 5, color = \"#009E73\") + -->\n<!--   # Critical value line -->\n<!--   geom_vline(xintercept = cv,  -->\n<!--              linetype = \"dashed\",  -->\n<!--              linewidth = 1, -->\n<!--              color = \"black\") + -->\n<!--   annotate(\"text\", x = cv + 0.3, y = 0.42,  -->\n<!--            label = \"Critical\\nvalue\",  -->\n<!--            size = 4) + -->\n<!--   labs(x = \"Test Statistic\",  -->\n<!--        y = \"Probability Density\", -->\n<!--        title = \"Type I error, Type II error, and Power\") + -->\n<!--   theme(text = element_text(size = 14)) -->\n<!-- ``` -->\n\n\n<!-- **Key observations:** -->\n\n<!-- -   Type I error ($\\alpha$): Area in tails under null distribution -->\n<!-- -   Type II error ($\\beta$): Area to left of critical value under alternative -->\n<!-- -   Power ($1-\\beta$): Area to right of critical value under alternative -->\n\n<!-- ## Visualizing Type I error, Type II error, and Power -->\n\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- #| fig-width: 12 -->\n<!-- #| fig-height: 6 -->\n<!-- #| fig-align: center -->\n\n<!-- library(ggplot2) -->\n\n<!-- # Parameters -->\n<!-- mu_null <- 0; mu_alt <- 3; sd <- 1; alpha <- 0.05 -->\n<!-- cv <- qnorm(1 - alpha/2) -->\n\n<!-- ggplot(data.frame(x = c(-3, 7)), aes(x)) + -->\n<!--   # 1. Shading (Power and Beta) - Keep these primary -->\n<!--   stat_function(fun = dnorm, args = list(mean = mu_alt, sd = sd), -->\n<!--                 xlim = c(-1, cv), geom = \"area\", fill = \"#F0E442\", alpha = 0.4) + -->\n<!--   stat_function(fun = dnorm, args = list(mean = mu_alt, sd = sd), -->\n<!--                 xlim = c(cv, 7), geom = \"area\", fill = \"#009E73\", alpha = 0.4) + -->\n\n<!--   # 2. Rejection Region (Alpha) - Small but distinct -->\n<!--   stat_function(fun = dnorm, args = list(mean = mu_null, sd = sd), -->\n<!--                 xlim = c(cv, 4), geom = \"area\", fill = \"#CC79A7\", alpha = 0.6) + -->\n\n<!--   # 3. The Curves (Linewidth hierarchy) -->\n<!--   stat_function(fun = dnorm, args = list(mean = mu_null, sd = sd), -->\n<!--                 linewidth = 0.8, color = \"grey40\", linetype = \"dashed\") + # Null as \"background\" -->\n<!--   stat_function(fun = dnorm, args = list(mean = mu_alt, sd = sd), -->\n<!--                 linewidth = 1.2, color = \"#0072B2\") + -->\n\n<!--   # 4. The \"Decision Wall\" -->\n<!--   geom_vline(xintercept = cv, linewidth = 1, color = \"black\") + -->\n<!--   annotate(\"label\", x = cv, y = 0.42, label = \"Critical Value\",  -->\n<!--            fill = \"white\", size = NA, fontface = \"bold\") + -->\n\n<!--   # 5. Strategic Labeling (using plotmath for Greek) -->\n<!--   annotate(\"text\", x = mu_null, y = 0.42, label = \"H[0]\", parse = TRUE, color = \"grey40\", size = 7) + -->\n<!--   annotate(\"text\", x = mu_alt, y = 0.42, label = \"H[1]\", parse = TRUE, color = \"#0072B2\", size = 7) + -->\n<!--   annotate(\"text\", x = 1.2, y = 0.02, label = \"beta\", parse = TRUE, size = 7) + -->\n<!--   annotate(\"text\", x = 3.25, y = 0.15, label = \"1-beta\", parse = TRUE, size = 7) + -->\n<!--   annotate(\"text\", x = 2.2, y = 0.02, label = \"alpha\", parse = TRUE, size = 7) + -->\n<!--   annotate(\"text\", x = -0.25, y = 0.15, label = \"1-alpha\", parse = TRUE, size = 7) +  -->\n\n<!--   # 6. Clean Theme -->\n<!--   laviz::theme_minimal_white(grid = \"none\") + -->\n<!--   labs(x = NULL,  -->\n<!--        y = NULL,  -->\n<!--        title = \"The Relationship Between Alpha, Beta, and Power\") + -->\n<!--   theme(panel.grid.minor = element_blank(), -->\n<!--         axis.text.x = element_blank(),  -->\n<!--         axis.text.y = element_blank()) -->\n<!-- ``` -->\n\n<!-- ## Visualizing Type I error, Type II error, and Power -->\n\n<!-- ::: {.fragment} -->\n<!-- **Two possible realities:** -->\n\n<!-- - Dashed grey: $H_0$ is true (no effect) -->\n<!-- - Solid blue: $H_A$ is true (real effect exists) -->\n<!-- ::: -->\n\n<!-- ::: {.fragment} -->\n<!-- **Our decision boundary:** The critical value separates \"reject\" from \"don't reject\" -->\n<!-- ::: -->\n\n<!-- ::: {.fragment} -->\n<!-- **Under $H_0$ (grey curve):** Pink region (α) = Type I error when we wrongly reject -->\n<!-- ::: -->\n\n<!-- ::: {.fragment} -->\n<!-- **Under $H_A$ (blue curve):**  -->\n\n<!-- - Yellow (β) = Type II error - we miss the real effect -->\n<!-- - Green (1-β) = **Power** - we correctly detect the effect! -->\n<!-- ::: -->\n\n<!-- ::: {.fragment} -->\n<!-- **The key insight:** These are all connected - changing one affects the others! -->\n<!-- ::: -->\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- #| fig-width: 12 -->\n<!-- #| fig-height: 6 -->\n<!-- #| fig-align: center -->\n\n<!-- library(ggplot2) -->\n\n<!-- # Parameters -->\n<!-- mu_null <- 0; mu_alt <- 3; sd <- 1; alpha <- 0.05 -->\n<!-- cv <- qnorm(1 - alpha/2) -->\n\n<!-- ggplot(data.frame(x = c(-3, 7)), aes(x)) + -->\n<!--   # 1. Shading (Power and Beta) - Keep these primary -->\n<!--   stat_function(fun = dnorm, args = list(mean = mu_alt, sd = sd), -->\n<!--                 xlim = c(-1, cv), geom = \"area\", fill = \"#F0E442\", alpha = 0.4) + -->\n<!--   stat_function(fun = dnorm, args = list(mean = mu_alt, sd = sd), -->\n<!--                 xlim = c(cv, 7), geom = \"area\", fill = \"#009E73\", alpha = 0.4) + -->\n\n<!--   # 2. Rejection Region (Alpha) - Small but distinct -->\n<!--   stat_function(fun = dnorm, args = list(mean = mu_null, sd = sd), -->\n<!--                 xlim = c(cv, 4), geom = \"area\", fill = \"#CC79A7\", alpha = 0.6) + -->\n\n<!--   # 3. The Curves (Linewidth hierarchy) -->\n<!--   stat_function(fun = dnorm, args = list(mean = mu_null, sd = sd), -->\n<!--                 linewidth = 0.8, color = \"grey40\", linetype = \"dashed\") + # Null as \"background\" -->\n<!--   stat_function(fun = dnorm, args = list(mean = mu_alt, sd = sd), -->\n<!--                 linewidth = 1.2, color = \"#0072B2\") + -->\n\n<!--   # 4. The \"Decision Wall\" -->\n<!--   geom_vline(xintercept = cv, linewidth = 1, color = \"black\") + -->\n<!--   annotate(\"label\", x = cv, y = 0.42, label = \"Critical Value\",  -->\n<!--            fill = \"white\", label.size = NA, fontface = \"bold\") + -->\n\n<!--   # 5. Strategic Labeling (using plotmath for Greek) -->\n<!--   annotate(\"text\", x = mu_null, y = 0.42, label = \"H[0]\", parse = TRUE, color = \"grey40\", size = 7) + -->\n<!--   annotate(\"text\", x = mu_alt, y = 0.42, label = \"H[1]\", parse = TRUE, color = \"#0072B2\", size = 7) + -->\n<!--   annotate(\"text\", x = 1.2, y = 0.02, label = \"beta\", parse = TRUE, size = 7) + -->\n<!--   annotate(\"text\", x = 3.25, y = 0.15, label = \"1-beta\", parse = TRUE, size = 7) + -->\n<!--   annotate(\"text\", x = 2.2, y = 0.02, label = \"alpha\", parse = TRUE, size = 7) + -->\n<!--   annotate(\"text\", x = -0.25, y = 0.15, label = \"1-alpha\", parse = TRUE, size = 7) +  -->\n\n<!--   # 6. Clean Theme -->\n<!--   laviz::theme_minimal_white(grid = \"none\") + -->\n<!--   labs(x = NULL,  -->\n<!--        y = NULL,  -->\n<!--        title = \"The Relationship Between Alpha, Beta, and Power\") + -->\n<!--   theme(panel.grid.minor = element_blank(), -->\n<!--         axis.text.x = element_blank(),  -->\n<!--         axis.text.y = element_blank()) -->\n<!-- ``` -->\n\n## Visualizing Type I error, Type II error, and Power (II)\n\n::: columns\n::: {.column width=\"30%\"}\n::: {.fragment}\n**Two possible realities:**\n\n- Dashed grey: $H_0$ is true (no effect)\n- Solid blue: $H_A$ is true (real effect exists)\n:::\n\n::: {.fragment}\n**Our decision boundary:** The critical value separates \"reject\" from \"don't reject\"\n:::\n\n::: {.fragment}\n**Under $H_0$ (grey curve):** \n\n- Pink region (α) = Type I error when we wrongly reject\n:::\n\n::: {.fragment}\n**Under $H_A$ (blue curve):** \n\n- Yellow (β) = Type II error - we miss the real effect\n- Green (1-β) = **Power** - we correctly detect the effect!\n:::\n\n\n:::\n\n::: {.column width=\"70%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](15_power_sample_size_4_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n::: {.fragment}\n**The key insight:** These are all connected - changing one affects the others!\n:::\n:::\n:::\n\n\n\n\n\n\n## What increases power?\n\n**Power increases when:**\n\n::::: columns\n::: {.column width=\"48%\"}\n**1. Larger sample size (**$n$)\n\n-   Reduces standard error\n-   Narrows sampling distributions\n-   Makes distributions more separated\n\n\\\n\n**2. Larger effect size**\n\n-   Greater true difference\n-   More separation between null and alternative\n-   Easier to distinguish groups\n:::\n\n::: {.column width=\"48%\"}\n**3. Less variability**\n\n-   Smaller population SD ($\\sigma$)\n-   Tighter distributions\n-   Less overlap\n\n\\\n\n**4. Higher significance level**\n\n-   Larger $\\alpha$ (but increases Type I error!)\n-   Usually not recommended\n-   Trade-off between errors\n:::\n:::::\n\n\\\n\n## Practical implications:\n\n\\\n\n-   We usually have most control over sample size\n-   Can sometimes reduce variability through better measurement\n-   Effect size is a property of reality — we estimate it, we don’t choose it\n-   Significance level is conventionally fixed at 0.05\n\n<!-- The key insight: -->\n<!-- You can't change the true effect size - it's a property of reality. -->\n<!-- If a new blood pressure medication truly reduces systolic BP by an average of 8 mmHg compared to placebo, that's what it does. You can't make that effect bigger just because you want more statistical power. The drug's actual effectiveness is determined by its pharmacology (nature) and how it interacts with the human body (biology). -->\n<!-- Contrast with what you CAN control: -->\n\n<!-- Sample size: You can recruit 50 people or 500 people - totally in your control (with budget/time constraints) -->\n<!-- Variability: You have some control - use better measurement equipment, standardize protocols, select more homogeneous populations -->\n<!-- Alpha: Technically flexible, but conventionally fixed at 0.05 -->\n<!-- Effect size: NOT in your control - it is what it is in the real world -->\n\n<!-- For power analysis purposes: -->\n<!-- When planning a study, you have to: -->\n\n<!-- Guess/estimate what the effect size might be (from pilot data, literature, or clinical meaningfulness) -->\n<!-- Accept that guess as your working assumption -->\n<!-- Manipulate sample size to achieve desired power for detecting that effect size -->\n\n<!-- You can't say \"I need more power, so I'll assume a bigger effect size\" - that would be wishful thinking! -->\n<!-- Better phrasing options: -->\n<!-- If this still feels unclear for your students, you might consider: -->\n\n<!-- \"Effect size reflects the true magnitude of the phenomenon we're studying\" -->\n<!-- \"Effect size is a property of the real-world phenomenon, not a design choice\" -->\n<!-- \"We estimate effect size; we don't choose it\" -->\n\n# Part 3: Calculating Power and Sample Size\n\n## Why do power calculations?\n\n**Before collecting data (prospective):**\n\n-   Determine required sample size for adequate power\n-   Justify sample size in grant proposals/protocols\n-   Avoid underpowered studies that waste resources\n-   Ensure ethical use of participants\n\n\\\n\n**After collecting data (post-hoc):**\n\n-   Understand power of completed study\n-   Plan follow-up studies\n\n\\\n\n::: callout-warning\n## Important Note\n\nPost-hoc power calculations for non-significant results can be misleading! Better to report confidence intervals showing uncertainty.\n:::\n\n## Cohen's d: Standardized effect size\n\n\\\n\n\n**Problem:** Effect sizes are in original units (e.g., taps/min, mmHg, °F)\n\n-   Hard to compare across studies\n-   Can't have general guidelines\n\n\\\n\n**Solution:** Cohen's *d* standardizes the effect size\n\n\n## Cohen's d: Standardized effect size\n\n\\\n\n::: {.callout-note icon=\"false\"}\n## Cohen's d Formulas\n\n**One-sample test (or paired):** $$d = \\frac{\\bar{x} - \\mu_0}{s} \\quad \\text{or} \\quad d = \\frac{\\bar{x}_d - \\delta_0}{s_d}$$\n\n**Two-sample test:** $$d = \\frac{\\bar{x}_1 - \\bar{x}_2}{s_{\\text{pooled}}}$$\n\nwhere $s_{\\text{pooled}} = \\sqrt{\\frac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1 + n_2 - 2}}$\n\n\\\n\nFor two-sample d, we often use pooled SD when group variances are similar; there are variants when they are not.\n:::\n\n## Interpreting Cohen's d\n\n**Cohen's guidelines for effect size:**\n\n| Effect Size | $d$ value | Interpretation                               |\n|-------------|-----------|----------------------------------------------|\n| Small       | 0.2       | Difficult to detect, subtle effect           |\n| Medium      | 0.5       | Moderate effect, visible to careful observer |\n| Large       | 0.8       | Large effect, obvious to casual observer     |\n\n\\\n\n**Example interpretations:**\n\n-   *d* = 0.2: Treatment shifts mean by 0.2 standard deviations\n-   *d* = 0.5: Treatment shifts mean by half a standard deviation\n-   *d* = 0.8: Treatment shifts mean by 0.8 standard deviations\n\n\\\n\n**Important:** These are just guidelines! What's \"small\" or \"large\" depends on context\n\n-   In medicine: Small effects can be clinically important\n-   In psychology: Large effects might indicate measurement problems\n\n## The pwr package in R\n\n**We'll use the `pwr` package for power calculations**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pwr)\n```\n:::\n\n\n\n\\\n\n**Key function:** `pwr.t.test()`\n\n-   Works for one-sample, two-sample, and paired t-tests\n-   Specify all parameters except one\n-   Returns the missing parameter\n\n\\\n\n**Function structure:**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.t.test(n = NULL,           # Sample size per group\n           d = NULL,           # Cohen's d effect size  \n           sig.level = 0.05,   # Significance level (α)\n           power = NULL,       # Power (1-β)\n           type = \"two.sample\", # or \"one.sample\", \"paired\"\n           alternative = \"two.sided\") # or \"less\", \"greater\"\n```\n:::\n\n\n\n**Leave out the parameter you want to calculate!**\n\n## Example 1: One-sample test - Finding sample size\n\n**Scenario:** Body temperature study\n\n-   We believe true mean is 98.25°F (vs. claimed 98.6°F)\n-   Pilot data suggests SD ≈ 0.73°F\n-   Want 80% power with $\\alpha = 0.05$\n-   **Question:** How many people do we need?\n\n\\\n\n**Step 1:** Calculate Cohen's d\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Effect size\nmu0 <- 98.6      # Null value\nmu_true <- 98.25 # What we believe is true\ns <- 0.73        # Standard deviation from pilot data\n\nd <- (mu_true - mu0) / s\nd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.4794521\n```\n\n\n:::\n:::\n\n\n\n**Interpretation:** The true mean differs from null by 0.48 standard deviations\n\n## Example 1: One-sample test - Finding sample size (cont.)\n\n**Step 2:** Use `pwr.t.test()` to find required sample size\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Specify all parameters except for sample size, n\n\nresult <- pwr.t.test(\n  d = (98.6 - 98.25) / 0.73,  # Cohen's d\n  sig.level = 0.05,            # α = 0.05\n  power = 0.80,                # Want 80% power\n  type = \"one.sample\",         # One-sample test\n  alternative = \"two.sided\"    # Two-sided test\n)\n\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     One-sample t test power calculation \n\n              n = 36.11196\n              d = 0.4794521\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n```\n\n\n:::\n:::\n\n\n\n\\\n\n**Conclusion:** We need **37 participants** to have 80% power to detect this difference at $\\alpha = 0.05$\n\n## Visualizing the power curve\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(result)\n```\n\n::: {.cell-output-display}\n![](15_power_sample_size_4_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n**The curve shows:** As sample size increases, power increases (holding other factors constant)\n\n## Example 2: One-sample test - Calculating power\n\n**Scenario:** Same body temperature study, but the sample size is fixed\n\n-   n = 130 participants\n-   Effect size: d = 0.479\n-   $\\alpha = 0.05$\n-   **Question:** What power do we have given the sample size we have?\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Specify all parameters except for power\n\nresult_power <- pwr.t.test(\n  n = 130,                     # Sample size we have\n  d = (98.6 - 98.25) / 0.73,   # Cohen's d\n  sig.level = 0.05,            # α = 0.05\n  type = \"one.sample\",\n  alternative = \"two.sided\"\n)\n```\n:::\n\n\n\n## Example 2: One-sample test - Calculating power (cont.)\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult_power\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     One-sample t test power calculation \n\n              n = 130\n              d = 0.4794521\n      sig.level = 0.05\n          power = 0.9997354\n    alternative = two.sided\n```\n\n\n:::\n:::\n\n\n\n\\\n\n**Conclusion:** With n=130, we had **100%** power! (Very high - almost certain to detect the effect if it exists)\n\n## Example 3: Two-sample test - Finding sample size\n\n\\\n\n**Scenario:** Caffeine tapping study\n\n-   Want to detect 2 taps/min difference between groups\n-   Expect SD ≈ 2.6 taps/min in each group\n-   Want 80% power with $\\alpha = 0.05$\n-   **Question:** How many participants per group do we need?\n\n\\\n\n**Step 1:** Calculate Cohen's d\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiff <- 2          # Difference we want to detect\nsd_pooled <- 2.6   # Expected SD in each group\n\nd <- diff / sd_pooled\nd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7692308\n```\n\n\n:::\n:::\n\n\n\n\\\n\n## Example 3: Two-sample test - Finding sample size (cont.)\n\n**Step 2:** Calculate required sample size\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Specify all parameters except for sample size, n\n\nresult_caff <- pwr.t.test(\n  d = d,\n  sig.level = 0.05,\n  power = 0.80,\n  type = \"two.sample\",        # Two independent groups\n  alternative = \"two.sided\"\n)\n\nresult_caff\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 27.52331\n              d = 0.7692308\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\n\n**Conclusion:** Need **28 participants per group** (total n = 56)\n\n## Example 4: Two-sample test - Calculating power\n\n\\\n\n**Scenario:** We have 35 subjects per group in the Caffeine study\n\n- Effect size: $d = 0.77$\n  - difference of $2$ points between the two groups\n  - assuming $SD = 2.6$ in both groups\n- $\\alpha = 0.05$\n- **Question:** What power do we have to detect this difference?\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Specify all parameters except for power\n\nresult_caff_power <- pwr.t.test(\n  n = 35,      # Sample size per group             \n  d = 2 / 2.6,\n  sig.level = 0.05,\n  type = \"two.sample\",\n  alternative = \"two.sided\"\n)\n```\n:::\n\n\n\n\n## Example 4: Two-sample test - Calculating power (cont.)\n\n\\\n\n::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult_caff_power\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 35\n              d = 0.7692308\n      sig.level = 0.05\n          power = 0.8872805\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(result_caff_power)\n```\n\n::: {.cell-output-display}\n![](15_power_sample_size_4_files/figure-revealjs/unnamed-chunk-19-1.png){width=960}\n:::\n:::\n\n\n\n:::\n:::\n\n\\\n\n**Conclusion:** With n=35 per group, we have **88.7%** power (excellent!)\n\n## One-sided vs two-sided tests and power\n\n\n::: columns\n::: {.column width=\"50%\"}\n\n### Two-sided test:\n\n$H_A: \\mu \\neq \\mu_0$ (most common)\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Two-sided test\ntwo_sided <- pwr.t.test(\n  d = 0.5, \n  sig.level = 0.05, \n  power = 0.80, \n  type = \"two.sample\", \n  alternative = \"two.sided\"\n)\n\ntwo_sided\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 63.76561\n              d = 0.5\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\n\n:::\n::: {.column width=\"50%\"}\n\n### One-sided test:\n\n$H_A: \\mu > \\mu_0$ or $H_A: \\mu < \\mu_0$\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# One-sided test  \none_sided <- pwr.t.test(\n  d = 0.5, \n  sig.level = 0.05, \n  power = 0.80,\n  type = \"two.sample\", \n  alternative = \"greater\"\n)\n\none_sided\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 50.1508\n              d = 0.5\n      sig.level = 0.05\n          power = 0.8\n    alternative = greater\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\n\n:::\n:::\n\n## One-sided vs two-sided tests and power (cont.)\n\n\\\n\n**Key point:** One-sided tests require smaller sample sizes BUT:\n\n-   Only justified when direction is known *a priori*\n-   Can't detect effects in \"wrong\" direction\n-   Generally not recommended unless strong scientific justification\n-   Reviewers/collaborators often require lower $\\alpha$ (e.g., 0.025) for one-sided tests\n\n# Part 4: Study Design Applications\n\n## The power-sample size trade-off\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n**Increasing sample size:**\n\n✓ Increases power\n\n✓ More likely to detect real effects\n\n✓ More precise estimates\n\n\\\n\n✗ More expensive\n\n✗ Takes longer\n\n✗ May not be feasible\n:::\n\n::: {.column width=\"48%\"}\n**Practical constraints:**\n\n-   Budget limitations\n-   Time constraints\n-   Available participants\n-   Ethical considerations\n-   Feasibility\n\n\\\n\n**The balance:** Choose smallest $n$ that gives adequate power (usually 80-90%)\n:::\n:::::\n\n## Common mistakes in power analysis\n\n::: callout-warning\n## Mistake 1: Post-hoc power for non-significant results\n\n**Don't do this:** \"Our result was non-significant (p=0.12). Let me calculate power...\"\n\n**Why it's wrong:** Post-hoc power for non-significant results is always low - tells you nothing!\n\n**Do instead:** Report confidence interval showing uncertainty\n:::\n\n\\\n\n::: callout-warning\n## Mistake 2: Using observed effect size for power\n\n**Don't do this:** Calculate power using the effect size you observed\n\n**Why it's wrong:** If result was non-significant, observed effect is likely underestimate\n\n**Do instead:** Use effect size from pilot data, literature, or smallest clinically meaningful effect\n:::\n\n## Common mistakes continued\n\n::: callout-warning\n## Mistake 3: Ignoring practical significance\n\n**Don't do this:** Design study to detect any statistically significant difference\n\n**Why it's wrong:** Tiny, clinically meaningless effects can be significant with large n\n\n**Do instead:** Base power on *clinically/scientifically meaningful* effect size\n:::\n\n\\\n\n::: callout-warning\n## Mistake 4: Not considering variability\n\n**Don't do this:** Assume optimistic (low) SD when planning sample size\n\n**Why it's wrong:** Real data often more variable → study underpowered\n\n**Do instead:** Use conservative (higher) SD estimate, or add 10-20% to planned n as buffer\n:::\n\n## Real-world example: A cautionary tale\n\n\\\n\n::: columns\n::: {.column width=\"50%\"}\n**Study:** New drug to lower blood pressure\n\n\n\n\n\n\n\n\n-   Powered to detect 5 mmHg reduction\n-   Assumed SD = 10 mmHg (from literature)\n-   Calculated need for n = 64 per group\n\n\\\n\n-   Only recruited n = 50 per group due to budget constraints\n-   Actual SD in study was 12 mmHg (more variability than expected)\n\n\\\n\n**Result:**\n\n-   Observed reduction: 4 mmHg (close to target!)\n-   *p*-value = 0.090 (not significant at 0.05 level)\n-   Actual power was only 38% (not the planned 80%)\n-   Study deemed \"negative\" despite clinically meaningful effect\n:::\n\n::: {.column width=\"50%\"}\n**Lessons:**\n\n1.  Small deviations from plan can substantially reduce power\n2.  Under-recruitment is very common - build in buffer\n3.  Conservative SD estimates are wise\n:::\n:::\n\n\n\n\n## When is a study \"underpowered\"?\n\n\\\n\n::: columns\n::: {.column width=\"50%\"}\n**Conventionally:**\n\n-   Power \\< 50%: Severely underpowered\n-   Power 50-70%: Underpowered\n-   Power 70-80%: Marginally adequate\n-   Power 80-90%: Good\n-   Power \\> 90%: Excellent (sometimes wasteful)\n:::\n::: {.column width=\"50%\"}\n**Practical considerations:**\n\n-   **80% power** is standard for many studies\n-   **90% power** for important decisions (e.g., FDA approval)\n-   **Lower power acceptable** for:\n    -   Pilot/feasibility studies\n    -   Exploratory research\n    -   Studies where negative result is informative\n:::\n:::\n\n\n\\\n\n::: callout-tip\nAlways report your power analysis in papers/grants! Shows thoughtful study design.\n:::\n\n## Using power analysis in different scenarios\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n**Planning a new study:**\n\n1.  Review literature for expected effect size\n2.  Use conservative estimates\n3.  Choose a target power (usually 80–90%) and calculate required sample size\n4.  Add 10-20% buffer for dropout\n5.  Check if feasible\n\n\\\n\n**Evaluating a completed study:**\n1.  Focus on effect estimates and confidence intervals\n2.  If non-significant: Is CI compatible with meaningful effect?\n3.  Don't calculate \"achieved power\" (mathematically determined by the *p*-value)\n4.  Use observed effect size & SD to plan follow-up studies\n:::\n\n::: {.column width=\"48%\"}\n**Reviewing others' work:**\n\n1.  Check if power analysis reported\n2.  Evaluate if assumptions reasonable\n3.  Consider if study adequately powered\n4.  Be skeptical of underpowered studies\n\n\\\n\n**Grant writing:**\n\n1.  Justify sample size with power analysis\n2.  Show you calculated it prospectively\n3.  Document all assumptions\n4.  Include sensitivity analyses\n:::\n:::::\n\n# Wrap-up and Key Takeaways\n\n## Summary: The big picture\n\n\\\n\n**Four quantities in equilibrium:**\n\n1.  **Significance level** ($\\alpha$) - usually fixed at 0.05\n2.  **Effect size** - a property of reality (we estimate it, we do not choose it)\n3.  **Sample size** ($n$) - what we typically calculate\n4.  **Power** ($1-\\beta$) - probability of detecting real effect\n\n\\\n\n**Key concepts:**\n\n-   Power = Probability of correctly detecting an effect when it exists\n-   Type I error ($\\alpha$) = False positive\n-   Type II error ($\\beta$) = False negative\\\n-   Cohen's *d* = Standardized effect size\n-   Typical target: 80-90% power\n\n## Key R functions\n\n**Main function:** `pwr.t.test()`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pwr)\n\n# Calculate sample size (leave n = NULL)\npwr.t.test(d = 0.5, sig.level = 0.05, power = 0.80,\n           type = \"two.sample\", alternative = \"two.sided\")\n\n# Calculate power (leave power = NULL)  \npwr.t.test(n = 50, d = 0.5, sig.level = 0.05,\n           type = \"two.sample\", alternative = \"two.sided\")\n\n# Calculate detectable effect size (leave d = NULL)\npwr.t.test(n = 50, sig.level = 0.05, power = 0.80,\n           type = \"two.sample\", alternative = \"two.sided\")\n```\n:::\n\n\n\n\\\n\n**Types:** `\"one.sample\"`, `\"two.sample\"`, `\"paired\"`\n\n**Alternatives:** `\"two.sided\"` (most common), `\"less\"`, `\"greater\"`\n\n## Best practices for power analysis\n\n1.  **Plan prospectively** - before collecting data\n2.  **Use realistic effect sizes** - from literature or pilot data\\\n3.  **Be conservative** - overestimate SD, add buffer to sample size\n4.  **Consider practical significance** - not just statistical\n5.  **Report your analysis** - document all assumptions\n6.  **Don't do post-hoc power** for non-significant results\n7.  **Use confidence intervals** to show uncertainty\n8.  **Consider feasibility** - balance power with resources\n\n\n<!-- # Resources for power and sample size calculations -->\n\n<!-- ## Additional resources -->\n\n<!-- **R documentation:** -->\n\n<!-- -   `?pwr.t.test` - help for power calculations -->\n<!-- -   PASS documentation: <https://www.ncss.com/software/pass/pass-documentation/#Means> -->\n\n<!-- \\ -->\n\n<!-- **Interactive tools:** -->\n\n<!-- -   <https://rpsychologist.com/d3/NHST/> - Visualize power -->\n<!-- -   <https://www.statmethods.net/stats/power.html> - Power analysis examples -->\n\n<!-- \\ -->\n\n<!-- **Textbook:** -->\n\n<!-- -   Section 5.4: Power and Sample Size for means -->\n\n<!-- \\ -->\n\n<!-- **Further reading:** -->\n\n<!-- -   Cohen, J. (1988). *Statistical Power Analysis for the Behavioral Sciences* -->\n<!-- -   Lenth, R. V. (2001). \"Some Practical Guidelines for Effective Sample Size Determination\" -->\n\n\n# Resources for power and sample size calculations\n\n## More software for power and sample size calculations: PASS\n\n-   PASS is a very powerful (& expensive) software that does power and sample size calculations for many advanced statistical modeling techniques.\n    -   Even if you don't have access to PASS, their [documentation](https://www.ncss.com/software/pass/pass-documentation/) is very good and free online.\n    -   Documentation includes formulas and references.\n    -   PASS documentation for powering [means](https://www.ncss.com/software/pass/pass-documentation/#Means)\n        -   One mean, paired means, two independent means\n-   One-sample t-test documentation: <https://www.ncss.com/wp-content/themes/ncss/pdf/Procedures/PASS/One-Sample_T-Tests.pdf>\n\n## OCTRI-BERD power & sample size presentations\n\n::: {style=\"font-size: 90%;\"}\n-   **Power and Sample Size 101**\n    -   Presented by Meike Niederhausen; April 13, 2023\n    -   Slides: <http://bit.ly/PSS101-BERD-April2023>\n    -   [Recording](https://echo360.org/media/10f37fa6-7196-4525-bd64-6b9fcca60ac0/public)\n-   **Power and Sample Size for Clinical Trials: An Introduction**\n    -   Presented by Yiyi Chen; Feb 18, 2021\n    -   Slides: <http://bit.ly/PSS-ClinicalTrials>\n    -   [Recording](https://echo360.org/lesson/9a21deb8-258d-4305-bdc9-7effdc35e719/classroom)\n-   **Planning a Study with Power and Sample Size Considerations in Mind**\n    -   Presented by David Yanez; May 29, 2019\n    -   [Slides](https://www.ohsu.edu/sites/default/files/2019-12/PowerAndSampleSize_29MAY2019.pdf)\n    -   [Recording](https://echo360.org/lesson/44c9a3e9-b8ec-4042-84d8-4758cc779a1f/classroom)\n-   **Power and Sample Size Simulations in R**\n    -   Presented by Robin Baudier; Sept 21, 2023\n    -   [Slides](https://www.slideshare.net/ssuser84c78e/octri-pss-simulations-in-r-seminarpdf)\n    -   [Recording](https://echo360.org/media/12e6e603-13f9-4b50-bf76-787185acdfce/public)\n:::\n\n\n## Additional resources\n\n\\\n\n**Good paper**\n\n- [Sample size, power and effect size revisited: simplified and practical approaches in pre-clinical, clinical and laboratory studies (Serdar et al.)](https://pmc.ncbi.nlm.nih.gov/articles/PMC7745163/)\n\n\\ \n\n**Interactive tools:**\n\n-   [Understanding Statistical Power and Significance Testing](https://rpsychologist.com/d3/NHST/)\n\n\\\n\n**Free software:**\n\n-   [Sample size calculators from UCSF](https://sample-size.net/calculator-finder)\n-   [CRAB (Cancer Research and Biostatistics) Statistical Tools](https://stattools.crab.org/)\n-   [G*Power - free, open source power analysis software](https://stats.oarc.ucla.edu/other/gpower/)\n\n",
    "supporting": [
      "15_power_sample_size_4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}