{
  "hash": "5f8a345ff3d13090980d7ad8725c7291",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Chi-Squared Tests and Fisher's Exact Test\"\nsubtitle: \"Textbook Sections 8.3–8.4\"\nauthor: \"Emile Latour, Nicky Wakim, Meike Niederhausen\"\ndate: \"2026-02-25\"\ndate-format: long\nformat:\n  revealjs:\n    theme: \"../../assets/css/reveal-bmsc620_v5.scss\"\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"BMSC 620 | Chi-Squared Tests and Fisher's Exact Test\"\n    html-math-method: mathjax\n    chalkboard: true\n    header-includes: |\n      <style>\n      #wrap {\n        width: 1650px;\n        height: 900px;\n        margin: 0 auto;\n        overflow: hidden;\n        border: 1px solid #999;\n        border-radius: 8px;\n      }\n      #frame {\n        width: 1650px;\n        height: 900px;\n        border: 0;\n        zoom: 1.25;\n        -moz-transform: scale(1.25);\n        -moz-transform-origin: 0 0;\n      }\n      /* Make selected tables bigger in RevealJS slides (robust to flextable output) */\n      .reveal .tbl-big {\n        font-size: 28px !important;\n        /* center the output block inside the column */\n        display: flex;\n        justify-content: center;\n      \n        /* scale from center */\n        transform: scale(1.6);\n        transform-origin: top center;\n      }\n      .reveal .tbl-big table,\n      .reveal .tbl-big .flextable,\n      .reveal .tbl-big .flextable table {\n        font-size: 28px !important;\n      }\n      .reveal .tbl-big td,\n      .reveal .tbl-big th {\n        padding: 6px 10px !important;\n      }\n      </style>\nexecute:\n  echo: true\n  warning: false\n  message: false\n  freeze: auto\n---\n\n\n\n\n\n\n# Learning Objectives\n\nBy the end of today's lecture, you will be able to:\n\n1. Explain what a contingency table is and why we need the chi-squared test\n2. Calculate expected cell counts under the null hypothesis of independence\n3. Conduct a chi-squared test of association/independence using R\n4. Check the technical conditions for the chi-squared test\n5. Recognize when to use Fisher's exact test instead of the chi-squared test\n6. Conduct Fisher's exact test in R and interpret results\n\n## Roadmap for Today\n\n::::: columns\n::: {.column width=\"50%\"}\n**Part 1: From 2×2 Tables to Bigger Tables**\n\n- Extending two-proportion tests\n- What is a contingency table?\n- The motivating example: depression and physical activity\n- Setting up the hypotheses\n\n**Part 2: The Chi-Squared Test**\n\n- Concept: observed vs. expected counts\n- The chi-squared statistic\n- The chi-squared distribution and degrees of freedom\n- Assumptions / technical conditions\n:::\n\n::: {.column width=\"50%\"}\n**Part 3: Chi-Squared Test in Practice**\n\n- Walking through all 6 steps\n- Using `chisq.test()` in R\n- Extracting observed and expected counts\n- Writing a conclusion\n\n**Part 4: Fisher's Exact Test**\n\n- When chi-squared breaks down\n- The idea behind the exact test\n- Using `fisher.test()` in R\n- Chi-squared vs. Fisher's: how to decide\n:::\n:::::\n\n## Where we are in the course\n\nLast time we covered inference for **proportions**:\n\n\\\n\n| Day | Method | Question |\n|:---:|:------:|:---------|\n| 13 | One proportion test | Is the response rate different from 30%? |\n| 13 | Two proportion test | Do response rates differ between groups? |\n| **Today** | **Chi-squared test** | **Is there an association between two categorical variables?** |\n| **Today** | **Fisher's exact test** | **Same question, but with small samples** |\n\n\\\n\n**The key extension:** What if one or both variables has **more than 2 levels**? We can no longer rely on a simple difference in proportions — we need a new method.\n\n# Part 1: From 2×2 Tables to Bigger Tables\n\n## Why do we need something new?\n\nLast class, we tested whether two proportions are equal. For example:\n\n\\\n\n> **Is the proportion of melanoma patients who respond to immunotherapy the same in treatment A vs. treatment B?**\n\n\\\n\nThis works great when both variables are **binary** (two levels each). But what about:\n\n\\\n\n> **Is there an association between depression level (None / Several days / Most days) and physical activity (Yes / No)?**\n\n\\\n\nNow the depression variable has **3 levels** — we can't just take a difference in two proportions! We need a way to compare proportions across multiple groups simultaneously.\n\n## The motivating example: Depression and Physical Activity\n\n::: {.callout-note icon=\"false\"}\n## NHANES Data\n\nData from the National Health and Nutrition Examination Survey (NHANES), 2009–2012. A random sample of **400 US adults** (aged ≥ 18) with data on:\n\n- **`Depressed`**: Self-reported number of days feeling down, depressed, or hopeless — **None**, **Several** (days), or **Most** (days)\n- **`PhysActive`**: Whether the participant does moderate or vigorous physical activity — **Yes** or **No**\n\n**Research Question:** Is there an association between depression status and physical activity?\n:::\n\n\\\n\nThis is a **2-row × 3-column contingency table** (or 3×2, depending on how you arrange it).\n\n## The contingency table\n\nA **contingency table** shows the frequency distribution of two categorical variables simultaneously.\n\n\\\n\n\n::: {style=\"text-align: center;\"}\n**Physical Activity by Depression Status (n = 400)**\n:::\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|PA/Depression | None| Several| Most| Total|\n|:-------------|----:|-------:|----:|-----:|\n|Yes           |  199|      26|    1|   226|\n|No            |  115|      32|   27|   174|\n|Total         |  314|      58|   28|   400|\n\n\n:::\n:::\n\n\n\n\n\\\n\nEach cell tells us: **how many people had this combination of depression status and physical activity level?**\n\n## Creating the contingency table in R\n\n\\\n\n::::: columns\n::: {.column width=\"50%\"}\n**If you have individual-level (tidy) data:**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using janitor::tabyl()\nDepPA %>%\n  tabyl(PA, Depression)\n\n# Using base R table()\ntable(DepPA$PA, DepPA$Depression)\n```\n:::\n\n\n\n\n\\\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  PA None Several Most\n Yes  199      26    1\n  No  115      32   27\n```\n\n\n:::\n:::\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n**If you only have the summary counts:**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDepPA_mat <- matrix(\n  c(199, 26,  1,   # PhysActive = Yes\n    115, 32, 27),  # PhysActive = No\n  nrow = 2,\n  byrow = TRUE\n)\n\ndimnames(DepPA_mat) <- list(\n  PA         = c(\"Yes\", \"No\"),\n  Depression = c(\"None\", \"Several\", \"Most\")\n)\n\nDepPA_mat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Depression\nPA    None Several Most\n  Yes  199      26    1\n  No   115      32   27\n```\n\n\n:::\n:::\n\n\n\n:::\n:::::\n\n## Setting up the hypotheses\n\n::: {.callout-important icon=\"false\"}\n## Hypotheses for a Chi-Squared Test\n\nFor chi-squared tests, we **do not use symbols** (no $p_1 - p_2 = 0$). We always state hypotheses in words.\n\n\\\n\n**Two equivalent ways to write the hypotheses:**\n\n::: columns\n::: {.column width=\"50%\"}\n**Test of \"association\" wording:**\n\n- $H_0$: There is **no association** between the two variables\n- $H_A$: There is **an association** between the two variables\n:::\n\n::: {.column width=\"50%\"}\n**Test of \"independence\" wording:**\n\n- $H_0$: The two variables are **independent**\n- $H_A$: The two variables are **not independent**\n:::\n:::\n\n\n\\\n\nBoth wordings are correct — pick one and be consistent. **NOTE** The test is always two-sided.\n:::\n\n\\\n\n**For our example:** $H_0$: There is no association between depression status and physical activity level\n\n# Part 2: The Chi-Squared Test\n\n## The core idea: observed vs. expected counts\n\n::: {.callout-tip icon=\"false\"}\n## The Key Insight\n\nIf depression and physical activity are truly **independent** (i.e., $H_0$ is true), then knowing someone's depression status tells us **nothing** about whether they are physically active.\n\n\\\n\nIn that case, the proportion who are physically active should be the **same across all depression groups**.\n\n\\\n\nWe test this by asking: **how far do the observed counts deviate from what we'd expect if the variables were independent?**\n:::\n\n\\\n\n- **Observed counts** = what we actually see in the data\n- **Expected counts** = what we'd expect to see **if $H_0$ is true**\n\n<!-- ## Calculating expected counts -->\n\n<!-- Under independence, the probability of being in cell $(i, j)$ is: -->\n\n<!-- $$P(\\text{row } i \\cap \\text{col } j) = P(\\text{row } i) \\times P(\\text{col } j)$$ -->\n\n<!-- \\ -->\n\n<!-- So the **expected count** for cell $(i, j)$ is: -->\n\n<!-- $$E_{ij} = n \\times P(\\text{row } i) \\times P(\\text{col } j) = \\frac{(\\text{row } i \\text{ total}) \\times (\\text{col } j \\text{ total})}{\\text{table total}}$$ -->\n\n<!-- \\ -->\n\n<!-- **Example:** Expected count for PhysActive = Yes, Depression = Several: -->\n\n<!-- $$E = \\frac{(\\text{row total for Yes}) \\times (\\text{col total for Several})}{\\text{table total}} = \\frac{226 \\times 58}{400} = 32.77$$ -->\n\n## Calculating expected counts\n\n\\\n\nUnder independence, the probability of being in a given cell is just the product of the row and column probabilities. This leads to the expected count formula:\n\n$$E = \\frac{R \\times C}{N}$$\nwhere\n\n- $R$ is the marginal total for a given row\n- $C$ is the marginal total for a given column\n- $N$ is the grand total for the table\n\n\\\n\nExpected counts will sum to the same row and column (marginal) totals.\n\n\n\n## Observed vs. expected: side by side\n\n::::: columns\n::: {.column width=\"50%\"}\n**Observed counts:**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Observed\n\n|PA/Depression | None| Several| Most| Total|\n|:-------------|----:|-------:|----:|-----:|\n|Yes           |  199|      26|    1|   226|\n|No            |  115|      32|   27|   174|\n|Total         |  314|      58|   28|   400|\n\n\n:::\n:::\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n**Expected counts (if independent):**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Expected\n\n|PA/Depression |None   |Several |Most  |Total  |\n|:-------------|:------|:-------|:-----|:------|\n|Yes           |177.41 |32.77   |15.82 |226.00 |\n|No            |136.59 |25.23   |12.18 |174.00 |\n|Total         |314.00 |58.00   |28.00 |400.00 |\n\n\n:::\n:::\n\n\n\n:::\n:::::\n\n\\\n\n::: fragment\n**Example:** Expected count for PhysActive = Yes, Depression = Several:\n\n$$E = \\frac{(\\text{row total for Yes}) \\times (\\text{col total for Several})}{\\text{table total}} = \\frac{226 \\times 58}{400} = 32.77$$\n:::\n\n::: fragment\n::: {.callout-warning icon=\"false\"}\n## Notice\n\nLook at **Most** depression, PhysActive = **Yes**: observed = 1, expected = 15.82. That's a huge discrepancy! People with the most depression days are far less physically active than independence would predict.\n:::\n:::\n\n## Calculating expected counts in R\n\n<!-- ```{r} -->\n<!-- # Using the epitools package -->\n<!-- library(epitools) -->\n<!-- expected(DepPA_mat) -->\n<!-- ``` -->\n\n<!-- \\ -->\n\n<!-- Or, save the chi-squared test result and pull out the expected counts: -->\n\n<!-- ```{r} -->\n<!-- chisq_result <- chisq.test(DepPA_mat) -->\n<!-- chisq_result$expected -->\n<!-- ``` -->\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_table <- DepPA_mat\n\nrow_totals <- rowSums(observed_table)\ncol_totals <- colSums(observed_table)\ngrand_total <- sum(observed_table)\n\n# Calculate expected counts using the manual formula\nmanual_expected <- outer(row_totals, col_totals) / grand_total\n\n# View the manually calculated expected counts\nmanual_expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      None Several  Most\nYes 177.41   32.77 15.82\nNo  136.59   25.23 12.18\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\nThe `outer()` function in R computes the outer product of two vectors, which efficiently creates the matrix of `row_totals * col_totals` for all cells.\n\n## The chi-squared test statistic\n\nOnce we have observed and expected counts, the **test statistic** quantifies the total discrepancy:\n\n$$\\chi^2 = \\sum_{\\text{all cells}} \\frac{(O - E)^2}{E}$$\n\n\\\n\n- $O$ = observed count in a cell\n- $E$ = expected count in that cell\n- We sum this ratio over **all cells** in the table\n\n\\\n\n**Intuition:**\n\n- If $H_0$ is true → $O \\approx E$ → small $\\chi^2$\n- If $H_A$ is true → some $O$ are very different from $E$ → large $\\chi^2$\n- **Large $\\chi^2$ = evidence against $H_0$**\n\n## Why $(O - E)^2 / E$?\n\n\\\n$$\\chi^2 = \\sum_{\\text{all cells}} \\frac{(O - E)^2}{E}$$\n\n\\\n\n- Each term measures how far a cell is from what we'd expect under independence\n- We square the difference so that **positive and negative deviations don't cancel out**.\n- We divide by $E$ to **standardize** — a deviation of 10 matters more when the expected count is 12 than when it's 300.\n\n## $\\chi^2$ with depression/activity data\n\n\\\n\n**For our depression/physical activity data:**\n\n$$\\chi^2 = \\frac{(199 - 178.13)^2}{178.13} + \\frac{(26 - 32.77)^2}{32.77} + \\frac{(1 - 15.82)^2}{15.82} + \\cdots = 41.17$$\n\n\\\n\n\\\n\nIs $41.17$ large enough to reject $H_0$? We need to know what distribution this statistic follows!\n\n## The chi-squared distribution\n\nUnder $H_0$, the test statistic follows a **chi-squared distribution** with degrees of freedom:\n\n$$df = (\\text{\\# rows} - 1) \\times (\\text{\\# columns} - 1)$$\n\n\\\n\n::::: columns\n::: {.column width=\"55%\"}\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](17_chi_squared_fisher_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n\n:::\n\n::: {.column width=\"45%\"}\n**Key properties:**\n\n- Always **right-skewed**\n- Only takes **non-negative** values ($\\chi^2 \\geq 0$)\n- Shape depends entirely on **df**\n- As df increases, distribution becomes more symmetric\n\n\\\n\n**For our 2×3 table:**\n\n$$df = (2-1)(3-1) = 2$$\n\n\\\n\n**The p-value is always the area to the right of the observed $\\chi^2$** — it is always a one-sided, upper-tail test.\n:::\n:::::\n\n## P-value for the chi-squared test\n\n\\\n\nThe p-value is the area to the **right** of our test statistic:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](17_chi_squared_fisher_files/figure-revealjs/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate p-value manually\npchisq(abs(41.17), df = 2, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.148281e-09\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n## Technical conditions (assumptions)\n\n\\\n\nBefore running the chi-squared test, we need to check two conditions:\n\n::: {.callout-important icon=\"false\"}\n## Conditions for the Chi-Squared Test\n\n::: columns\n::: {.column width=\"50%\"}\n**1. Independence**\n\nEach observation must be independent. In practice:\n\n- Each person contributes to **exactly one cell** of the table\n- Observations are not paired or clustered (no repeated measures)\n:::\n::: {.column width=\"50%\"}\n**2. Sample size (expected counts)**\n\nThe chi-squared approximation is valid when:\n\n- **2×2 tables:** All expected counts ≥ 10\n- **Larger tables:** No more than 20% of expected counts < 5, **and** all expected counts ≥ 1\n:::\n:::\n\n\n\\\n\n**If these fail → use Fisher's exact test (Part 4)**\n:::\n\n# Part 3: Chi-Squared Test in Practice\n\n## The 6-step framework\n\n\\\n\nWe'll use our standard 6-step approach for hypothesis testing.\n\n\\\n\n**Our question:** Is there an association between depression status and physical activity among US adults?\n\n\\\n\n**Data:** Random sample of 400 US adults from NHANES 2009–2012\n\n\\\n\nLet's go through all 6 steps together.\n\n## From matrix to real data\n\n\\\nIn Part 2 we built `DepPA_mat` by hand to illustrate the concepts. \nIn practice, you always start from your actual dataset.\n\n\\\n\nBase R's `table()` produces the same result:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# These are equivalent\nDepPA_mat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Depression\nPA    None Several Most\n  Yes  199      26    1\n  No   115      32   27\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(DepPA$PA, DepPA$Depression)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n      None Several Most\n  Yes  199      26    1\n  No   115      32   27\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\nFor the 6 steps, we'll use `table()` on the real data — \nwhich is how you'll do it in your own analyses.\n\n## Step 1: State the hypotheses\n\n\\\n\n$H_0$: There is no association between depression status and physical activity\n\n$H_A$: There is an association between depression status and physical activity\n\n\\\n\n::: {.callout-note icon=\"false\"}\n## Note: No symbols needed\n\nUnlike tests for means or proportions, chi-squared hypotheses are **always stated in words**. There's no simple symbolic representation like $\\mu_1 = \\mu_2$ because we're simultaneously comparing proportions across multiple groups and levels.\n:::\n\n## Step 2: Set significance level\n\n$$\\alpha = 0.05$$\n\n## Step 3: Check assumptions\n\n**Independence:** Each person contributes to exactly one cell. A person \ncan't be both physically active and not physically active, and can't have \nboth \"None\" and \"Several\" depression days. ✓\n\n**Expected counts:**\n\nIn practice, I check expected counts *after* running the test — \n`chisq.test()` will warn you if expected counts are too small, and you \ncan pull them directly from the result object:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndep_pa_tab <- table(DepPA$PA, DepPA$Depression)\n\nchisq_result <- chisq.test(dep_pa_tab)\n\n# check what is stored in the result\nnames(chisq_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"statistic\" \"parameter\" \"p.value\"   \"method\"    \"data.name\" \"observed\" \n[7] \"expected\"  \"residuals\" \"stdres\"   \n```\n\n\n:::\n\n```{.r .cell-code}\n# Look at the expected counts\nchisq_result$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n        None Several  Most\n  Yes 177.41   32.77 15.82\n  No  136.59   25.23 12.18\n```\n\n\n:::\n:::\n\n\n\n\nAll expected counts > 5. The only borderline cell is PhysActive = Yes, \nDepression = Most (expected = 15.82), which easily passes. ✓\n\n\n\n## Step 4: Calculate the test statistic\n\n$$\\chi^2 = \\sum_{\\text{all cells}} \\frac{(O - E)^2}{E}$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq_result <- chisq.test(dep_pa_tab)\nchisq_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  dep_pa_tab\nX-squared = 41.171, df = 2, p-value = 1.148e-09\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n\\\n\nThe test statistic is $\\chi^2 = 41.17$ with $df = (2-1)(3-1) = 2$.\n\n## Step 5: Calculate the p-value\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq_result$statistic   # test statistic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nX-squared \n 41.17067 \n```\n\n\n:::\n\n```{.r .cell-code}\nchisq_result$parameter   # degrees of freedom\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndf \n 2 \n```\n\n\n:::\n\n```{.r .cell-code}\nchisq_result$p.value     # p-value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.147897e-09\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n- The p-value is essentially 0 (< 0.001). \n- This means: **if there were truly no association between depression and physical activity (the null hypothesis is true), the probability of observing data as extreme as ours (or more extreme) is less than 0.001.**\n\n## Step 6: Conclusion\n\nSince $p < 0.001 < \\alpha = 0.05$, we **reject $H_0$**.\n\n\\\n\n::: {.callout-tip icon=\"false\"}\n## Conclusion Statement\n\nBased on a random sample of 400 US adults from NHANES 2009–2012, there is very strong evidence of an association between depression status and physical activity level ($\\chi^2 = 41.17$, $df = 2$, $p < 0.001$).\n\nThose with more days of depression appear to be substantially less physically active than would be expected if the variables were independent.\n:::\n\n\\\n\n::: {.callout-warning icon=\"false\"}\n## Common mistake\n\nIf we fail to reject $H_0$, we do **NOT** say \"the variables are independent.\" We say: \"We have insufficient evidence of an association.\" Absence of evidence ≠ evidence of absence!\n:::\n\n## Base R: contingency table and expected counts\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make the table\ndep_pa_tab <- table(DepPA$PA, DepPA$Depression)\n\ndep_pa_tab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n      None Several Most\n  Yes  199      26    1\n  No   115      32   27\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run the test\nchisq_result <- chisq.test(dep_pa_tab)\n\n# Check expected counts\nchisq_result$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n        None Several  Most\n  Yes 177.41   32.77 15.82\n  No  136.59   25.23 12.18\n```\n\n\n:::\n:::\n\n\n\n\n## Base R: test result\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  dep_pa_tab\nX-squared = 41.171, df = 2, p-value = 1.148e-09\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq_result %>% \n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  statistic       p.value parameter method                    \n      <dbl>         <dbl>     <int> <chr>                     \n1      41.2 0.00000000115         2 Pearson's Chi-squared test\n```\n\n\n:::\n:::\n\n\n\n\n## janitor: contingency table and expected counts\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make the table\ndep_pa_tab_janitor <- DepPA %>%\n  tabyl(PA, Depression)\n\ndep_pa_tab_janitor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  PA None Several Most\n Yes  199      26    1\n  No  115      32   27\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run the test\nchisq_result_janitor <- dep_pa_tab_janitor %>% \n  chisq.test()\n\n# Check expected counts\nchisq_result_janitor$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  PA   None Several  Most\n Yes 177.41   32.77 15.82\n  No 136.59   25.23 12.18\n```\n\n\n:::\n:::\n\n\n\n\n## janitor: test result\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq_result_janitor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  .\nX-squared = 41.171, df = 2, p-value = 1.148e-09\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq_result_janitor %>% \n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  statistic       p.value parameter method                    \n      <dbl>         <dbl>     <int> <chr>                     \n1      41.2 0.00000000115         2 Pearson's Chi-squared test\n```\n\n\n:::\n:::\n\n\n\n\n## rstatix: contingency table and expected counts\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make the table\ndep_pa_tab <- table(DepPA$PA, DepPA$Depression)\n\ndep_pa_tab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n      None Several Most\n  Yes  199      26    1\n  No   115      32   27\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run the test\nchisq_result_rstatix <- dep_pa_tab %>% \n  rstatix::chisq_test()\n\n# Check expected counts\nchisq_result_janitor$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  PA   None Several  Most\n Yes 177.41   32.77 15.82\n  No 136.59   25.23 12.18\n```\n\n\n:::\n:::\n\n\n\n\n\n## rstatix: test result\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq_result_rstatix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n      n statistic             p    df method          p.signif\n* <int>     <dbl>         <dbl> <int> <chr>           <chr>   \n1   400      41.2 0.00000000115     2 Chi-square test ****    \n```\n\n\n:::\n:::\n\n\n\n\n::: {.callout-note icon=\"false\"}\n## Note\n`rstatix` returns a tidy data frame directly — no need for `broom::tidy()`.\n:::\n\n\n\n## Part 3: Summary\n\n- Chi-squared test asks: **do the observed counts match what we'd expect under independence?**\n- Use `table()` or `janitor::tabyl()` to build the contingency table\n- Use `chisq.test()`, `janitor::chisq.test()`, or `rstatix::chisq_test()` to run it\n- Always check `$expected` — if any expected counts are too small, use Fisher's exact test (Part 4)\n\n# Part 4: Fisher's Exact Test\n\n## When chi-squared breaks down\n\n\\\n\nThe chi-squared test relies on an **approximation** — the test statistic only follows the chi-squared distribution when the **expected counts are large enough**.\n\n\\\n\n**What happens when we have small samples?** Suppose instead of 400 adults, we had only **100** adults:\n\n\\\n\n::: {style=\"text-align: center;\"}\n**Physical Activity by Depression Status (n = 100)**\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|PA/Depression | None| Several| Most| Total|\n|:-------------|----:|-------:|----:|-----:|\n|Yes           |   43|       5|    2|    50|\n|No            |   40|       4|    6|    50|\n|Total         |   83|       9|    8|   100|\n\n\n:::\n:::\n\n\n\n\n\n## The chi-squared warning\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make the table\ndep_pa_tab <- table(DepPA100$PA, DepPA100$Depression)\n\n# Run the test\nchisq_res <- chisq.test(dep_pa_tab)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in stats::chisq.test(x, y, ...): Chi-squared approximation may be\nincorrect\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n::: {.callout-warning icon=\"false\"}\n## What does this warning mean?\n\nR tells us: *\"Chi-squared approximation may be incorrect.\"* The expected counts for the \"Most\" depression column are too small (< 5), violating our sample size condition. The chi-squared approximation can't be trusted here. **We need a different approach.**\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq_res$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n      None Several Most\n  Yes 41.5     4.5    4\n  No  41.5     4.5    4\n```\n\n\n:::\n:::\n\n\n\n\n\n## Fisher's Exact Test: the idea\n\n::: {.callout-note icon=\"false\"}\n## The Core Concept\n\nFisher's exact test computes the **exact probability** of observing our data (or data more extreme) given the **fixed row and column totals**.\n\n\\\n\nIt's called \"exact\" because instead of using an asymptotic approximation (like the chi-squared distribution), it computes the probability **exactly** using the **hypergeometric distribution** for $2 \\times 2$ case; multivariate hypergeometric distribution in $r \\times c$ case.\n\n\\\n\nThink of it this way: if the row and column totals are fixed, there's only a limited number of ways to fill in the cells. Fisher's test calculates how likely our observed arrangement is under $H_0$.\n:::\n\n\n## Key features of Fisher's exact test\n\n::: {.callout-important icon=\"false\"}\n## What's different about Fisher's exact test?\n\n1. **No test statistic** — the p-value is calculated directly from the data\n2. **No confidence interval** from the standard output (for tables larger than 2×2)\n3. **Always two-sided** — no option to specify direction of the alternative\n4. **No continuity correction** needed — the hypergeometric distribution is already discrete\n5. **Works for any sample size** — exact regardless of whether expected counts are small or large\n\n\\\n\n**When to use it:**\n\n- **2×2 tables:** Any expected count < 10\n- **Larger tables:** More than 20% of expected counts < 5, or any expected count < 1\n:::\n\n## Fisher's exact test in R\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher.test(dep_pa_tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  dep_pa_tab\np-value = 0.3844\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\nThe p-value of 0.384 provides no evidence of an association \nbetween depression and physical activity in this smaller sample \n(Fisher's exact test). We fail to reject $H_0$ at $\\alpha = 0.05$.\n\n\n\\\n\nNote: the larger sample (n = 400) gave very strong evidence of an association. With only n = 100, we don't have enough data to detect the association reliably — this is a **power** issue!\n\n## Base R: Fisher's exact test\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make the table\ndep_pa_tab100 <- table(DepPA100$PA, DepPA100$Depression)\ndep_pa_tab100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n      None Several Most\n  Yes   43       5    2\n  No    40       4    6\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run the test\nfisher_result <- fisher.test(dep_pa_tab100)\nfisher_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  dep_pa_tab100\np-value = 0.3844\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher_result %>% \n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  p.value method                             alternative\n    <dbl> <chr>                              <chr>      \n1   0.384 Fisher's Exact Test for Count Data two.sided  \n```\n\n\n:::\n:::\n\n\n\n\n## janitor: Fisher's exact test\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make the table\ndep_pa_tab100_janitor <- DepPA100 %>%\n  tabyl(PA, Depression)\ndep_pa_tab100_janitor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  PA None Several Most\n Yes   43       5    2\n  No   40       4    6\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run the test\nfisher_result_janitor <- dep_pa_tab100_janitor %>% \n  fisher.test()\n\nfisher_result_janitor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  .\np-value = 0.3844\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher_result_janitor %>% \n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  p.value method                             alternative\n    <dbl> <chr>                              <chr>      \n1   0.384 Fisher's Exact Test for Count Data two.sided  \n```\n\n\n:::\n:::\n\n\n\n\n## rstatix: Fisher's exact test\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make the table\ndep_pa_tab100 <- table(DepPA100$PA, DepPA100$Depression)\ndep_pa_tab100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n      None Several Most\n  Yes   43       5    2\n  No    40       4    6\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndep_pa_tab100 %>% \n  rstatix::fisher_test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n      n     p p.signif\n* <int> <dbl> <chr>   \n1   100 0.384 ns      \n```\n\n\n:::\n:::\n\n\n\n\n::: {.callout-note icon=\"false\"}\n## Note\n`rstatix` returns a tidy data frame directly — no need for `broom::tidy()`.\n:::\n\n## Another small-sample example\n\n::: {.callout-note icon=\"false\"}\n## Clinical Example: Adverse Events in a Cancer Drug Trial\n\nA pilot trial of 25 patients tests a new targeted therapy. Investigators are concerned about liver toxicity:\n\n|  | Elevated enzymes | Normal | Total |\n|:-:|:-:|:-:|:-:|\n| **Treated** | 5 | 8 | 13 |\n| **Control** | 1 | 11 | 12 |\n| **Total** | 6 | 19 | 25 |\n\nWith only 25 patients, expected counts in the \"Elevated enzymes\" column will be very small. Chi-squared is not appropriate here.\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nliver_mat <- matrix(\n  c(5,  8,\n    1, 11),\n  nrow = 2, byrow = TRUE,\n  dimnames = list(Group = c(\"Treated\", \"Control\"),\n                  Enzymes = c(\"Elevated\", \"Normal\"))\n)\n```\n:::\n\n\n\n\n## Interpreting the Fisher's exact test output\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher.test(liver_mat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  liver_mat\np-value = 0.1602\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n   0.5555821 353.2536123\nsample estimates:\nodds ratio \n  6.382758 \n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n- **p-value = 0.160** → No significant evidence of an association at $\\alpha = 0.05$\n- **Odds ratio = 6.4** → Treated patients have about 7 times the odds of elevated liver enzymes compared to control\n- **95% CI: (0.6 — 353.3)** → Extremely wide — the study is **underpowered** for detecting a difference\n\n\n::: {.callout-tip icon=\"false\"}\n## Takeaway\n\nWith only 25 patients, we lack the statistical power to detect even a potentially large effect. This study should be viewed as exploratory — not definitive. Larger trials are needed.\n:::\n\n## Chi-Squared vs. Fisher's Exact: how to decide\n\n\\\n\n| | Chi-Squared Test | Fisher's Exact Test |\n|:--|:--:|:--:|\n| When to use | Expected counts large enough | Expected counts too small |\n| **2×2 table** | All $E \\geq 10$ | Any $E < 10$ |\n| **Larger tables** | ≤ 20% of $E < 5$, all $E \\geq 1$ | > 20% of $E < 5$, or any $E < 1$ |\n| Test statistic | $\\chi^2$ | None |\n| Distribution | Chi-squared (approx.) | Hypergeometric (exact) |\n| Confidence interval | No (from test) | For 2×2 only |\n| One-sided available? | No | No |\n| R function | `chisq.test()` | `fisher.test()` |\n\n\\\n\n**Rule of thumb:** Always check expected counts first. If in doubt, Fisher's exact test is conservative and always valid — it just requires more computing time for large tables.\n\n## Bonus: simulated p-values for larger tables\n\nFor **large contingency tables** with small expected counts, `fisher.test()` can be slow. An alternative is to simulate the p-value using `chisq.test()`:\n\n- This randomly generates many tables with the same row/column totals and calculates what proportion have a $\\chi^2$ statistic as large as ours.\n- **B = 10000** means we simulate 10,000 random tables\n- Results will be slightly different each run (set a seed for reproducibility!)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(456)\nchisq.test(dep_pa_tab, simulate.p.value = TRUE, B = 10000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with simulated p-value (based on 10000\n\treplicates)\n\ndata:  dep_pa_tab\nX-squared = 2.2195, df = NA, p-value = 0.3817\n```\n\n\n:::\n:::\n\n\n\n\n\n\n# Summary and Key Takeaways\n\n## What we learned today\n\n**1. Chi-squared test of association**\n\n- Tests whether two categorical variables are associated (independent)\n- Compares **observed** vs. **expected** counts under independence\n- Expected count = $\\frac{\\text{row total} \\times \\text{column total}}{\\text{table total}}$\n- Test statistic: $\\chi^2 = \\sum \\frac{(O-E)^2}{E}$, with $df = (r-1)(c-1)$\n- Use `chisq.test()` in R\n- **Always check expected counts first!**\n\n\\\n\n**2. Fisher's exact test**\n\n- Use when expected counts are too small for chi-squared\n- Computes exact p-value using the hypergeometric distribution\n- No test statistic, no CI (for tables > 2×2), always two-sided\n- Use `fisher.test()` in R\n\n## Key decision: which test to use?\n\n\\\n\n::: {style=\"text-align: center;\"}\n**Decision workflow for categorical association tests**\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Step                                 |Action                         |\n|:------------------------------------|:------------------------------|\n|1. Create the contingency table      |tabyl() or table() or matrix() |\n|2. Calculate expected counts         |chisq.test()$expected          |\n|3a. Expected counts are large enough |→ Use chisq.test()             |\n|3b. Expected counts are too small    |→ Use fisher.test()            |\n\n\n:::\n:::\n",
    "supporting": [
      "17_chi_squared_fisher_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}