{
  "hash": "9c1adec66d6da07d1d0ec06a54bb7b69",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Odds & Ends: Multiple Linear Regression\"\nsubtitle: \"Categorical Predictors + Adjusting for Confounding\"\nauthor: \"Emile Latour\"\ndate: \"March 18, 2026\"\ndate-format: long\nformat:\n  revealjs:\n    theme: \"../../assets/css/reveal-bmsc620_v5.scss\"\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"BMSC 620 | Multiple Linear Regression\"\n    html-math-method: mathjax\n    chalkboard: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n  freeze: auto\n---\n\n\n\n\n\n# From SLR to Multiple Regression\n\n## Where we left off\n\n\\\n\n::::: columns\n::: {.column width=\"55%\"}\n\nIn the SLR lecture we asked:\n\n> **Does BMI predict systolic blood pressure?**\n\nWe fit:\n\n$$\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 \\cdot \\text{BMI}$$\n\n\\\n\nAnd found: for every 1 kg/m² increase in BMI, systolic BP is expected to increase by 0.70 mmHg on average.\n\n\\\n\nBut real biology is messier. **Multiple variables** are usually at play — age, sex, medications, comorbidities...\n\n:::\n\n::: {.column width=\"45%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](22_mlr_categorical_files/figure-revealjs/unnamed-chunk-1-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n:::\n:::::\n\n## Roadmap for Today\n\n\\\n\n::::: columns\n::: {.column width=\"50%\"}\n\n**Part 1: Categorical Predictors**\n\n- A new kind of explanatory variable\n- The binary categorical model\n- Connecting to what you already know\n- Interpreting output in R\n- Changing the reference category\n\n:::\n\n::: {.column width=\"50%\"}\n\n**Part 2: Multiple Linear Regression**\n\n- Adding predictors to the model\n- Confounding: why adjustment matters\n- Fitting MLR in R with `lm()`\n- Interpreting adjusted coefficients\n- $R^2$ and adjusted $R^2$\n- Unadjusted vs. adjusted: a side-by-side comparison\n\n:::\n:::::\n\n# Part 1: Categorical Predictors\n\n## A new question about blood pressure\n\n\\\n\nSo far, the explanatory variable has always been **continuous** (e.g., BMI, Age).\n\n\\\n\nWhat if the explanatory variable is **categorical**?\n\n\\\n\n::: {.callout-note icon=\"false\"}\n### New question\n\n**Does mean systolic blood pressure differ between males and females in the NHANES sample?**\n\n- Response $Y$: Systolic BP (continuous)\n- Explanatory $X$: Gender (categorical: female / male)\n:::\n\n\\\n\nYou might think: *\"I know how to do this — it's a two-sample t-test!\"* And you're right. But regression gives us a unified framework that extends naturally to multiple predictors.\n\n## Visualizing BP by gender\n\n::: columns\n::: {.column width=\"40%\"}\n\n\\\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ubjciswesn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ubjciswesn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ubjciswesn thead, #ubjciswesn tbody, #ubjciswesn tfoot, #ubjciswesn tr, #ubjciswesn td, #ubjciswesn th {\n  border-style: none;\n}\n\n#ubjciswesn p {\n  margin: 0;\n  padding: 0;\n}\n\n#ubjciswesn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 28px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ubjciswesn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ubjciswesn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ubjciswesn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ubjciswesn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ubjciswesn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ubjciswesn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ubjciswesn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ubjciswesn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ubjciswesn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ubjciswesn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ubjciswesn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ubjciswesn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ubjciswesn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ubjciswesn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ubjciswesn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ubjciswesn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ubjciswesn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ubjciswesn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ubjciswesn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ubjciswesn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ubjciswesn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ubjciswesn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ubjciswesn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ubjciswesn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ubjciswesn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ubjciswesn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ubjciswesn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ubjciswesn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ubjciswesn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ubjciswesn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ubjciswesn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ubjciswesn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ubjciswesn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ubjciswesn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ubjciswesn .gt_left {\n  text-align: left;\n}\n\n#ubjciswesn .gt_center {\n  text-align: center;\n}\n\n#ubjciswesn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ubjciswesn .gt_font_normal {\n  font-weight: normal;\n}\n\n#ubjciswesn .gt_font_bold {\n  font-weight: bold;\n}\n\n#ubjciswesn .gt_font_italic {\n  font-style: italic;\n}\n\n#ubjciswesn .gt_super {\n  font-size: 65%;\n}\n\n#ubjciswesn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ubjciswesn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ubjciswesn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ubjciswesn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ubjciswesn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ubjciswesn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ubjciswesn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ubjciswesn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ubjciswesn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Gender\">Gender</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean_bp\">Mean BP</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd_bp\">SD</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Gender\" class=\"gt_row gt_center\">female</td>\n<td headers=\"n\" class=\"gt_row gt_right\">78</td>\n<td headers=\"mean_bp\" class=\"gt_row gt_right\">116.3</td>\n<td headers=\"sd_bp\" class=\"gt_row gt_right\">18.4</td></tr>\n    <tr><td headers=\"Gender\" class=\"gt_row gt_center\">male</td>\n<td headers=\"n\" class=\"gt_row gt_right\">84</td>\n<td headers=\"mean_bp\" class=\"gt_row gt_right\">119.3</td>\n<td headers=\"sd_bp\" class=\"gt_row gt_right\">18.0</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\\\n\nMales have a slightly higher mean BP than females in this sample.\n\n:::\n::: {.column width=\"60%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](22_mlr_categorical_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n:::\n:::\n\n## The regression model with a binary categorical predictor\n\n\\\n\nFor a binary categorical variable, R creates an **indicator variable** (0/1) automatically:\n\n$$\\text{Gender}_{\\text{male}} = \\begin{cases} 1 & \\text{if male} \\\\ 0 & \\text{if female} \\end{cases}$$\n\n\\\n\nThe model becomes:\n\n$$E(\\text{BP}) = \\beta_0 + \\beta_1 \\cdot \\text{Gender}_{\\text{male}}$$\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n\n::: {.callout-note icon=\"false\"}\n### Intercept $\\hat{\\beta}_0$\nThe **estimated mean BP for females** — the group where $\\text{Gender}_{\\text{male}} = 0$.\n\nThis is the **reference category**.\n:::\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n::: {.callout-note icon=\"false\"}\n### Slope $\\hat{\\beta}_1$\nThe **estimated difference in mean BP** comparing males to females.\n\n$\\hat{\\beta}_1 = \\bar{Y}_{\\text{male}} - \\bar{Y}_{\\text{female}}$\n:::\n\n:::\n:::::\n\n## Running the model in R\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_cat <- lm(BPSys1 ~ Gender, data = nhanes_bp)\ntidy(model_cat, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term        estimate std.error statistic   p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n1 (Intercept)   116.        2.06     56.4  1.61e-107   112.      120.  \n2 Gendermale      3.00      2.86      1.05 2.96e-  1    -2.65      8.66\n```\n\n\n:::\n:::\n\n\n\n\\\n\n::: {.callout-important icon=\"false\"}\n### Interpretation\n\n- **Intercept** (116.3 mmHg): The estimated mean systolic BP for **females**.\n- **Gendermale** (3.0 mmHg): Males have, on average, a systolic BP that is 3.0 mmHg **higher** than females (95% CI: -2.7 to 8.7 mmHg).\n\nThe p-value (0.296) indicates this difference is statistically significant.\n:::\n\n## This is a t-test in disguise\n\n\\\n\n::: {.callout-tip icon=\"false\"}\n### Connecting to what you already know\n\nRunning `lm(BPSys1 ~ Gender)` with a binary predictor gives you the **same p-value** as a two-sample t-test (assuming equal variances).\n\nRegression is the more general framework — it lets us add more predictors, which a t-test cannot do.\n:::\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Two-sample t-test for comparison\nt.test(BPSys1 ~ Gender, data = nhanes_bp, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  BPSys1 by Gender\nt = -1.0485, df = 160, p-value = 0.296\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n95 percent confidence interval:\n -8.655674  2.652011\nsample estimates:\nmean in group female   mean in group male \n            116.3077             119.3095 \n```\n\n\n:::\n:::\n\n\n\n## Changing the reference category\n\n\\\n\nR chooses the reference category **alphabetically** — \"female\" comes before \"male\", so female is the reference.\n\n\\\n\nTo change it, use `relevel()`:\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnhanes_bp_male_ref <- nhanes_bp %>%\n  mutate(Gender = relevel(Gender, ref = \"male\"))\n\nlm(BPSys1 ~ Gender, data = nhanes_bp_male_ref) %>%\n  tidy(conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term         estimate std.error statistic   p.value conf.low conf.high\n  <chr>           <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n1 (Intercept)    119.        1.99     60.1  1.14e-111   115.      123.  \n2 Genderfemale    -3.00      2.86     -1.05 2.96e-  1    -8.66      2.65\n```\n\n\n:::\n:::\n\n\n\n\\\n\n::: {.callout-note icon=\"false\"}\nThe **estimate changes sign** but the **magnitude and p-value are identical** — we're just asking the question from the other direction. Use whichever reference group makes the most scientific sense.\n:::\n\n# Part 2: Multiple Linear Regression\n\n## Adding more predictors\n\n\\\n\nWe have two questions we'd like to answer simultaneously:\n\n- Is BMI associated with BP?\n- Is gender associated with BP?\n\n\\\n\n**And**: we know BMI and gender are themselves related — males tend to have different BMI distributions than females. This creates a problem called **confounding**.\n\n\\\n\nThe solution is to put both predictors in the same model:\n\n$$E(\\text{BP}) = \\beta_0 + \\beta_1 \\cdot \\text{BMI} + \\beta_2 \\cdot \\text{Gender}_{\\text{male}}$$\n\n\\\n\n::: {.callout-note icon=\"false\"}\n### Multiple linear regression (MLR)\nA regression model with **two or more** explanatory variables. Each coefficient describes the association between that predictor and the response, **holding the other predictors constant**.\n:::\n\n## What is confounding?\n\n\\\n\n::::: columns\n::: {.column width=\"55%\"}\n\nA **confounder** is a variable that is:\n\n1. Associated with the **explanatory variable** of interest\n2. Associated with the **response variable**\n3. Not on the causal pathway between them\n\n\\\n\n**Example here:** Gender is associated with both BMI and BP.\n\nIf we only look at BP ~ BMI, some of the apparent \"BMI effect\" is really a \"gender effect\" in disguise.\n\n\\\n\n::: {.callout-important icon=\"false\"}\n### Adjusting for confounding\nIncluding the confounder in the model lets us estimate the association between BMI and BP **among people of the same gender** — a fairer comparison.\n:::\n\n:::\n\n::: {.column width=\"45%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](22_mlr_categorical_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\n:::\n:::::\n\n## Fitting MLR in R\n\n\\\n\nThe syntax extends naturally from SLR — just add predictors with `+`:\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_mlr <- lm(BPSys1 ~ BMI + Gender, data = nhanes_bp)\ntidy(model_mlr, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  term        estimate std.error statistic  p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)   96.6       5.32      18.2  1.16e-40   86.1      107.  \n2 BMI            0.710     0.178      3.99 1.02e- 4    0.358      1.06\n3 Gendermale     3.58      2.74       1.31 1.93e- 1   -1.83       9.00\n```\n\n\n:::\n:::\n\n\n\n\\\n\n::: {.callout-note icon=\"false\"}\nR handles the categorical variable automatically. You do not need to create indicator variables by hand — just make sure `Gender` is a `factor`.\n:::\n\n## Interpreting the adjusted coefficients\n\n\\\n\n$$\\widehat{\\text{BP}} = \\hat{\\beta}_0 + \\hat{\\beta}_1 \\cdot \\text{BMI} + \\hat{\\beta}_2 \\cdot \\text{Gender}_{\\text{male}}$$\n\n\\\n\n::: {.callout-important icon=\"false\"}\n### Key rule: always say \"holding the other variables constant\"\n\n- **BMI** (0.71 mmHg): For every 1 kg/m² increase in BMI, systolic BP is expected to increase by 0.71 mmHg on average, **holding gender constant**.\n\n- **Gendermale** (3.58 mmHg): Males have, on average, a systolic BP that is 3.58 mmHg higher than females, **holding BMI constant** (i.e., comparing males and females at the same BMI).\n\n- **Intercept**: Expected mean BP for a **female** with BMI = 0. (Not a meaningful prediction — extrapolation.)\n:::\n\n## Unadjusted vs. adjusted: what changed?\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n\n::: {.callout-note icon=\"false\"}\n### Unadjusted (SLR): BP ~ BMI\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jnthpzjzkg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jnthpzjzkg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jnthpzjzkg thead, #jnthpzjzkg tbody, #jnthpzjzkg tfoot, #jnthpzjzkg tr, #jnthpzjzkg td, #jnthpzjzkg th {\n  border-style: none;\n}\n\n#jnthpzjzkg p {\n  margin: 0;\n  padding: 0;\n}\n\n#jnthpzjzkg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 26px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jnthpzjzkg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jnthpzjzkg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jnthpzjzkg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jnthpzjzkg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jnthpzjzkg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jnthpzjzkg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jnthpzjzkg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jnthpzjzkg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jnthpzjzkg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jnthpzjzkg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jnthpzjzkg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jnthpzjzkg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jnthpzjzkg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jnthpzjzkg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jnthpzjzkg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jnthpzjzkg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jnthpzjzkg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jnthpzjzkg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jnthpzjzkg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jnthpzjzkg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jnthpzjzkg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jnthpzjzkg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jnthpzjzkg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jnthpzjzkg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jnthpzjzkg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jnthpzjzkg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jnthpzjzkg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jnthpzjzkg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jnthpzjzkg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jnthpzjzkg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jnthpzjzkg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jnthpzjzkg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jnthpzjzkg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jnthpzjzkg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jnthpzjzkg .gt_left {\n  text-align: left;\n}\n\n#jnthpzjzkg .gt_center {\n  text-align: center;\n}\n\n#jnthpzjzkg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jnthpzjzkg .gt_font_normal {\n  font-weight: normal;\n}\n\n#jnthpzjzkg .gt_font_bold {\n  font-weight: bold;\n}\n\n#jnthpzjzkg .gt_font_italic {\n  font-style: italic;\n}\n\n#jnthpzjzkg .gt_super {\n  font-size: 65%;\n}\n\n#jnthpzjzkg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jnthpzjzkg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jnthpzjzkg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jnthpzjzkg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jnthpzjzkg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jnthpzjzkg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jnthpzjzkg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jnthpzjzkg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jnthpzjzkg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">Term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">Est.</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">Lower</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">Upper</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p-value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">98.83</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">88.85</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">108.81</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">< 0.001</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">BMI</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.70</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.35</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.05</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">< 0.001</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nBMI slope: **0.70** mmHg per kg/m²\n\n:::\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n::: {.callout-note icon=\"false\"}\n### Adjusted (MLR): BP ~ BMI + Gender\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"eonsxzvbnf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#eonsxzvbnf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#eonsxzvbnf thead, #eonsxzvbnf tbody, #eonsxzvbnf tfoot, #eonsxzvbnf tr, #eonsxzvbnf td, #eonsxzvbnf th {\n  border-style: none;\n}\n\n#eonsxzvbnf p {\n  margin: 0;\n  padding: 0;\n}\n\n#eonsxzvbnf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 26px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#eonsxzvbnf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#eonsxzvbnf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#eonsxzvbnf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#eonsxzvbnf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#eonsxzvbnf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eonsxzvbnf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#eonsxzvbnf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#eonsxzvbnf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#eonsxzvbnf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#eonsxzvbnf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#eonsxzvbnf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#eonsxzvbnf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#eonsxzvbnf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#eonsxzvbnf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#eonsxzvbnf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#eonsxzvbnf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#eonsxzvbnf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#eonsxzvbnf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eonsxzvbnf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#eonsxzvbnf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#eonsxzvbnf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#eonsxzvbnf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eonsxzvbnf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#eonsxzvbnf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#eonsxzvbnf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eonsxzvbnf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eonsxzvbnf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#eonsxzvbnf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eonsxzvbnf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#eonsxzvbnf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eonsxzvbnf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#eonsxzvbnf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eonsxzvbnf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#eonsxzvbnf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eonsxzvbnf .gt_left {\n  text-align: left;\n}\n\n#eonsxzvbnf .gt_center {\n  text-align: center;\n}\n\n#eonsxzvbnf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#eonsxzvbnf .gt_font_normal {\n  font-weight: normal;\n}\n\n#eonsxzvbnf .gt_font_bold {\n  font-weight: bold;\n}\n\n#eonsxzvbnf .gt_font_italic {\n  font-style: italic;\n}\n\n#eonsxzvbnf .gt_super {\n  font-size: 65%;\n}\n\n#eonsxzvbnf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#eonsxzvbnf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#eonsxzvbnf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#eonsxzvbnf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#eonsxzvbnf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#eonsxzvbnf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#eonsxzvbnf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#eonsxzvbnf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#eonsxzvbnf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">Term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">Est.</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">Lower</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">Upper</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p-value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">96.63</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">86.13</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">107.13</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">< 0.001</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">BMI</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.71</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.36</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.06</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">< 0.001</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">Gendermale</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">3.58</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−1.83</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">9.00</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.193</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nBMI slope: **0.71** mmHg per kg/m²\n\n:::\n\n:::\n:::::\n\n\\\n\n::: {.callout-tip icon=\"false\"}\nThe BMI coefficient changed slightly after adjusting for gender — a sign that gender was acting as a mild confounder. In some datasets, adjustment can dramatically change an estimate (or even flip its direction).\n:::\n\n## $R^2$ and adjusted $R^2$\n\n\\\n\nYou've seen $R^2$ as a measure of model fit. In MLR there's a wrinkle:\n\n\\\n\n::: {.callout-note icon=\"false\"}\n### $R^2$ always increases when you add predictors\n\nEven if the new predictor is noise, $R^2$ can only stay the same or go up. This makes it a poor tool for comparing models with different numbers of predictors.\n:::\n\n\\\n\n**Adjusted $R^2$** penalizes for the number of predictors:\n\n$$R^2_{\\text{adj}} = 1 - \\frac{(1-R^2)(n-1)}{n - p - 1}$$\n\nwhere $p$ = number of predictors. A new predictor only improves adjusted $R^2$ if it adds more than it costs.\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(model_mlr) %>% select(r.squared, adj.r.squared, sigma, nobs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  r.squared adj.r.squared sigma  nobs\n      <dbl>         <dbl> <dbl> <int>\n1    0.0970        0.0857  17.4   162\n```\n\n\n:::\n:::\n\n\n\n\\\n\nIn our model: $R^2$ = 0.097, adjusted $R^2$ = 0.086.\n\n## The MLR workflow\n\n\\\n\n::::: columns\n::: {.column width=\"45%\"}\n\n**1. Visualize**\n\n```r\nggplot(data, aes(x = X1, y = Y, color = X2)) +\n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n**2. Ensure categorical vars are factors**\n\n```r\ndata <- data %>%\n  mutate(X2 = factor(X2))\n```\n\n**3. Fit**\n\n```r\nmodel <- lm(Y ~ X1 + X2, data = data)\n```\n\n:::\n\n::: {.column width=\"3%\"}\n:::\n\n::: {.column width=\"52%\"}\n\n**4. Coefficients + inference**\n\n```r\ntidy(model, conf.int = TRUE)\n```\n\n**5. Model fit**\n\n```r\nglance(model)   # R², adj. R², sigma\n```\n\n**6. Change reference category (if needed)**\n\n```r\ndata <- data %>%\n  mutate(X2 = relevel(X2, ref = \"your_ref\"))\n```\n\n**7. Interpret everything as \"adjusted\"**\n\nEvery coefficient describes the association with $Y$ **holding all other predictors constant**.\n\n:::\n:::::\n\n## What we haven't covered (and where to go)\n\n\\\n\nMLR is a huge topic. Today's lecture gives you the foundation; there's much more in the textbook (Chapter 7) and beyond:\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n\n::: {.callout-note icon=\"false\"}\n### In your textbook (Ch. 7)\n- Categorical predictors with **3+ levels** (§7.5)\n- Model selection strategies (§7.8)\n- Interaction terms (§7.7)\n- Connection to ANOVA (§7.9)\n:::\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n::: {.callout-note icon=\"false\"}\n### Next steps in your training\n- **Logistic regression** — binary response (yes/no, alive/dead)\n- **Survival analysis** — time-to-event outcomes\n- **Mixed models** — correlated observations (more on this soon!)\n:::\n\n:::\n:::::\n",
    "supporting": [
      "22_mlr_categorical_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}