{
  "hash": "c4a4e289c6cbfd29869eaebd222c69b9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Comparing Means Across Groups\"\nsubtitle: \"Analysis of Variance (ANOVA)\"\nauthor: \"Emile Latour, Nicky Wakim, Meike Niederhausen\"\ndate: \"2026-03-04\"\ndate-format: long\nformat:\n  revealjs:\n    theme: \"../../assets/css/reveal-bmsc620_v5.scss\"\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"BMSC 620 | ANOVA\"\n    html-math-method: mathjax\n    chalkboard: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n  freeze: auto\n---\n\n\n\n\n\n# Learning Objectives\n\nBy the end of today's lecture, you will be able to:\n\n1. Explain why we cannot just run many pairwise t-tests when comparing 3 or more group means\n2. State the null and alternative hypotheses for a one-way ANOVA\n3. Interpret the components of an ANOVA table (SS, MS, F-statistic)\n4. Check the assumptions required for ANOVA\n5. Run a one-way ANOVA in R and interpret the output\n6. Explain the multiple comparisons problem and why post-hoc testing is needed\n7. Conduct and interpret Tukey HSD, Bonferroni, and FDR post-hoc tests in R\n\n## Roadmap for Today\n\n::::: columns\n::: {.column width=\"50%\"}\n**Part 1: Why Not Just Use More t-Tests?**\n\n- Extending our toolkit beyond two groups\n- The multiple comparisons problem\n- Introducing ANOVA\n\n**Part 2: The Logic of ANOVA**\n\n- The research question and data\n- Between-group vs. within-group variability\n- The F-statistic and F-distribution\n- Reading the ANOVA table\n:::\n\n::: {.column width=\"50%\"}\n**Part 3: Running ANOVA in R**\n\n- Checking assumptions\n- The six-step hypothesis test\n- Running `aov()` in R\n- Writing a complete conclusion\n\n**Part 4: Post-Hoc Comparisons**\n\n- Which groups are actually different?\n- Tukey's HSD\n- Bonferroni correction\n- False Discovery Rate (FDR)\n:::\n:::::\n\n# Part 1: Why Not Just Use More t-Tests?\n\n## Where we've been\n\n\\\n\nSo far our inference toolkit for **numerical outcomes** has been:\n\n\\\n\n| Lesson | Test | Groups |\n|---|---|:---:|\n| 9 | One-sample t-test | 1 |\n| 10 | Paired t-test | 2 (matched) |\n| 11 | Two-sample t-test | 2 (independent) |\n\n\\\n\n**Today's question:** What happens when we want to compare **3 or more** groups?\n\n\\\n\n::: {.callout-note icon=\"false\"}\n### The motivating question\n\nA genetics study wants to know: does ACTN3 genotype (CC, CT, or TT) affect how much arm strength changes after an exercise intervention?\n\nThat's **three groups** — we can't use a two-sample t-test anymore.\n:::\n\n## Why not just run three t-tests?\n\n\\\n\nWith 3 groups (CC, CT, TT), we could run every possible pairwise comparison:\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n\n**3 tests:**\n\n- CC vs. CT\n- CC vs. TT\n- CT vs. TT\n\n\\\n\nEach test has $\\alpha = 0.05$ probability of a Type I error.\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n**The problem:** With multiple tests, errors accumulate.\n\n$$P(\\text{at least one false positive}) = 1 - (1-\\alpha)^m$$\n\nFor $m = 3$ tests at $\\alpha = 0.05$:\n\n$$1 - (0.95)^3 = 0.143$$\n\nThat's a **14% chance** of at least one false positive — not 5%!\n\n:::\n:::::\n\n\\\n\n<!-- the (1-\\alpha)^m formula assumes independent tests, which pairwise t-tests on overlapping groups aren't — so the actual inflation can be even worse -->\n\n::: {.callout-important icon=\"false\"}\n### The multiple comparisons problem\n\nRunning many tests inflates the Type I error rate beyond the nominal $\\alpha$. We need a method that tests all groups simultaneously — that's ANOVA.\n:::\n\n## The multiple comparisons problem grows fast\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](19_anova_files/figure-revealjs/unnamed-chunk-1-1.png){fig-align='center' width=2400}\n:::\n:::\n\n\n\n**If we had 4 groups that's 6 tests → 19% chance of a false positive. ANOVA solves this by testing all groups in a single test.**\n\n# Part 2: The Logic of ANOVA\n\n## Motivating example: arm strength and genotype\n\n\\\n\n::: {.callout-note icon=\"false\"}\n### The FAMuSS Study\n\nThe **Functional SNPs Associated with Muscle Size and Strength** (FAMuSS) study investigated whether genetic variation is associated with exercise response.\n\n- **Participants:** ~600 young adults completed a resistance training program\n- **Genetic variable:** ACTN3 genotype at position R577X (CC, CT, or TT)\n- **Outcome:** Percent change in non-dominant arm strength after training\n\n**Question:** Is mean percent change in arm strength different across the three genotype groups?\n:::\n\n## Mean arms strength by genotype group\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(oibiostat)\ndata(\"famuss\")\n\nfamuss %>%\n  group_by(actn3.r577x) %>%\n  summarise(n = n(),\n            mean = round(mean(ndrm.ch), 1),\n            sd   = round(sd(ndrm.ch), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  actn3.r577x     n  mean    sd\n  <fct>       <int> <dbl> <dbl>\n1 CC            173  48.9  30  \n2 CT            261  53.2  33.2\n3 TT            161  58.1  35.7\n```\n\n\n:::\n:::\n\n\n\n## Visualizing the three groups\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](19_anova_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=2400}\n:::\n:::\n\n\n\nThe diamond ◆ marks the group mean. The dashed line is the grand mean across all participants. Do the groups look different enough to conclude a real effect?\n\n## The key question ANOVA asks\n\n\\\n\nWhether or not group means appear different depends on **two things**:\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n\n**1. How far apart are the group means?**\n\nIf the group means are close to the grand mean → not much going on.\n\nIf the group means are far from the grand mean → evidence of a real difference.\n\nThis is **between-group variability**.\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n**2. How much spread is there within each group?**\n\nIf observations are tightly clustered around their group mean → easy to tell groups apart.\n\nIf observations are widely scattered → hard to tell groups apart even if means differ.\n\nThis is **within-group variability**.\n\n:::\n:::::\n\n\\\n\n::: {.callout-tip icon=\"false\"}\n### ANOVA's insight\n\n- ANOVA compares these two sources of variability. \n- If between-group variability is large *relative to* within-group variability, that's evidence that the group means are genuinely different.\n:::\n\n## Three sources of variability — visually\n\n\\\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](19_anova_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=4200}\n:::\n:::\n\n\n\n$$\\underbrace{SST}_{\\text{Total}} = \\underbrace{SSG}_{\\text{Between groups}} + \\underbrace{SSE}_{\\text{Within groups}}$$\n\n## The ANOVA table\n\n\\\n\nANOVA organizes the variability into a table. $k =$ the number of groups and $N =$ the total number of observations across $k$ groups:\n\n\\\n\n::: {style=\"width: 80%; margin: 0 auto;\"}\n| Source | SS | df | MS | F |\n|---|---|---|---|---|\n| Between groups (Model) | SSG | $k-1$ | $MSG = SSG/(k-1)$ | $F = MSG/MSE$ |\n| Within groups (Error) | SSE | $N-k$ | $MSE = SSE/(N-k)$ | |\n| Total | SST | $N-1$ | | |\n:::\n\n\\\n\n::: {.callout-note icon=\"false\"}\n### Mean Squares: the key step\n\nDividing each SS by its degrees of freedom converts sums of squares into **mean squares** — averages of squared deviations. This puts between and within variability on the same scale so we can compare them with a ratio.\n\n$$F = \\frac{MSG}{MSE} = \\frac{\\text{between-group variability}}{\\text{within-group variability}}$$\n:::\n\n## The F-statistic\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n\n$F = \\frac{MSG}{MSE}$\n\n\\\n\n**When $H_0$ is true** (all means equal):\n\n- Between-group variability ≈ within-group variability\n- $F \\approx 1$\n\n**When $H_A$ is true** (at least one mean differs):\n\n- Between-group variability > within-group variability\n- $F > 1$, potentially much larger\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](19_anova_files/figure-revealjs/unnamed-chunk-5-1.png){width=2100}\n:::\n:::\n\n\n\n\n\n:::\n:::::\n\n\n::: {.callout-important icon=\"false\"}\nThe p-value for an F-test is **always the upper tail** — we only care about F being surprisingly large.\n:::\n\n# Part 3: Running ANOVA in R\n\n## Step 1: State hypotheses\n\n\\\n\n::: {.callout-important icon=\"false\"}\n### The ANOVA hypotheses\n\nThe null hypothesis for ANOVA is that **all** group means are equal:\n\n$$H_0: \\mu_{CC} = \\mu_{CT} = \\mu_{TT}$$\n\nThe alternative is that **at least one pair** of means differs:\n\n<!-- $$H_A: \\text{At least one pair } \\mu_i \\neq \\mu_j \\text{ for } i \\neq j$$ -->\n$$H_A: \\text{At least one mean differs from the others}$$\n:::\n\n\\\n\n::: {.callout-warning icon=\"false\"}\n### Common mistake\n\nPeople often write $H_A$ as \"all means are different.\" That is **wrong!**\n\n$H_A$ only requires that *at least one* group differs from at least one other. It could be that two groups are identical and a third is different — that still counts as $H_A$.\n:::\n\n## Step 1: State hypotheses — in words\n\n\\\n\n::::: columns\n::: {.column width=\"48%\"}\n\n**In symbols:**\n\n\\\n\n\n$$H_0: \\mu_{CC} = \\mu_{CT} = \\mu_{TT}$$\n\n<!-- $$H_A: \\text{At least one pair } \\mu_i \\neq \\mu_j$$ -->\n$$H_A: \\text{At least one mean differs from the others}$$\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n**In words:**\n\n\\\n\n\n$H_0$: The mean percent change in non-dominant arm strength is the same across all three ACTN3 genotype groups.\n\n$H_A$: The mean percent change in non-dominant arm strength differs for at least one pair of ACTN3 genotype groups.\n\n:::\n:::::\n\n\n\n## Step 2: Set significance level\n\n\\\n\nWe use the conventional significance level:\n\n$$\\alpha = 0.05$$\n\n## Step 3: Check assumptions\n\n\\\n\nThe F-statistic follows an F-distribution when these conditions hold:\n\n\\\n\n**1. Independence:** Observations within and across groups are independent\n\n- Met by design in FAMuSS (different participants in each group)\n\n\\\n\n**2. Normality within groups (or large samples):**\n\n- Each group should be approximately normally distributed, OR $n_i \\geq 30$ per group\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfamuss %>%\n  group_by(actn3.r577x) %>%\n  summarise(n = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  actn3.r577x     n\n  <fct>       <int>\n1 CC            173\n2 CT            261\n3 TT            161\n```\n\n\n:::\n:::\n\n\n\nAll groups have $n > 30$ ✓\n\n## Step 3: Check assumptions (continued)\n\n\\\n\n**3. Equal variance across groups (homoscedasticity):**\n\n- Within-group variability should be similar across groups\n- Rule of thumb: violated if $\\max(s_i) / \\min(s_i) > 2$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfamuss %>%\n  group_by(actn3.r577x) %>%\n  summarise(sd = sd(ndrm.ch)) %>%\n  summarise(ratio = max(sd) / min(sd))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  ratio\n  <dbl>\n1  1.19\n```\n\n\n:::\n:::\n\n\n\n\\\n\nRatio is close to 1 — equal variance assumption is reasonable ✓\n\n\n::: {.callout-tip icon=\"false\"}\nIf the equal variance assumption is seriously violated, Welch's ANOVA (`oneway.test(..., var.equal = FALSE)`) is a robust alternative that does not require equal variances.\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n## Steps 4–5: Calculate F-statistic and p-value\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the ANOVA model\nfamuss_aov <- aov(ndrm.ch ~ actn3.r577x, data = famuss)\n\n# View the ANOVA table\nsummary(famuss_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)  \nactn3.r577x   2   7043    3522   3.231 0.0402 *\nResiduals   592 645293    1090                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\\\n\n::: {.callout-note icon=\"false\"}\n### Reading the output\n\n- `actn3.r577x` row = **between-group** (model) variability\n- `Residuals` row = **within-group** (error) variability\n- `F value` = MSG / MSE\n- `Pr(>F)` = p-value (upper tail of F-distribution)\n:::\n\n## Steps 4–5: Tidy output with `broom`\n\n\\\n\nFor inline reporting or downstream use, `tidy()` from the `broom` package converts the ANOVA table to a data frame:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfamuss_aov %>%\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  term           df   sumsq meansq statistic p.value\n  <chr>       <dbl>   <dbl>  <dbl>     <dbl>   <dbl>\n1 actn3.r577x     2   7043.  3522.      3.23  0.0402\n2 Residuals     592 645293.  1090.     NA    NA     \n```\n\n\n:::\n:::\n\n\n\n\\\n\nPull the p-value for inline reporting:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfamuss_aov %>%\n  tidy() %>%\n  filter(term == \"actn3.r577x\") %>%\n  pull(p.value) %>%    # From dplyr package. Extract (\"pull\") a single column \n  round(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0402\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n## Step 6: Conclusion\n\n\\\n\n\n\n::: {.cell}\n\n:::\n\n\n\nRecall our hypotheses:\n\n$$H_0: \\mu_{CC} = \\mu_{CT} = \\mu_{TT} \\qquad \\text{vs.} \\qquad H_A: \\text{At least one mean differs from the others}$$\n\n\\\n\nWith $F$ = 3.23, $df$ = (2, 592), *p* = 0.040, and $\\alpha = 0.05$: We **reject $H_0$**.\n\n\\\n\n::: {.callout-important icon=\"false\"}\n### Conclusion\n\nThere is sufficient evidence that the mean percent change in non-dominant arm strength differs for at least one pair of ACTN3 genotype groups ($F$ = 3.23, $df$ = 2, 592, *p* = 0.040).\n\nDescriptively, mean arm strength change was 48.9% (SD = 30.0%) for CC, 53.2% (SD = 33.2%) for CT, and 58.1% (SD = 35.7%) for TT.\n:::\n\n## What ANOVA tells us — and what it doesn't (1/2)\n\n\\\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](19_anova_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=2400}\n:::\n:::\n\n\n\n## What ANOVA tells us — and what it doesn't (2/2)\n\n\\\n\n::: {.callout-warning icon=\"false\"}\n### A critical limitation\n\nANOVA tells us that **at least one pair** of means differs. It does **not** tell us:\n\n- Which specific groups are different from which\n- How many pairs differ\n- The direction or magnitude of the differences\n\nAfter a significant ANOVA, we need **post-hoc tests** to identify where the differences lie.\n:::\n\n\n\n\n# Part 4: Post-Hoc Comparisons\n\n## The multiple comparisons problem, revisited\n\n\\\n\nAfter a significant ANOVA, we want to test all pairwise comparisons. With $k = 3$ groups:\n\n$${3 \\choose 2} = 3 \\text{ pairwise tests: CC vs. CT, CC vs. TT, CT vs. TT}$$\n\n\\\n\nIf we just ran three regular t-tests at $\\alpha = 0.05$:\n\n$$P(\\text{at least one false positive}) = 1 - (0.95)^3 = 0.143$$\n\n\\\n\n**Post-hoc methods control this inflated error rate** through different strategies — each with different tradeoffs between Type I and Type II error.\n\n## Post-hoc comparisons with `rstatix`\n\n\\\n\nThe `rstatix` package provides tidy post-hoc testing:\n\n\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Tukey HSD — controls family-wise error rate\nfamuss %>%\n  tukey_hsd(ndrm.ch ~ actn3.r577x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  term  group1 group2 null.value estimate conf.low conf.high  p.adj p.adj.signif\n* <chr> <chr>  <chr>       <dbl>    <dbl>    <dbl>     <dbl>  <dbl> <chr>       \n1 actn… CC     CT              0     4.35   -3.25       12.0 0.371  ns          \n2 actn… CC     TT              0     9.19    0.695      17.7 0.0303 *           \n3 actn… CT     TT              0     4.83   -2.94       12.6 0.31   ns          \n```\n\n\n:::\n:::\n\n\n\n## Tukey's Honest Significant Difference (HSD)\n\n\\\n\n::::: columns\n::: {.column width=\"55%\"}\n\n**What it does:**\n\n- Controls the **family-wise error rate** (FWER) — the probability of making *any* false positive across all comparisons\n- Compares all pairwise differences simultaneously\n- Reports both adjusted p-values and confidence intervals for each difference\n- **The standard choice for ANOVA post-hoc testing**\n\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"40%\"}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](19_anova_files/figure-revealjs/unnamed-chunk-15-1.png){width=1800}\n:::\n:::\n\n\n\n:::\n:::::\n\nWhich comparison is driving the significant ANOVA result?\n\n## Bonferroni correction\n\n\n**Strategy:** Divide $\\alpha$ by the number of tests: $\\alpha_{Bonf} = \\alpha / m$\n\nEquivalently, multiply each p-value by $m$ and compare to $\\alpha$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bonferroni correction\nfamuss %>%\n  rstatix::pairwise_t_test(ndrm.ch ~ actn3.r577x,\n                           p.adjust.method = \"bonferroni\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  .y.     group1 group2    n1    n2      p p.signif  p.adj p.adj.signif\n* <chr>   <chr>  <chr>  <int> <int>  <dbl> <chr>     <dbl> <chr>       \n1 ndrm.ch CC     CT       173   261 0.179  ns       0.537  ns          \n2 ndrm.ch CC     TT       173   161 0.0113 *        0.0338 *           \n3 ndrm.ch CT     TT       261   161 0.144  ns       0.433  ns          \n```\n\n\n:::\n:::\n\n\n\n\\\n\n::: {.callout-note icon=\"false\"}\n### Bonferroni: pros and cons\n\n**Pro:** Simple, transparent, very conservative (strong Type I error control)\n\n**Con:** Loses power quickly as the number of comparisons grows — becomes hard to detect real differences\n\nBonferroni is best when you have a small number of *a priori* comparisons you care about.\n:::\n\n## False Discovery Rate (FDR)\n\n\\\n\n**Strategy:** Control the *expected proportion* of false positives among significant results, rather than the probability of *any* false positive.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Benjamini-Hochberg FDR\nfamuss %>%\n  rstatix::pairwise_t_test(ndrm.ch ~ actn3.r577x,\n                           p.adjust.method = \"fdr\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  .y.     group1 group2    n1    n2      p p.signif  p.adj p.adj.signif\n* <chr>   <chr>  <chr>  <int> <int>  <dbl> <chr>     <dbl> <chr>       \n1 ndrm.ch CC     CT       173   261 0.179  ns       0.179  ns          \n2 ndrm.ch CC     TT       173   161 0.0113 *        0.0338 *           \n3 ndrm.ch CT     TT       261   161 0.144  ns       0.179  ns          \n```\n\n\n:::\n:::\n\n\n\n\\\n\n::: {.callout-note icon=\"false\"}\n### FDR: pros and cons\n\n**Pro:** More powerful than Bonferroni or Tukey when there are many comparisons — allows more discoveries\n\n**Con:** Some false positives are tolerated (you control the *rate*, not the *occurrence*)\n\nFDR is especially popular in genomics and omics where hundreds or thousands of tests are run simultaneously.\n:::\n\n## Comparing the three approaches\n\n\\\n\n| Method | Controls | Best used when | Conservativeness |\n|---|---|---|:---:|\n| **Tukey HSD** | Family-wise error rate | Post-ANOVA pairwise comparisons | Moderate |\n| **Bonferroni** | Family-wise error rate | Few *a priori* comparisons | High |\n| **FDR** | False discovery rate | Many simultaneous tests | Low |\n\n\\\n\n::: {.callout-tip icon=\"false\"}\n### Rule of thumb for BMSC 620\n\nFor ANOVA post-hoc testing in a standard biomedical study: **Tukey HSD** is your default.\n\nUse Bonferroni when you have a small number of planned comparisons stated *before* looking at the data.\n\nUse FDR when you're doing many tests (e.g., comparing gene expression across dozens of groups).\n:::\n\n## Visualizing post-hoc results (1/2)\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Add significance brackets to a boxplot using rstatix + ggpubr\nlibrary(ggpubr)\n\ntukey_results <- famuss %>%\n  rstatix::tukey_hsd(ndrm.ch ~ actn3.r577x) %>%\n  rstatix::add_xy_position(x = \"actn3.r577x\")\n\nggpubr::ggboxplot(famuss, x = \"actn3.r577x\", y = \"ndrm.ch\",\n                  color = \"actn3.r577x\",\n                  width = 0.5, \n                  palette = c(\"#E69F00\", \"#0072B2\", \"#009E73\"),\n                  add = \"jitter\", add.params = list(alpha = 0.3)) +\n  ggpubr::stat_pvalue_manual(tukey_results, hide.ns = TRUE) +\n  labs(title = \"Percent change in arm strength by ACTN3 genotype\",\n       subtitle = \"Tukey HSD post-hoc comparisons (significant pairs shown)\",\n       x = \"ACTN3 genotype\",\n       y = \"Percent change in arm strength (%)\",\n       color = \"Genotype\")\n```\n:::\n\n\n\n## Visualizing post-hoc results (2/2)\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](19_anova_files/figure-revealjs/unnamed-chunk-19-1.png){fig-align='center' width=1800}\n:::\n:::\n\n\n\n## Putting it all together: full reporting\n\n\\\n\nA complete report of this analysis would include:\n\n\\\n\n::: {.callout-important icon=\"false\"}\n### Example write-up\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nMean percent change in non-dominant arm strength was 48.9% (SD = 30.0%) for CC, 53.2% (SD = 33.2%) for CT, and 58.1% (SD = 35.7%) for TT genotype groups. A one-way ANOVA indicated a statistically significant difference in mean arm strength change across genotype groups ($F$(2, 592) = 3.23, *p* = 0.040).\n\nPost-hoc comparisons using Tukey's HSD revealed that the TT group had significantly greater mean arm strength change than the CC group (difference = 9.2 percentage points, 95% CI: 0.7 to 17.7, adjusted *p* = 0.030). No significant differences were found between the CC and CT groups (adjusted *p* = 0.371) or the CT and TT groups (adjusted p = 0.310).\n:::\n\n\\\n\nNote what's included: group-level descriptive statistics, the F-statistic with both df values, the p-value, and specific post-hoc results with effect sizes and CIs.\n\n# Wrap-Up\n\n## ANOVA summary\n\n::::: columns\n::: {.column width=\"48%\"}\n\n**When to use ANOVA:**\n\n- Continuous outcome\n- 3 or more independent groups\n- Groups are independent of each other\n\n\\\n\n**The hypotheses:**\n\n$$H_0: \\mu_1 = \\mu_2 = \\cdots = \\mu_k$$\n<!-- $$H_A: \\text{at least one pair } \\mu_i \\neq \\mu_j$$ -->\n$$H_A: \\text{At least one mean differs from the others}$$\n\n\n\\\n\n**Key assumption to check:**\n\n- Similar within-group SDs ($SD_{max} / SD_{min}$ ratio < 2)\n- $n \\geq 30$ per group or approximate normality\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n**R workflow:**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Check assumptions\nfamuss %>%\n  group_by(actn3.r577x) %>%\n  summarise(n = n(), sd = sd(ndrm.ch))\n\n# 2. Fit ANOVA\nfamuss_aov <- aov(ndrm.ch ~ actn3.r577x,\n                  data = famuss)\nsummary(famuss_aov)\n\n# 3. Post-hoc (if significant)\nfamuss %>%\n  tukey_hsd(ndrm.ch ~ actn3.r577x)\n```\n:::\n\n\n\n\n**Post-hoc methods:**\n\n| Method | Use when |\n|---|---|\n| `tukey_hsd()` | Default for ANOVA |\n| `rstatix::pairwise_t_test` |  |\n| `p.adjust = \"bonferroni\"` | Few planned comparisons |\n| `p.adjust = \"fdr\"` | Many tests |\n\n:::\n:::::\n\n## Connecting to what's next\n\n\\\n\n**Lesson 17 (Monday):** Nonparametric tests\n\n- What if the normality assumption is violated *and* sample sizes are small?\n- Mann-Whitney U, Kruskal-Wallis — the nonparametric analogues to the t-test and ANOVA\n\n\\\n\n**Lesson 18 (Wednesday):** Correlation and Simple Linear Regression\n\n- What if both variables are continuous?\n- Extending beyond group comparisons to relationships between variables\n- ANOVA is actually a special case of regression — we'll see the connection\n\n\\\n\n::: {.callout-tip icon=\"false\"}\n### The big picture\n\nANOVA, t-tests, and linear regression are all part of the same family. The F-test in ANOVA and the t-test are mathematically related — in fact, for $k = 2$ groups, $F = t^2$. \n:::\n",
    "supporting": [
      "19_anova_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}