{
  "hash": "2fe6a93da87ab3cc444b58916b2519e3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Midterm Review\"\nsubtitle: \"Key Concepts from Lessons 1–9\"\nauthor: \"Emile Latour\"\ndate: \"2026-02-11\"\nformat:\n  revealjs:\n    theme: \"../../assets/css/reveal-bmsc620_v5.scss\"\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"BMSC 620 | Midterm Review\"\n    html-math-method: mathjax\n    chalkboard: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n  freeze: auto\n---\n\n\n\n\n\n\n## Today's Agenda\n\n- Quick overview of exam structure\n- Key concepts review\n  - Study design\n  - Probability and Bayes' Theorem\n  - Distributions (focus on R functions!)\n  - Sampling distributions and CLT\n  - Confidence intervals\n  - Hypothesis testing\n- Your questions\n\n\\\n\n**The midterm opens TODAY at 3:00 PM and closes Monday at 11:00 PM**\n\n\n# Exam Logistics\n\n## Exam Details\n\n**Format:**\n\n- 8 parts, 120 points total\n- Designed for 3-5 hours completion\n- Mix of conceptual questions, R code, and interpretation\n\n\\\n\n**Resources allowed:**\n\n- ✅ Course materials (slides, homework, textbook)\n- ✅ R documentation\n- ✅ Your notes\n- ❌ Other students\n- ❌ AI assistants\n- ❌ Online help forums\n\n\\\n\n**Submit both `.qmd` and `.html` files!**\n\n## What's Covered\n\n::::: columns\n::: {.column width=\"48%\"}\n**Part 1:** Study design (10 pts)\n\n**Part 2:** Descriptive stats & viz (15 pts)\n\n**Part 3:** Probability (15 pts)\n\n**Part 4:** Distributions (20 pts)\n:::\n\n::: {.column width=\"48%\"}\n**Part 5:** Sampling distributions & CLT (15 pts)\n\n**Part 6:** Confidence intervals (15 pts)\n\n**Part 7:** Hypothesis testing (20 pts)\n\n**Part 8:** Integration (10 pts)\n:::\n:::::\n\n\\\n\n**Key datasets:** `nhanes.samp` (you've used this in HW!)\n\n## General Tips\n\n\\\n\n::: columns\n::: {.column width=\"50%\"}\n**Before you start:**\n\n- Read all instructions carefully\n- Set up your workspace (load packages, data)\n- Check that code chunks run\n\n\\\n\n**While working:**\n\n- Show your work and reasoning\n- Provide interpretations in complete sentences\n- Use comments in your R code\n- Check that your document renders frequently\n- **Save regularly**\n:::\n\n::: {.column width=\"50%\"}\n**Before submitting:**\n\n- Render one final time\n- Check that all answers are complete\n- Verify both files are being submitted\n:::\n:::\n\n\n\n# Quick Concepts Review\n\n## Study Design: The Basics\n\n\\\n\n**Experiments vs. Observational Studies**\n\n::::: columns\n::: {.column width=\"48%\"}\n**Experiment:**\n\n- Researchers assign treatments\n- Random assignment\n- Can establish causation\n- Example: Drug trial with treatment vs. placebo\n:::\n\n::: {.column width=\"48%\"}\n**Observational Study:**\n\n- Researchers observe without interfering\n- No random assignment\n- Can only show association\n- Example: Reviewing medical records\n:::\n:::::\n\n\\\n\n**Why does this matter?**\n\nOnly randomized experiments can establish causal relationships!\n\n## Sampling Concepts\n\n\\\n\n**Key terms:**\n\n- **Population** vs. **Sample**\n- **Simple random sample** (each individual has equal chance)\n- **Convenience sample** (easily accessible - often biased)\n\n\\\n\n**Confounding variables:**\n\n- Associated with both explanatory and response variables\n- Can make it look like there's a causal relationship when there isn't\n- Example: Exercise and cardiovascular health might both be related to socioeconomic status\n\n# R Skills Review: Data Wrangling & Visualization\n\n## dplyr: The grammar of data manipulation\n\n`dplyr` provides a consistent set of **verbs** for data manipulation:\n\n\\\n\n| Function | What it does |\n|----------|-------------|\n| `filter()` | Keep rows that meet conditions |\n| `select()` | Keep or drop columns |\n| `mutate()` | Create or modify columns |\n| `arrange()` | Sort rows |\n| `group_by()` | Group data for summaries |\n| `summarize()` | Calculate summary statistics |\n\n\\\n\nThese verbs can be chained together with `%>%` for powerful data transformations.\n\n## ggplot2: The Basic Template\n\n::: {.callout-tip icon=\"false\"}\n## The ggplot2 pattern\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(data = dataset, \n       aes(x = variable, y = variable)) +\n  geom_*() +                    # Choose your geometry\n  labs(title = \"...\",           # Add labels\n       x = \"...\", \n       y = \"...\")\n```\n:::\n\n\n\n:::\n\n\\\n\n**Key geoms you need to know:**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram (one continuous variable)\ngeom_histogram(bins = 20)\n\n# Boxplot (continuous by categorical)\ngeom_boxplot()\n\n# Scatterplot (two continuous variables)\ngeom_point()\n```\n:::\n\n\n\n\n## ggplot2: Example\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(oibiostat)\ndata(\"nhanes.samp\")\n\n# Histogram\nggplot(nhanes.samp, aes(x = Height)) +\n  geom_histogram(bins = 20) +\n  labs(title = \"Distribution of Height\",\n       x = \"Height (cm)\",\n       y = \"Count\")\n\n# Boxplot by group\nggplot(nhanes.samp, \n       aes(x = Gender, y = Weight, fill = Gender)) +\n  geom_boxplot() +\n  labs(title = \"Weight by Gender\",\n       x = \"Gender\",\n       y = \"Weight (kg)\")\n```\n:::\n\n\n\n\n\\\n\n**Remember:** Start with `ggplot()`, then add layers with `+`\n\n## dplyr + rstatix: Summary Statistics\n\n::: {.callout-tip icon=\"false\"}\n## The pattern: group_by() then summarize\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(rstatix)\n\ndataset %>%\n  group_by(grouping_variable) %>%\n  get_summary_stats(numeric_variable, type = \"mean_sd\")\n```\n:::\n\n\n\n:::\n\n\\\n\n**Example:**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summary stats by one group\nnhanes.samp %>%\n  group_by(Gender) %>%\n  get_summary_stats(Height, type = \"mean_sd\")\n\n# Summary stats by multiple groups\nnhanes.samp %>%\n  group_by(Gender, SmokeNow) %>%\n  get_summary_stats(Weight, type = \"mean_sd\")\n```\n:::\n\n\n\n\n## dplyr only: Summary Statistics\n\n::: {.callout-tip icon=\"false\"}\n## The pattern: group_by() then summarize\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\ndataset %>%\n  group_by(grouping_variable) %>%\n  summarise(...)\n```\n:::\n\n\n\n:::\n\n\n**Example:**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summary stats by one group\nnhanes.samp %>%\n  group_by(Gender) %>%\n  summarise(n = sum(!is.na(Height)), \n            mean = mean(Height, na.rm = TRUE), \n            sd = sd(Height, na.rm = TRUE))\n\n# Summary stats by multiple groups\nnhanes.samp %>%\n  group_by(Gender, SmokeNow) %>%\n  summarise(n = sum(!is.na(Weight)), \n            mean = mean(Weight, na.rm = TRUE), \n            sd = sd(Weight, na.rm = TRUE))\n```\n:::\n\n\n\n\n## Categorical Data: janitor::tabyl()\n\n::: {.callout-tip icon=\"false\"}\n## The pattern for frequency tables\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(janitor)\n\n# One-way table\ndataset %>%\n  tabyl(variable)\n\n# Two-way table with row percentages\ndataset %>%\n  tabyl(row_variable, column_variable) %>%\n  adorn_totals(where = \"row\") %>% \n  adorn_percentages(\"row\") %>%\n  adorn_pct_formatting(digits = 1)\n```\n:::\n\n\n\n:::\n\n**Example:**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Two-way table\nnhanes.samp %>%\n  tabyl(Gender, SmokeNow) %>%\n  adorn_totals(where = \"row\") %>% \n  adorn_percentages(\"row\") %>%\n  adorn_pct_formatting(digits = 1) %>%\n  adorn_ns()\n```\n:::\n\n\n\n\n\n\n# Probability\n\n## Probability Notation Quick Reference\n\n**Basic probabilities:**\n\n- **Marginal:** $P(A)$ - probability of $A$ alone\n- **Joint:** $P(A \\text{ and } B)$ - probability of both\n- **Conditional:** $P(A \\mid B)$ - probability of $A$ given $B$\n\n\\\n\n**Key formula:**\n\n$$P(A \\mid B) = \\frac{P(A \\text{ and } B)}{P(B)}$$\n\n\\\n\n**Independence:**\n\nEvents $A$ and $B$ are independent if: $P(A \\text{ and } B) = P(A) \\times P(B)$\n\n## Probability Rules to Remember\n\n**General Addition Rule:**\n\nIf $A$ and $B$ are any two events:\n\n$$P(A \\text{ or } B) = P(A) + P(B) - P(A \\text{ and } B)$$\n\nWe subtract $P(A \\text{ and } B)$ because those outcomes were counted twice.\n\n\\\n\n**General Multiplication Rule:**\n\n$$P(A \\text{ and } B) = P(A \\mid B) \\times P(B)$$\n\nThis connects **joint** and **conditional** probabilities, and leads directly to Bayes' Theorem!\n\n\\\n\n::: {.callout-tip icon=\"false\"}\n## Special case: Independent events\n\nIf $A$ and $B$ are independent: $P(A \\text{ and } B) = P(A) \\times P(B)$\n:::\n\n## Bayes' Theorem: The Pattern\n\nYou'll almost always use it in this form:\n\n$$\n\\begin{aligned}\nP(A \\mid B) &= \\frac{P(B \\mid A) \\times P(A)}{P(B)} \\\\\n\\\\\n&= \\frac{P(B \\mid A) \\times P(A)}{P(B \\mid A) \\times P(A) + P(B \\mid A^c) \\times P(A^c)}\n\\end{aligned}\n$$\n\\\n\n\\\n\n**In medical testing context:**\n\n$$P(\\text{Disease} \\mid \\text{Test+}) = \\frac{\\text{sensitivity} \\times \\text{prevalence}}{\\text{sensitivity} \\times \\text{prevalence} + (1-\\text{specificity}) \\times (1-\\text{prevalence})}$$\n\n\\\n\n**Pro tip:** Calculate numerator and denominator separately, then divide!\n\n## Bayes' Theorem: Step-by-Step\n\n\\\n\n**Given:** Sensitivity = 0.90, Specificity = 0.85, Prevalence = 0.02\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Set up\nsensitivity <- 0.90     # P(Test + | Disease)\nspecificity <- 0.85     # P(Test - | No Disease)\nprevalence <- 0.02      # P(Disease)\n\n# Step 2: Calculate P(Test + | No Disease)\np_pos_given_healthy <- 1 - specificity\np_pos_given_healthy\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.15\n```\n\n\n:::\n\n```{.r .cell-code}\n# Step 3: Numerator (true positives)\nnumerator <- sensitivity * prevalence\nnumerator\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.018\n```\n\n\n:::\n\n```{.r .cell-code}\n# Step 4: Denominator (all positives)\ndenominator <- sensitivity * prevalence + p_pos_given_healthy * (1 - prevalence)\ndenominator\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.165\n```\n\n\n:::\n\n```{.r .cell-code}\n# Step 5: PPV\nppv <- numerator / denominator\nppv\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1090909\n```\n\n\n:::\n:::\n\n\n\n\n\n\n# Distributions: The R Functions\n\n## The Four Functions Pattern\n\n**Every distribution in R has 4 functions:**\n\n::::: columns\n::: {.column width=\"48%\"}\n**d-functions:** `dbinom()`, `dnorm()`, `dpois()`\n\n- \"density\" or \"probability mass\"\n- **Exactly** x\n- Returns: P(X = x)\n\n\\\n\n**p-functions:** `pbinom()`, `pnorm()`, `ppois()`\n\n- \"cumulative probability\"\n- **At most** x (or **at least** with `lower.tail = FALSE`)\n- Returns: P(X ≤ x) or P(X > x)\n:::\n\n::: {.column width=\"48%\"}\n**q-functions:** `qbinom()`, `qnorm()`, `qpois()`\n\n- \"quantile\"\n- What value gives this probability?\n- Returns: value of x\n\n\\\n\n**r-functions:** `rbinom()`, `rnorm()`, `rpois()`\n\n- \"random\"\n- Generate random samples\n- Returns: random values\n:::\n:::::\n\n## Binomial Functions in R\n\n**The four binomial functions:**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# d = probability of EXACTLY x successes\ndbinom(x = 3, size = 10, prob = 0.5)\n# \"What's P(X = 3)?\"\n\n# p = cumulative probability (at most x OR at least x)\npbinom(q = 3, size = 10, prob = 0.5)\n# \"What's P(X ≤ 3)?\" (default)\n\npbinom(q = 3, size = 10, prob = 0.5, lower.tail = FALSE)\n# \"What's P(X > 3)?\"\n\n# q = quantile (what value gives this probability?)\nqbinom(p = 0.25, size = 10, prob = 0.5)\n# \"What value has 25% of the distribution below it?\"\n\n# r = random samples\nrbinom(n = 100, size = 10, prob = 0.5)\n# \"Give me 100 random draws\"\n```\n:::\n\n\n\n\n## Visual: dbinom() - EXACTLY\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](14_midterm_review_files/figure-revealjs/unnamed-chunk-12-1.png){width=1152}\n:::\n:::\n\n\n\n\n## Visual: pbinom() - AT MOST (default)\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](14_midterm_review_files/figure-revealjs/unnamed-chunk-13-1.png){width=1152}\n:::\n:::\n\n\n\n\n## Visual: pbinom(..., lower.tail = FALSE) - MORE THAN\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](14_midterm_review_files/figure-revealjs/unnamed-chunk-14-1.png){width=1152}\n:::\n:::\n\n\n\n\n## The lower.tail = TRUE/FALSE Concept\n\n::: {.callout-tip icon=\"false\"}\n## Visual Guide\n\n\\\n\n```\n       |--------------●-------------|\n       lower tail     x    upper tail\n       (left)                 (right)\n```\n\n\\\n\n**lower.tail = TRUE** → gives you $P(X \\le x)$ — everything to the **LEFT** of (and including) x\n\n**lower.tail = FALSE** → gives you $P(X \\gt x)$ — everything to the **RIGHT** of x\n:::\n\n\\\n\n**Quick decision rule:**\n\n- Question has \"**less than**\" or \"**at most**\" → `lower.tail = TRUE` (default)\n- Question has \"**greater than**\" or \"**at least**\" → `lower.tail = FALSE`\n\n## Common Confusion: \"At least 5\" (Discrete Distributions)\n\n\\\n\n**Question:** What is $P(X \\ge 5)$ for a binomial distribution?\n\n\\\n\n**Step 1:** Translate to something the computer understands\n\n- \"At least 5\" = \"5 or more\" = \"greater than 4\"\n- So: $P(X \\ge 5)$ = $P(X \\gt 4)$\n\n\n**Step 2:** Code it\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Correct!\npbinom(q = 4, size = 10, prob = 0.5, lower.tail = FALSE)\n\n# Also correct (but slightly more work)\n1 - pbinom(q = 4, size = 10, prob = 0.5)\n```\n:::\n\n\n\n\n\n::: {.callout-important icon=\"false\"}\n## Key Point\n\nFor discrete distributions: \"$X \\ge 5$\" is the same as \"$X \\gt 4$\" because we can't have $4.5$ successes!\n\nThis slide applies to **binomial and Poisson** (discrete).\nFor Normal (continuous), $P(X \\ge 5) = P(X \\gt 5)$ - no adjustment needed!\n:::\n\n\n\n## Practice: Binomial Questions\n\nA vaccine is 75% effective. You vaccinate 20 people.\n\n**Which R function do you use?**\n\n::::: columns\n::: {.column width=\"48%\"}\n**Question 1:** What's the probability that *exactly* 15 are protected?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your answer:\n```\n:::\n\n\n\n\n\\\n\n**Question 2:** What's the probability that *at most* 12 are protected?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your answer:\n```\n:::\n\n\n\n:::\n\n::: {.column width=\"48%\"}\n**Question 3:** What's the probability that *at least* 18 are protected?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your answer:\n```\n:::\n\n\n\n\n\\\n\n**Question 4:** What's the expected number protected?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your answer:\n```\n:::\n\n\n\n:::\n:::::\n\n## Practice: Binomial Answers (1/2)\n\nA vaccine is 75% effective. You vaccinate 20 people.\n\n\\\n\n**Question 1:** What's the probability that *exactly* 15 are protected?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Question 1: Exactly 15\ndbinom(x = 15, size = 20, prob = 0.75)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2023312\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n**Question 2:** What's the probability that *at most* 12 are protected?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Question 2: At most 12\npbinom(q = 12, size = 20, prob = 0.75)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1018119\n```\n\n\n:::\n\n```{.r .cell-code}\n# OR: pbinom(q = 12, size = 20, prob = 0.75, lower.tail = TRUE)\n```\n:::\n\n\n\n\n## Practice: Binomial Answers (2/2)\n\n\\\n\n**Question 3:** What's the probability that *at least* 18 are protected?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Question 3: At least 18 (same as > 17)\npbinom(q = 17, size = 20, prob = 0.75, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09126043\n```\n\n\n:::\n\n```{.r .cell-code}\n# OR: 1 - pbinom(q = 17, size = 20, prob = 0.75)\n```\n:::\n\n\n\n\n\\\n\n**Question 4:** What's the expected number protected?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Question 4: Expected value\nn <- 20\np <- 0.75\nexpected <- n * p\nexpected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15\n```\n\n\n:::\n\n```{.r .cell-code}\n# Bonus: standard deviation\nvariance <- n * p * (1 - p)\nst_dev <- sqrt(variance)\nst_dev\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.936492\n```\n\n\n:::\n:::\n\n\n\n\n## Normal Distribution Functions\n\n**The same pattern applies!**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# d = density (height of curve at x)\ndnorm(x = 120, mean = 100, sd = 15)\n# Rarely used in practice\n\n# p = cumulative probability\npnorm(q = 120, mean = 100, sd = 15)\n# \"What proportion have values ≤ 120?\"\n\npnorm(q = 120, mean = 100, sd = 15, lower.tail = FALSE)\n# \"What proportion have values > 120?\"\n\n# q = quantile (most common!)\nqnorm(p = 0.95, mean = 100, sd = 15)\n# \"What value has 95% below it?\" (95th percentile)\n\n# r = random samples\nrnorm(n = 100, mean = 100, sd = 15)\n# \"Give me 100 random values from this distribution\"\n```\n:::\n\n\n\n\n## Visual: Normal Distribution\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](14_midterm_review_files/figure-revealjs/unnamed-chunk-25-1.png){width=1152}\n:::\n:::\n\n\n\n\n## Practice: Normal Distribution\n\nBlood pressure is Normal with mean = 120 mmHg, sd = 15 mmHg.\n\n**Which R function?**\n\n::::: columns\n::: {.column width=\"48%\"}\n**Question 1:** What proportion have BP above 135?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your answer:\n```\n:::\n\n\n\n\n\\\n\n**Question 2:** What proportion have BP between 110 and 130?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your answer:\n```\n:::\n\n\n\n:::\n\n::: {.column width=\"48%\"}\n**Question 3:** What BP value is the 90th percentile?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your answer:\n```\n:::\n\n\n\n\n\\\n\n**Question 4:** If we want the middle 95%, what are the cutoffs?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your answer:\n```\n:::\n\n\n\n:::\n:::::\n\n## Practice: Normal Answers (1/2)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu <- 120\nsigma <- 15\n\n# Question 1: Above 135\npnorm(135, mean = mu, sd = sigma, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1586553\n```\n\n\n:::\n\n```{.r .cell-code}\n# OR\n1 - pnorm(135, mean = mu, sd = sigma, lower.tail = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1586553\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Question 2: Between 110 and 130\npnorm(130, mean = mu, sd = sigma) - pnorm(110, mean = mu, sd = sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4950149\n```\n\n\n:::\n:::\n\n\n\n\n## Practice: Normal Answers (2/2)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Question 3: 90th percentile\nqnorm(0.90, mean = mu, sd = sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 139.2233\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Question 4: Middle 95% (2.5th to 97.5th percentiles)\nqnorm(0.025, mean = mu, sd = sigma)  # Lower\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 90.60054\n```\n\n\n:::\n\n```{.r .cell-code}\nqnorm(0.975, mean = mu, sd = sigma)  # Upper\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 149.3995\n```\n\n\n:::\n:::\n\n\n\n\n# Sampling Distributions & CLT\n\n## Central Limit Theorem: What You Need to Know\n\n::: {.callout-important icon=\"false\"}\n## The CLT in plain language\n\nFor a random sample of size $n$ from ANY population with mean $\\mu$ and SD $\\sigma$:\n\n**The sampling distribution of** $\\bar{X}$ **is approximately normal when** $n$ **is large ($\\ge 30$)**\n\nWith:\n\n- Mean = $\\mu$\n- Standard Error = $\\sigma / \\sqrt{n}$\n:::\n\n\\\n\n**Why this matters:**\n\n1. We can use normal distribution tools even if data aren't normal\n2. Larger samples → smaller standard error → more precise estimates\n3. This is the foundation for confidence intervals and hypothesis tests!\n\n## Standard Error vs. Standard Deviation\n\n::: {.callout-warning icon=\"false\"}\n## Don't confuse these!\n\n**Standard Deviation ($s$ or $\\sigma$):**\n\n- Measures spread of *individual observations*\n- Describes variability in the data\n- Formula: $s = \\sqrt{\\frac{\\sum(x_i - \\bar{x})^2}{n-1}}$\n\n\\\n\n**Standard Error (SE):**\n\n- Measures uncertainty of the *sample mean*\n- Describes variability of $\\bar{x}$ across (theoretical) samples\n- Formula: $SE = \\frac{s}{\\sqrt{n}}$\n:::\n\n\\\n\n**Key insight:** SE gets smaller as $n$ increases, but $s$ stays roughly the same!\n\n## Example: CLT in Action\n\nPopulation: Mean = 5.1 hours, SD = 1.9 hours, right-skewed\n\nSample: n = 40\n\n**What's the sampling distribution of** $\\bar{X}$?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Parameters\nmu <- 5.1\nsigma <- 1.9\nn <- 40\n\n# Sampling distribution\nmean_xbar <- mu\nse_xbar <- sigma / sqrt(n)\n\nmean_xbar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.1\n```\n\n\n:::\n\n```{.r .cell-code}\nse_xbar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3004164\n```\n\n\n:::\n\n```{.r .cell-code}\n# Example probability about the sample mean, P(Xbar > 5.6)\npnorm(5.6, mean = mean_xbar, sd = se_xbar, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04802059\n```\n\n\n:::\n:::\n\n\n\n\n\\\n\nSampling distribution: approximately Normal(mean = $mu$, sd = $\\frac{s}{\\sqrt{n}}$). Even though the original data are right-skewed!\n\n\n\n# Confidence Intervals\n\n## Confidence Interval Formula\n\n::: {.callout-tip icon=\"false\"}\n## General form\n\n$$\\text{point estimate} \\pm \\text{critical value} \\times SE$$\n\nFor a mean:\n\n$$\\bar{x} \\pm t^* \\times \\frac{s}{\\sqrt{n}}$$\n\nWhere:\n\n- $\\bar{x}$ = sample mean\n- $t^*$ = critical value from t-distribution with $df = n-1$\n- $s$ = sample standard deviation  \n- $n$ = sample size\n:::\n\n## Calculating a 95% CI in R (1/2)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sample data\nn <- 25\nxbar <- 14.2\ns <- 1.8\nconfidence_level <- 0.95\n\n# Step 1: Find critical value\nt_star <- qt((1 + confidence_level) / 2, df = n - 1)\n# OR: qt(0.975, df = 24)\nt_star\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.063899\n```\n\n\n:::\n\n```{.r .cell-code}\n# Step 2: Calculate standard error\nSE <- s / sqrt(n)\nSE\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.36\n```\n\n\n:::\n:::\n\n\n\n\n## Calculating a 95% CI in R (2/2)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 3: Calculate margin of error\nmargin_error <- t_star * SE\nmargin_error\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7430035\n```\n\n\n:::\n\n```{.r .cell-code}\n# Step 4: Build the interval\nlower <- xbar - margin_error\nupper <- xbar + margin_error\n\nc(lower, upper)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13.457 14.943\n```\n\n\n:::\n:::\n\n\n\n\n## Interpreting Confidence Intervals\n\n::: {.callout-important icon=\"false\"}\n## Correct interpretation\n\n\"We are 95% confident that the population mean is between 13.5 and 14.9.\"\n\n**What this means:**\n\n- If we repeated this process many times (new samples, new CIs)\n- About 95% of those intervals would contain the true $\\mu$\n- We don't know if *this specific interval* contains $\\mu$, but we're using a reliable method\n:::\n\n\\\n\n::: {.callout-warning icon=\"false\"}\n## Common mistakes - DON'T SAY:\n\n- ❌ \"There's a 95% probability that $\\mu$ is in this interval\"\n- ❌ \"95% of the data are in this interval\"\n- ❌ \"We're 95% sure the sample mean is in this interval\"\n:::\n\n## What Affects CI Width?\n\n\\\n\n**Margin of error** = $t^* \\times \\frac{s}{\\sqrt{n}}$\n\n\\\n\n**To get a narrower CI:**\n\n1. **Increase sample size** ($n$ ↑ → SE ↓ → narrower CI)\n2. **Decrease confidence level** (95% → 90% → smaller $t^*$ → narrower CI)\n    - But this means less confidence!\n3. **Reduce variability** ($s$ ↓ → SE ↓ → narrower CI)\n    - Often not under our control\n\n\\\n\n**Trade-off:** Precision vs. Confidence\n\n\n\n# Hypothesis Testing\n\n## The Hypothesis Testing Framework\n\n\\\n\n**Six steps:**\n\n1. **State hypotheses:** $H_0$ and $H_A$\n2. **Set significance level:** Usually $\\alpha = 0.05$\n3. **Check assumptions:** Independence, normality/large sample\n4. **Calculate test statistic:** $t = \\frac{\\bar{x} - \\mu_0}{s/\\sqrt{n}}$\n5. **Find p-value:** Probability of seeing data this extreme if $H_0$ true\n6. **Make conclusion:** Reject $H_0$ if p-value < $\\alpha$\n\n## Writing Hypotheses\n\n::: {.callout-tip icon=\"false\"}\n## Template\n\n$H_0: \\mu = \\mu_0$ (null value)\n\n$H_A: \\mu \\neq \\mu_0$ (two-sided) OR $\\mu > \\mu_0$ OR $\\mu < \\mu_0$ (one-sided)\n:::\n\n\\\n\n**Example:** Is mean body temperature different from 98.6°F?\n\n- $H_0: \\mu = 98.6$\n- $H_A: \\mu \\neq 98.6$\n\n\\\n\n**In words:**\n\n- $H_0$: The population mean body temperature is 98.6°F\n- $H_A$: The population mean body temperature is not 98.6°F\n\n## P-values: What They Mean\n\n::: {.callout-important icon=\"false\"}\n## Definition\n\nThe p-value is the probability of observing data as extreme as (or more extreme than) what we observed, **assuming $H_0$ is true**.\n:::\n\n\\\n\n**Interpretation guide:**\n\n- p-value < 0.05 → Strong evidence against $H_0$ → Reject $H_0$\n- p-value ≥ 0.05 → Insufficient evidence → Fail to reject $H_0$\n\n\\\n\n::: {.callout-warning icon=\"false\"}\n## What p-values are NOT\n\n- ❌ NOT the probability that $H_0$ is true\n- ❌ NOT the probability of making an error\n- ❌ NOT a measure of effect size or importance\n:::\n\n## One-Sample t-test in R\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using raw data\nt.test(data$variable, \n       mu = null_value, \n       alternative = \"two.sided\")  # or \"less\" or \"greater\"\n```\n:::\n\n\n\n\n\\\n\n**Example:**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Test if mean pulse rate is different from 72 bpm\ndata(\"nhanes.samp\")\n\nt.test(nhanes.samp$Pulse, \n       mu = 72, \n       alternative = \"two.sided\")\n```\n:::\n\n\n\n\n## Understanding t.test() Output\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  nhanes.samp$Pulse\nt = 2.1383, df = 170, p-value = 0.03392\nalternative hypothesis: true mean is not equal to 72\n95 percent confidence interval:\n 72.15999 76.00376\nsample estimates:\nmean of x \n 74.08187 \n```\n\n\n:::\n:::\n\n\n\n\n\\\n\n**What to report:**\n\n- **t-statistic:** How many SEs away from null value\n- **p-value:** Evidence against $H_0$\n- **95% CI:** Range of plausible values for $\\mu$\n- **Sample mean:** Our point estimate\n\n## Connection: CIs and Hypothesis Tests\n\n::: {.callout-tip icon=\"false\"}\n## Key relationship\n\nFor a two-sided test at $\\alpha = 0.05$:\n\n**If the 95% CI does NOT contain** $\\mu_0$, then we reject $H_0: \\mu = \\mu_0$\n\n**If the 95% CI DOES contain** $\\mu_0$, then we fail to reject $H_0$\n:::\n\n\\\n\n**Both methods use the same math - just different framing!**\n\n- CI: \"What values are plausible for $\\mu$?\"\n- Hypothesis test: \"Is this specific value plausible?\"\n\n\n\n# Final Reminders\n\n## Statistical Significance vs. Practical Significance\n\n::: {.callout-warning icon=\"false\"}\n## Don't confuse these!\n\n**Statistical significance** (p < 0.05):\n\n- Evidence that there's a real effect\n- Doesn't tell you if the effect matters\n\n\\\n\n**Practical/Clinical significance:**\n\n- Effect is large enough to matter in real-world terms\n- You must judge this based on context\n:::\n\n\\\n\n**Example:** A drug lowers blood pressure by 0.5 mmHg (p = 0.001)\n\n- Statistically significant? ✅ Yes\n- Clinically meaningful? ❌ No (too small to affect patient outcomes)\n\n## Common Mistakes to Avoid\n\n1. **Forgetting to check assumptions** before running tests\n2. **Confusing standard deviation and standard error**\n3. **Using `lower.tail = TRUE` when you need `FALSE`** (or vice versa)\n4. **Misinterpreting p-values and confidence intervals**\n5. **Forgetting to include** `na.rm = TRUE` when there are missing values\n6. **Not rendering your document before submitting**\n\n\\\n\n**Pro tip:** When using `pbinom()` or `ppois()`, sketch a quick picture to check if you want the left or right tail!\n\n## Exam Strategy\n\n**Time management:**\n\n- Don't get stuck on one question\n- Move on and come back if needed\n- Leave buffer time for rendering and checking\n\n\\\n\n**Interpretation questions:**\n\n- Write in complete sentences\n- Reference numbers from your calculations\n- Connect to context (not just abstract statistics)\n\n\\\n\n**Coding questions:**\n\n- Show your work (don't just give answers)\n- Use comments to explain your logic\n- Check that your code actually runs!\n\n## Resources\n\n**During the exam:**\n\n- Lecture slides (especially the summary slides)\n- Homework solutions (you've seen similar questions!)\n- R help: `?t.test`, `?pnorm`, etc.\n\n\\\n\n**After you submit:**\n\n- The exam will close Monday at 11 PM\n- Solutions will be available after \n- We'll get feedback to you within a week\n- Remember: This is a learning experience!\n\n\n\n# Questions?\n\n## Your Turn!\n\n**What questions do you have?**\n\n- Concepts that are still unclear?\n- R functions you're unsure about?\n- Specific exam questions you want to discuss?\n\n\\\n\n**Remember:** \n\n- Exam opens today at 3 PM\n- You have until Monday at 11 PM\n- You've got this! 💪\n\n## Good luck!\n\n**You're well prepared:**\n\n- ✅ You've done the homework\n- ✅ You've come to class\n- ✅ You've practiced with R\n- ✅ You know where to find help\n\n\\\n\n**Trust your preparation and think carefully about each question.**\n\n",
    "supporting": [
      "14_midterm_review_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}