{
  "hash": "820e018aa4ceca32da147f7e93a185cc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"BMSC 620 — Homework 8 SOLUTIONS\"\nsubtitle: \"ANOVA and Nonparametric Tests\"\nauthor: \"Instructor solutions\"\nformat: \n  html:\n    embed-resources: true\n    toc: true\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  message: false\n---\n\n\n\n\n## Part 0: Project Setup\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(here)\nlibrary(broom)\nlibrary(rstatix)\nlibrary(janitor)\n```\n:::\n\n\n\n---\n\n## Part 1: One-Way ANOVA\n\n### 1A. Load and explore the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknee <- read_csv(here(\"data\", \"knee_rehab.csv\"))\n\nglimpse(knee)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 150\nColumns: 8\n$ patient_id      <chr> \"KR0001\", \"KR0002\", \"KR0003\", \"KR0004\", \"KR0005\", \"KR0…\n$ protocol        <chr> \"Standard\", \"Standard\", \"Standard\", \"Standard\", \"Stand…\n$ age             <dbl> 70, 70, 62, 52, 72, 72, 68, 65, 74, 62, 57, 60, 67, 64…\n$ sex             <chr> \"Female\", \"Female\", \"Female\", \"Female\", \"Female\", \"Mal…\n$ rom_improvement <dbl> 29.8, 22.3, 22.3, 38.1, 26.6, 31.8, 13.5, 28.1, 28.2, …\n$ pain_score_12wk <dbl> 8, 6, 1, 2, 2, 2, 10, 3, 7, 9, 4, 3, 4, 3, 1, 1, 2, 8,…\n$ tug_before      <dbl> 22.7, 21.4, 35.7, 21.6, 25.0, 13.4, 41.4, 19.9, 21.6, …\n$ tug_after       <dbl> 22.0, 15.9, 30.0, 16.6, 20.7, 8.6, 39.3, 18.1, 19.9, 1…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrom_stats <- knee %>%\n  group_by(protocol) %>%\n  summarise(\n    n    = n(),\n    mean = round(mean(rom_improvement), 1),\n    sd   = round(sd(rom_improvement), 1)\n  )\n\nrom_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  protocol        n  mean    sd\n  <chr>       <int> <dbl> <dbl>\n1 Accelerated    50  25.1   9.4\n2 Aquatic        50  30.7   8.6\n3 Standard       50  25.3   9.3\n```\n\n\n:::\n:::\n\n\n\n**Answer:** The Aquatic group had the highest mean ROM improvement (30.7 degrees), while the Standard group had the lowest (25.3 degrees). The Accelerated group fell in between.\n\n---\n\n### 1B. Visualize the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(knee, aes(x = protocol, y = rom_improvement,\n                 color = protocol, fill = protocol)) +\n  geom_boxplot(alpha = 0.2, outlier.shape = NA) +\n  geom_jitter(alpha = 0.4, width = 0.15) +\n  labs(\n    x = \"Rehabilitation Protocol\",\n    y = \"ROM Improvement (degrees)\",\n    title = \"Range of Motion Improvement by Protocol\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](HW08_solutions_files/figure-html/rom-boxplot-1.png){width=672}\n:::\n:::\n\n\n\n**Answer:** The three groups show similar spread (IQR widths are comparable). The data within each group looks approximately symmetric with no severe skew, supporting the normality assumption for ANOVA.\n\n---\n\n### 1C. State the hypotheses\n\n**Answer:**\n\n$H_0$: $\\mu_\\text{Standard} = \\mu_\\text{Aquatic} = \\mu_\\text{Accelerated}$ — The mean ROM improvement is the same across all three rehabilitation protocols.\n\n$H_A$: At least one pair of means $\\mu_i \\neq \\mu_j$ — The mean ROM improvement differs for at least one pair of rehabilitation protocols.\n\n---\n\n### 1D. Check ANOVA assumptions\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Equal variance: SD ratio\nrom_stats %>%\n  summarise(sd_ratio = max(sd) / min(sd))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  sd_ratio\n     <dbl>\n1     1.09\n```\n\n\n:::\n\n```{.r .cell-code}\n# Sample size per group\nrom_stats %>% select(protocol, n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  protocol        n\n  <chr>       <int>\n1 Accelerated    50\n2 Aquatic        50\n3 Standard       50\n```\n\n\n:::\n:::\n\n\n\n**Answer:** The SD ratio is approximately 1.09, well below the threshold of 2, so the equal variance assumption is met. ✓ All three groups have 50 observations, exceeding the $n \\geq 30$ per group guideline, so the normality assumption is satisfied by the Central Limit Theorem even without checking histograms. ✓ Patients were randomized to independent groups, so independence holds. ✓\n\n---\n\n### 1E. Run the one-way ANOVA\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknee_aov <- aov(rom_improvement ~ protocol, data = knee)\n\nsummary(knee_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value  Pr(>F)   \nprotocol      2   1015   507.3     6.1 0.00285 **\nResiduals   147  12226    83.2                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nknee_aov %>% tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  term         df  sumsq meansq statistic  p.value\n  <chr>     <dbl>  <dbl>  <dbl>     <dbl>    <dbl>\n1 protocol      2  1015.  507.       6.10  0.00285\n2 Residuals   147 12226.   83.2     NA    NA      \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n**Answer:** The F-statistic is 6.1 with df = (2, 147), and the p-value is 0.003.\n\n---\n\n### 1F. Interpret the ANOVA result\n\n**Answer:** There is statistically significant evidence that mean ROM improvement differs across at least one pair of rehabilitation protocols (F(2, 147) = 6.1, p = 0.003). We reject $H_0$ at $\\alpha = 0.05$. This indicates that not all three rehabilitation protocols produce the same average improvement in knee range of motion at 12 weeks, but the ANOVA itself does not tell us which specific pair(s) differ — post-hoc testing is needed.\n\n---\n\n## Part 2: Post-Hoc Comparisons\n\n### 2A. Tukey HSD\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntukey_results <- knee %>%\n  tukey_hsd(rom_improvement ~ protocol)\n\ntukey_results\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  term     group1      group2   null.value estimate conf.low conf.high   p.adj\n* <chr>    <chr>       <chr>         <dbl>    <dbl>    <dbl>     <dbl>   <dbl>\n1 protocol Accelerated Aquatic           0    5.58      1.26      9.90 0.00739\n2 protocol Accelerated Standard          0    0.128    -4.19      4.45 0.997  \n3 protocol Aquatic     Standard          0   -5.45     -9.77     -1.13 0.00915\n# ℹ 1 more variable: p.adj.signif <chr>\n```\n\n\n:::\n:::\n\n\n\n**Answer:** The Tukey HSD reveals that the **Aquatic** protocol produced significantly greater ROM improvement than the **Standard** protocol (mean difference ≈ 5.6 degrees, adjusted p = 0.009). The Aquatic vs. Accelerated and Accelerated vs. Standard comparisons were not statistically significant at $\\alpha = 0.05$.\n\n---\n\n### 2B. Compare adjustment methods\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknee %>%\n  pairwise_t_test(rom_improvement ~ protocol,\n                  p.adjust.method = \"bonferroni\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  .y.            group1 group2    n1    n2       p p.signif   p.adj p.adj.signif\n* <chr>          <chr>  <chr>  <int> <int>   <dbl> <chr>      <dbl> <chr>       \n1 rom_improveme… Accel… Aquat…    50    50 0.00264 **       0.00791 **          \n2 rom_improveme… Accel… Stand…    50    50 0.944   ns       1       ns          \n3 rom_improveme… Aquat… Stand…    50    50 0.00328 **       0.00984 **          \n```\n\n\n:::\n:::\n\n\n\n**Answer:** The Bonferroni results agree with the Tukey HSD — the same pair (Aquatic vs. Standard) is significant, and the other two comparisons are not. This is expected with only 3 pairwise comparisons; Bonferroni and Tukey HSD tend to give similar results when the number of comparisons is small. With many more groups (and thus many more pairwise tests), Bonferroni can become overly conservative compared to Tukey, potentially missing real differences.\n\n---\n\n### 2C. Write a complete report\n\n**Answer:** Mean ROM improvement at 12 weeks was 25.3° (SD = 9.3°) for Standard PT, 30.7° (SD = 8.6°) for Aquatic therapy, and 25.1° (SD = 9.4°) for the Accelerated protocol. A one-way ANOVA indicated a statistically significant difference in mean ROM improvement across the three groups (F(2, 147) = 6.1, p = 0.003). Post-hoc testing using Tukey's HSD revealed that patients in the Aquatic group achieved significantly greater ROM improvement than those in the Standard group (adjusted p = 0.009)). No significant differences were observed between the Accelerated protocol and either of the other two groups.\n\n---\n\n## Part 3: Choosing Between Parametric and Nonparametric\n\n### 3A. Explore the pain score variable\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknee %>%\n  group_by(protocol) %>%\n  summarise(\n    n      = n(),\n    median = median(pain_score_12wk),\n    mean   = round(mean(pain_score_12wk), 1),\n    sd     = round(sd(pain_score_12wk), 1)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  protocol        n median  mean    sd\n  <chr>       <int>  <dbl> <dbl> <dbl>\n1 Accelerated    50      2   2.9   2.3\n2 Aquatic        50      1   1.9   2.4\n3 Standard       50      3   4.2   3.1\n```\n\n\n:::\n:::\n\n\n\n---\n\n### 3B. Visualize the distribution\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(knee, aes(x = protocol, y = pain_score_12wk,\n                 color = protocol, fill = protocol)) +\n  geom_boxplot(alpha = 0.2, outlier.shape = NA) +\n  geom_jitter(alpha = 0.4, width = 0.15) +\n  labs(\n    x = \"Rehabilitation Protocol\",\n    y = \"Pain Score (0–10)\",\n    title = \"Pain Scores at 12 Weeks by Protocol\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](HW08_solutions_files/figure-html/pain-boxplot-1.png){width=672}\n:::\n:::\n\n\n\n**Answer:** The pain score distributions are clearly **right-skewed** in all three groups — most patients report low pain, but some report much higher values. The distributions are not approximately symmetric.\n\n---\n\n### 3C. Check ANOVA assumptions for pain scores\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npain_sds <- knee %>%\n  group_by(protocol) %>%\n  summarise(sd = sd(pain_score_12wk))\n\npain_sds %>%\n  summarise(sd_ratio = max(sd) / min(sd))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  sd_ratio\n     <dbl>\n1     1.38\n```\n\n\n:::\n:::\n\n\n\n**Answer:** While the SD ratio is below 2, the pain score variable is an **ordinal scale** (integers 0–10), and the distributions are **clearly right-skewed** in all groups. ANOVA assumes approximately normal distributions within groups (or large enough samples to rely on CLT), but with strongly skewed ordinal data, the mean is not a particularly meaningful summary and the normal approximation is questionable. The **Kruskal-Wallis test** is more appropriate here because it (1) does not assume normality, (2) works with ordinal data by using ranks, and (3) compares medians rather than means, which better represents the center of skewed distributions.\n\n---\n\n## Part 4: Kruskal-Wallis Test\n\n### 4A. State the hypotheses\n\n**Answer:**\n\n$H_0$: The median pain score at 12 weeks is the same across all three rehabilitation protocols.\n\n$H_A$: The median pain score at 12 weeks differs for at least one pair of rehabilitation protocols.\n\n---\n\n### 4B. Run the Kruskal-Wallis test\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkw_result <- kruskal.test(pain_score_12wk ~ protocol, data = knee)\nkw_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  pain_score_12wk by protocol\nKruskal-Wallis chi-squared = 24.802, df = 2, p-value = 4.115e-06\n```\n\n\n:::\n\n```{.r .cell-code}\nkw_result %>% tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  statistic    p.value parameter method                      \n      <dbl>      <dbl>     <int> <chr>                       \n1      24.8 0.00000412         2 Kruskal-Wallis rank sum test\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n**Answer:** The Kruskal-Wallis test statistic is $H$ = 24.8 with df = 2, and the p-value is < 0.001.\n\n---\n\n### 4C. Post-hoc pairwise comparisons\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknee %>%\n  wilcox_test(pain_score_12wk ~ protocol,\n              p.adjust.method = \"fdr\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  .y.           group1 group2    n1    n2 statistic       p   p.adj p.adj.signif\n* <chr>         <chr>  <chr>  <int> <int>     <dbl>   <dbl>   <dbl> <chr>       \n1 pain_score_1… Accel… Aquat…    50    50     1726. 8.21e-4 1   e-3 **          \n2 pain_score_1… Accel… Stand…    50    50      945  3.2 e-2 3.2 e-2 *           \n3 pain_score_1… Aquat… Stand…    50    50      586. 3.60e-6 1.08e-5 ****        \n```\n\n\n:::\n:::\n\n\n\n**Answer:** After FDR correction, the **Standard** protocol shows significantly higher pain scores than both the **Aquatic** protocol and the **Accelerated** protocol. The comparison between Aquatic and Accelerated is not statistically significant.\n\n---\n\n### 4D. Interpret the results\n\n**Answer:** There is strong evidence that median 12-week pain scores differ across the three rehabilitation protocols (Kruskal-Wallis test, $H$ = 24.8, df = 2, p = < 0.001). Pairwise Wilcoxon rank-sum tests with FDR correction indicate that patients in the Standard protocol reported significantly higher pain (median = 3) compared to both the Aquatic group (median = 1) and the Accelerated group (median = 2). The Aquatic and Accelerated groups did not differ significantly from each other.\n\n---\n\n## Part 5: Wilcoxon Signed-Rank Test (Paired Data)\n\n### 5A. Explore the TUG data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknee <- knee %>%\n  mutate(tug_diff = tug_before - tug_after)\n\nknee %>%\n  summarise(\n    mean_diff   = round(mean(tug_diff), 1),\n    median_diff = round(median(tug_diff), 1),\n    sd_diff     = round(sd(tug_diff), 1)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  mean_diff median_diff sd_diff\n      <dbl>       <dbl>   <dbl>\n1       4.3         4.4     2.5\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(knee, aes(x = tug_before)) +\n  geom_histogram(binwidth = 2, fill = \"#0072B2\", color = \"white\",\n                 alpha = 0.7) +\n  labs(\n    x = \"TUG Time Before Rehabilitation (seconds)\",\n    y = \"Count\",\n    title = \"Distribution of Baseline TUG Times\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](HW08_solutions_files/figure-html/tug-histogram-1.png){width=672}\n:::\n:::\n\n\n\n**Answer:** The baseline TUG times are **right-skewed** — most patients have TUG times in the 15–25 second range, but a tail of patients take considerably longer. This is typical of timing data. The mean difference (before − after) is positive, indicating improvement on average.\n\n---\n\n### 5B. Justify the nonparametric approach\n\n**Answer:** The TUG times are clearly right-skewed, and the differences inherit some of this skew. While the sample size is moderately large ($n = 150$), the Wilcoxon signed-rank test is more appropriate than a paired *t*-test because timing data is inherently skewed — a few patients with much longer TUG times could unduly influence the mean difference. The signed-rank test is robust to this skew because it operates on ranks rather than raw values.\n\n---\n\n### 5C. State the hypotheses\n\n**Answer:**\n\n$H_0$: The median difference in TUG time (before − after) is zero — rehabilitation does not change functional mobility.\n\n$H_A$: The median difference in TUG time (before − after) is not zero — rehabilitation changes functional mobility.\n\n---\n\n### 5D. Run the Wilcoxon signed-rank test\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsr_result <- knee %>%\n  wilcox_test(tug_diff ~ 1, mu = 0,\n              alternative = \"two.sided\")\n\nsr_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  .y.      group1 group2         n statistic        p\n* <chr>    <chr>  <chr>      <int>     <dbl>    <dbl>\n1 tug_diff 1      null model   150    11124. 9.55e-26\n```\n\n\n:::\n:::\n\n\n\n---\n\n### 5E. Interpret the results\n\n\n\n::: {.cell}\n\n:::\n\n\n\n**Answer:** The Wilcoxon signed-rank test provides very strong evidence that TUG times improved after rehabilitation ($T^+$ = 11 123.5, p < 0.001). The median improvement in TUG time was 4.4 seconds, indicating that patients walked faster after 12 weeks of rehabilitation regardless of protocol. We reject $H_0$ at $\\alpha = 0.05$ and conclude that the rehabilitation programs significantly improved functional mobility as measured by the TUG test.\n",
    "supporting": [
      "HW08_solutions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}